export default function smartDayPlanner328(){
  return {
    name:'smart-day-planner-v328',
    enforce:'pre',
    transform(code,id){
      if(!id.endsWith('/src/App.jsx'))return null
      const start=code.indexOf('function CoachPage('),end=code.indexOf('\nfunction ProfilePage(',start)
      if(start<0||end<0)throw new Error('V2.0.166 CoachPage transform target not found')
      const next=`function CoachPage({onBack,onSaved}){
  const weekdays=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag']
  const profile=useMemo(()=>{const p=readStore('ft-equipment-profile',null)?.equipment||readStore('ft-available-equipment-v238',null)||{};const hasWeights=k=>Array.isArray(readStore(k,[]))&&readStore(k,[]).length>0;return{Kurzhanteln:p.dumbbell??hasWeights('ft-dumbbell-weights'),Bank:!!(p.bench??p.bank),Körpergewicht:p.bodyweight!==false,Widerstandsbänder:!!p.band,Langhantel:p.barbell??hasWeights('ft-barbell-weights'),Landmine:!!p.landmine,Kettlebell:!!p.kettlebell,Kabelzug:!!(p.cable??p.machine),Maschinen:!!p.machine,'TRX/Schlingentrainer':!!(p.trx??p.suspension),Klimmzugstange:!!(p.pullupBar??p.pullup), 'Dip-Barren':!!(p.dipBars??p.dip),Medizinball:!!p.medicineBall,Gymnastikball:!!p.stabilityBall,BOSU:!!p.bosu,'Stepper/Box':!!(p.box??p.stepBox),'Indoor Bike':!!p.bike,Rudergerät:!!p.rower,Laufband:!!p.treadmill,Crosstrainer:!!(p.elliptical??p.crosstrainer),Stepper:!!p.stepper,Springseil:!!(p.jumpRope??p.rope)}} ,[])
  const strengthEquipment=Object.keys(profile).filter(x=>!['Indoor Bike','Rudergerät','Laufband','Crosstrainer','Stepper','Springseil'].includes(x)&&profile[x])
  const cardioEquipment=['Indoor Bike','Rudergerät','Laufband','Crosstrainer','Stepper','Springseil'].filter(x=>profile[x])
  const[goal,setGoal]=useState('Muskelaufbau'),[focus,setFocus]=useState('Ausgeglichen'),[minutes,setMinutes]=useState(60)
  const defaults=type=>type==='Cardio'?cardioEquipment:strengthEquipment
  const[days,setDays]=useState(()=>({Montag:{type:'Kraft',equipment:[...strengthEquipment]},Dienstag:{type:'Cardio',equipment:[...cardioEquipment]},Mittwoch:{type:'Kraft',equipment:[...strengthEquipment]},Donnerstag:{type:'Cardio',equipment:[...cardioEquipment]},Freitag:{type:'Kraft',equipment:[...strengthEquipment]},Samstag:{type:'Frei',equipment:[]},Sonntag:{type:'Frei',equipment:[]}}))
  const setType=(day,type)=>setDays(v=>({...v,[day]:{...v[day],type,equipment:type==='Frei'?[]:[...defaults(type)]}}))
  const toggleEq=(day,eq)=>setDays(v=>{const cur=v[day].equipment||[],has=cur.includes(eq);return{...v,[day]:{...v[day],equipment:has?cur.filter(x=>x!==eq):[...cur,eq]}}})
  const strengthFor=cfg=>{const e=cfg.equipment||[],has=x=>e.includes(x),list=[];if(has('Kurzhanteln'))list.push(ex('Kurzhantel-Bankdrücken',3,'8–12'),ex('Kurzhantel-Schulterdrücken',3,'8–12'),ex('Kurzhantel-Seitheben',3,'12–15'),ex('Kurzhantel-Bizeps-Curl',2,'10–15'),ex('Kurzhantel-Rumänisches Kreuzheben',3,'8–12'),ex('Kurzhantel-Rudern',3,'8–12'),ex('Goblet Squat',3,'8–12'));if(has('Körpergewicht'))list.push(ex('Liegestütz',3,'8–15'),ex('Kniebeuge mit Körpergewicht',3,'10–20'),ex('Ausfallschritte mit Körpergewicht',3,'8–15'));if(has('Widerstandsbänder'))list.push({name:'Rudern mit Widerstandsband',query:'band seated row',sets:3,reps:'10–15',equipment:'Widerstandsband'});if(has('Langhantel'))list.push({name:'Langhantel-Kniebeuge',query:'barbell squat',sets:3,reps:'6–10',equipment:'Langhantel'});if(has('Landmine'))list.push({name:'Landmine Press',query:'landmine press',sets:3,reps:'8–12',equipment:'Landmine'});if(has('Kettlebell'))list.push({name:'Kettlebell Goblet Squat',query:'kettlebell goblet squat',sets:3,reps:'8–12',equipment:'Kettlebell'});if(has('Kabelzug'))list.push({name:'Kabelrudern',query:'cable seated row',sets:3,reps:'8–12',equipment:'Kabelzug'});if(has('Klimmzugstange'))list.push({name:'Klimmzüge',query:'pull up',sets:3,reps:'6–12',equipment:'Klimmzugstange'});if(has('Dip-Barren'))list.push({name:'Dips',query:'chest dip',sets:3,reps:'6–12',equipment:'Dip-Barren'});return[...new Map(list.map(x=>[x.name,x])).values()].slice(0,Math.max(3,Math.min(7,Math.floor((minutes-5)/8))))}
  const cardioFor=cfg=>{const e=cfg.equipment||[],xs=[];[['Indoor Bike','bike'],['Rudergerät','rowing'],['Laufband','treadmill'],['Crosstrainer','elliptical'],['Stepper','stepper'],['Springseil','jump rope']].forEach(([name,query])=>{if(e.includes(name))xs.push({name,query,kind:'cardio',loadType:'cardio',category:'Cardio',equipment:name,minutes})});return xs}
  const sessions=useMemo(()=>weekdays.filter(day=>days[day].type!=='Frei').map(day=>{const cfg=days[day],allowed=cfg.type==='Cardio'?cardioEquipment:strengthEquipment,safe={...cfg,equipment:(cfg.equipment||[]).filter(x=>allowed.includes(x))},xs=safe.type==='Cardio'?cardioFor(safe):strengthFor(safe);return{title:day+' · '+safe.type,day,weekday:day,type:safe.type,duration:minutes,goal,equipment:[...safe.equipment],exercises:xs}}),[days,goal,minutes])
  const save=()=>{const plans=readStore('ft-plans',[]),active=weekdays.filter(d=>days[d].type!=='Frei');if(!active.length)return;writeStore('ft-plans',[...plans,{name:'Smart Plan · '+goal+' · '+active.length+' Tage',smart:true,days:active.length,weekStartsOn:'Montag',minutes,goal,focus,dayConfig:days,sessions,createdAt:Date.now()}]);try{window.FitTogetherCloud?.upload?.()}catch{};onSaved()}
  return <SimplePage title="Smarter Trainer" kicker="PLAN ERSTELLEN" text="Pro Tag kannst du nur Equipment auswählen, das in deinem Equipment-Profil vorhanden ist." onBack={onBack}><div className="coach-settings"><label><span>Dein Ziel</span><select value={goal} onChange={e=>setGoal(e.target.value)}><option>Muskelaufbau</option><option>Kraft</option><option>Allgemeine Fitness</option></select></label><label><span>Zeit pro Training</span><select value={minutes} onChange={e=>setMinutes(Number(e.target.value))}>{[30,45,60,75,90].map(m=><option key={m}>{m}</option>)}</select></label><label><span>Schwerpunkt</span><select value={focus} onChange={e=>setFocus(e.target.value)}><option>Ausgeglichen</option><option>Brust</option><option>Rücken</option><option>Beine</option><option>Schultern</option><option>Arme</option></select></label></div><div className="smart-week-v328"><div className="smart-week-head-v328"><small>TRAININGSWOCHE · MONTAG BIS SONNTAG</small><strong>Deine Tage</strong></div>{weekdays.map(day=>{const cfg=days[day],allowed=cfg.type==='Cardio'?cardioEquipment:cfg.type==='Kraft'?strengthEquipment:[];return <div className={'smart-day-v328 '+cfg.type.toLowerCase()} key={day}><div className="smart-day-top-v328"><strong>{day}</strong><div>{['Kraft','Cardio','Frei'].map(t=><button type="button" className={cfg.type===t?'active':''} onClick={()=>setType(day,t)} key={t}>{t}</button>)}</div></div>{cfg.type!=='Frei'&&<div className="smart-eq-v328"><small>Von deinem vorhandenen Equipment:</small><div>{allowed.map(eq=><button type="button" className={cfg.equipment.includes(eq)?'active':''} onClick={()=>toggleEq(day,eq)} key={eq}>{cfg.equipment.includes(eq)?'✓ ':''}{eq}</button>)}</div>{!allowed.length&&<em>Für diese Trainingsart ist in Einstellungen noch kein Equipment hinterlegt.</em>}{allowed.length>0&&!cfg.equipment.some(x=>allowed.includes(x))&&<em>Mindestens ein Gerät auswählen.</em>}</div>}</div>})}</div><div className="coach-suggestion"><Brain size={28}/><small>DEIN WOCHENPLAN</small><h2>{goal} · {sessions.length} Trainingstage</h2><div className="coach-plan-preview">{sessions.map(s=><div key={s.day}><b>{s.day.toUpperCase()}</b><span>{s.type} · {s.equipment.join(' + ')||'kein Equipment'} · {s.exercises.length} Übungen</span></div>)}</div><button className="primary-action" disabled={!sessions.length||sessions.some(s=>!s.equipment.length||!s.exercises.length)} onClick={save}><Check size={18}/> Plan speichern</button></div></SimplePage>
}`
      return {code:code.slice(0,start)+next+code.slice(end),map:null}
    },
  }
}
