export default function cardioSearch302(){
  return {
    name:'cardio-search-v302',
    enforce:'pre',
    transform(code,id){
      if(!id.endsWith('/src/App.jsx'))return null
      let next=code

      const exercisesMarker='function Exercises({onBack})'
      if(!next.includes(exercisesMarker))throw new Error('V2.0.121 Exercises target not found')
      const helpers=`const normSearch302=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9äöüß]+/g,' ').trim()\nconst exerciseMatches302=(x,q)=>{const n=normSearch302(q);if(!n)return true;const hay=normSearch302([x?.name,germanName(x?.name),x?.muscle,x?.bodyPart,x?.equipment].filter(Boolean).join(' '));if(hay.includes(n))return true;const aliases=[];if(/fahrrad|ergometer/.test(n))aliases.push('bike','bicycle','cycle','cycling','stationary bike','ergometer');if(/ruder|rudern/.test(n))aliases.push('rower','rowing','rowing machine');if(/laufband|laufen/.test(n))aliases.push('treadmill','running');if(/kurzhantel/.test(n))aliases.push('dumbbell');if(/langhantel/.test(n))aliases.push('barbell');return aliases.some(a=>hay.includes(normSearch302(a)))}\nconst cardioQuery302=x=>{const t=normSearch302([x?.name,x?.query,x?.equipment].filter(Boolean).join(' '));if(/fahrrad|ergometer|bike|bicycle|cycle|cycling/.test(t))return'stationary bike';if(/ruder|rower|rowing/.test(t))return'rowing machine';if(/laufband|treadmill/.test(t))return'treadmill';return x?.query||x?.name}\n`
      next=next.replace(exercisesMarker,helpers+exercisesMarker)

      const oldSearch="(!query||`${x.name} ${germanName(x.name)}`.toLowerCase().includes(query.toLowerCase()))"
      if(!next.includes(oldSearch))throw new Error('V2.0.121 exercise search predicate not found')
      next=next.replace(oldSearch,'exerciseMatches302(x,query)')

      const marker="const current=exercises[index],restSeconds=readStore('ft-timer-default',90);"
      if(!next.includes(marker))throw new Error('V2.0.121 ActiveTraining marker not found')
      const cardioState="const cardioExercise302=(()=>{const t=normSearch302([current?.kind,current?.category,current?.bodyPart,current?.muscle,current?.equipment,current?.name,current?.query].filter(Boolean).join(' '));return /cardio|cardiovascular|fahrrad|ergometer|bike|bicycle|cycling|cycle|laufband|treadmill|rudergerät|rower|rowing/.test(t)})();const[cardioMinutes302,setCardioMinutes302]=useState(()=>Math.max(1,Number(current?.duration||current?.minutes)||20)),[cardioMode302,setCardioMode302]=useState('manual'),[cardioRemaining302,setCardioRemaining302]=useState(()=>Math.max(1,Number(current?.duration||current?.minutes)||20)*60),[cardioRunning302,setCardioRunning302]=useState(false),[cardioDeadline302,setCardioDeadline302]=useState(0),[cardioRunStarted302,setCardioRunStarted302]=useState(0),[cardioAccumulated302,setCardioAccumulated302]=useState(0),[cardioFinished302,setCardioFinished302]=useState(false);useEffect(()=>{if(!cardioExercise302)return;const mins=Math.max(1,Number(current?.duration||current?.minutes)||20);setCardioMinutes302(mins);setCardioRemaining302(mins*60);setCardioMode302('manual');setCardioRunning302(false);setCardioDeadline302(0);setCardioRunStarted302(0);setCardioAccumulated302(0);setCardioFinished302(false)},[index,cardioExercise302]);const fmtCardio302=v=>Math.floor(Math.max(0,v)/60)+':'+String(Math.max(0,v)%60).padStart(2,'0');const notifyCardio302=()=>{try{navigator.vibrate?.([180,80,180])}catch{};try{const C=window.AudioContext||window.webkitAudioContext;if(C){const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.value=.07;o.start();o.stop(c.currentTime+.18)}}catch{}};useEffect(()=>{if(!cardioExercise302||!cardioRunning302||!cardioDeadline302)return;let done=false;const tick=()=>{const left=Math.max(0,Math.ceil((cardioDeadline302-Date.now())/1000));setCardioRemaining302(left);if(left<=0&&!done){done=true;const extra=cardioRunStarted302?Math.max(0,Date.now()-cardioRunStarted302):0;setCardioAccumulated302(v=>v+extra);setCardioRunStarted302(0);setCardioRunning302(false);setCardioFinished302(true);notifyCardio302()}};tick();const timer=setInterval(tick,250);const vis=()=>{if(document.visibilityState==='visible')tick()};document.addEventListener('visibilitychange',vis);window.addEventListener('pageshow',vis);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',vis);window.removeEventListener('pageshow',vis)}},[cardioExercise302,cardioRunning302,cardioDeadline302,cardioRunStarted302]);"
      next=next.replace(marker,marker+cardioState)

      const mediaLookup='setMedia(findExerciseMedia(items,current))'
      if(!next.includes(mediaLookup))throw new Error('V2.0.121 media lookup target not found')
      next=next.replace(mediaLookup,"setMedia(findExerciseMedia(items,cardioExercise302?{...current,query:cardioQuery302(current)}:current))")

      const mediaOld='{media?.gifUrl?<img src={media.gifUrl} alt={current.name}/>:<div className="media-loading"><Dumbbell size={32}/><small>Bild wird geladen…</small></div>}'
      if(!next.includes(mediaOld))throw new Error('V2.0.121 media render target not found')
      next=next.replace(mediaOld,'{(current?.gifUrl||current?.image||media?.gifUrl)?<img src={current?.gifUrl||current?.image||media?.gifUrl} alt={current.name}/>:<div className="media-loading"><Dumbbell size={32}/><small>Bild wird geladen…</small></div>}')

      const descOld="<p>{current.sets||3} Sätze · {current.reps||'8–12'} Wiederholungen</p>"
      if(!next.includes(descOld))throw new Error('V2.0.121 exercise description target not found')
      next=next.replace(descOld,"<p>{cardioExercise302?(cardioMode302==='timer'?`${fmtCardio302(cardioRemaining302)} verbleibend`:`${cardioMinutes302} Min. Cardio`):`${current.sets||3} Sätze · ${current.reps||'8–12'} Wiederholungen`}</p>")

      const setPrefix='{!current.warmup&&<div className="set-card compact-set-card">'
      if(!next.includes(setPrefix))throw new Error('V2.0.121 set card target not found')
      next=next.replace(setPrefix,'{!current.warmup&&!cardioExercise302&&<div className="set-card compact-set-card">')

      const nextDef="const nextExercise=()=>{setResting(false);if(index<exercises.length-1){setIndex(i=>i+1);setSet(1);setTip('Neue Übung · sauber starten')}else setFinished(true)};"
      if(!next.includes(nextDef))throw new Error('V2.0.121 nextExercise target not found')
      const cardioFns="const saveCardio302=(seconds,mode)=>{const durationSeconds=Math.max(1,Math.round(Number(seconds)||0)),logs=readStore('ft-active-set-logs-v277',[]);logs.push({exercise:current.name,exerciseIndex:index,set:1,durationSeconds,durationMinutes:Math.max(1,Math.round(durationSeconds/60)),targetMinutes:Math.max(1,Number(cardioMinutes302)||1),kind:'cardio',loadType:'cardio',entryMode:mode});writeStore('ft-active-set-logs-v277',logs);nextExercise()};const finishCardio302=()=>{if(cardioMode302==='manual'){saveCardio302(Math.max(1,Number(cardioMinutes302)||1)*60,'manual');return}const live=cardioRunning302&&cardioRunStarted302?Math.max(0,Date.now()-cardioRunStarted302):0,actual=Math.max(1000,cardioAccumulated302+live);setCardioRunning302(false);setCardioRunStarted302(0);saveCardio302(actual/1000,'timer')};const startPauseCardio302=()=>{if(cardioFinished302)return;if(cardioRunning302){const now=Date.now(),segment=cardioRunStarted302?Math.max(0,now-cardioRunStarted302):0,left=Math.max(0,Math.ceil((cardioDeadline302-now)/1000));setCardioAccumulated302(v=>v+segment);setCardioRunStarted302(0);setCardioRemaining302(left);setCardioRunning302(false);return}const seconds=Math.max(1,Number(cardioRemaining302)||Math.max(1,Number(cardioMinutes302)||1)*60),now=Date.now();setCardioRemaining302(seconds);setCardioDeadline302(now+seconds*1000);setCardioRunStarted302(now);setCardioRunning302(true)};const adjustCardio302=delta=>{if(cardioFinished302)return;const nextSeconds=Math.max(60,(Number(cardioRemaining302)||0)+delta);setCardioRemaining302(nextSeconds);setCardioMinutes302(Math.max(1,Math.round(nextSeconds/60)));if(cardioRunning302)setCardioDeadline302(d=>Math.max(Date.now()+1000,d+delta*1000))};"
      next=next.replace(nextDef,nextDef+cardioFns)

      const buttonOld='<button className="primary-action compact-action" onClick={()=>current.warmup?advance():setRirOpen(true)}><Check size={19}/> {current.warmup?`Aufwärmen ${set} abschließen`:`Satz ${set} abschließen`}</button>'
      if(!next.includes(buttonOld))throw new Error('V2.0.121 primary action target not found')
      const buttonNew='<>{cardioExercise302&&<div className="cardio-card-v302"><div className="cardio-mode-v302"><button type="button" className={cardioMode302===\'manual\'?\'active\':\'\'} onClick={()=>{if(cardioRunning302)return;setCardioMode302(\'manual\');setCardioFinished302(false)}}>Nachtragen</button><button type="button" className={cardioMode302===\'timer\'?\'active\':\'\'} onClick={()=>{setCardioMode302(\'timer\');setCardioRemaining302(Math.max(1,Number(cardioMinutes302)||1)*60);setCardioFinished302(false)}}>Timer starten</button></div>{cardioMode302===\'manual\'?<><span>TRAININGSDAUER EINTRAGEN</span><label className="cardio-manual-v302"><input inputMode="numeric" value={cardioMinutes302} onChange={e=>setCardioMinutes302(Math.max(1,Number(e.target.value)||1))}/><small>Min.</small></label><p>Für Einheiten, die du z. B. mit Apple Watch oder Fahrradcomputer aufgezeichnet hast.</p></>:<><span>{cardioFinished302?\'ZEIT ABGELAUFEN\':cardioRunning302?\'CARDIO LÄUFT\':\'ZIELZEIT\'}</span><strong className="cardio-clock-v302">{fmtCardio302(cardioRemaining302)}</strong>{!cardioRunning302&&!cardioFinished302&&<div className="cardio-target-v302"><button type="button" onClick={()=>adjustCardio302(-60)}>−1 Min.</button><input inputMode="numeric" value={cardioMinutes302} onChange={e=>{const m=Math.max(1,Number(e.target.value)||1);setCardioMinutes302(m);setCardioRemaining302(m*60)}}/><button type="button" onClick={()=>adjustCardio302(60)}>+1 Min.</button></div>}{cardioRunning302&&<div className="cardio-adjust-v302"><button type="button" onClick={()=>adjustCardio302(-60)}>−1 Min.</button><button type="button" onClick={()=>adjustCardio302(60)}>+1 Min.</button></div>}<button type="button" className="cardio-start-v302" onClick={startPauseCardio302} disabled={cardioFinished302}>{cardioRunning302?\'Pause\':cardioAccumulated302>0?\'Weiter\':\'Start\'}</button><p>{cardioFinished302?\'Zielzeit erreicht. Du kannst die Einheit jetzt speichern.\':\'Die Zeit läuft auch korrekt weiter, wenn die App kurz im Hintergrund ist.\'}</p></>}</div>}<button className="primary-action compact-action" onClick={()=>current.warmup?advance():cardioExercise302?finishCardio302():setRirOpen(true)}><Check size={19}/> {current.warmup?`Aufwärmen ${set} abschließen`:cardioExercise302?(cardioMode302===\'manual\'?\'Cardio nachtragen\':\'Cardio beenden & speichern\'):`Satz ${set} abschließen`}</button></>'
      next=next.replace(buttonOld,buttonNew)

      next=next.replace("kind:'strength',sets:logs,version:'V2.0.87'","kind:logs.length&&logs.every(x=>x?.kind==='cardio')?'cardio':'strength',sets:logs,version:'V2.0.121'")

      return {code:next,map:null}
    }
  }
}
