// FitTogether V2.0.21: per-exercise values, pause settings and set history.
const FT221_SETTINGS='ft-exercise-settings'
const FT221_HISTORY='ft-exercise-history'
const read221=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
const write221=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
const norm221=s=>String(s||'').trim().toLowerCase()
const getSettings221=name=>read221(FT221_SETTINGS,{})[norm221(name)]||{}
const saveSettings221=(name,patch)=>{const all=read221(FT221_SETTINGS,{}),key=norm221(name);all[key]={...(all[key]||{}),...patch,name,updatedAt:Date.now()};write221(FT221_SETTINGS,all);return all[key]}
const getHistory221=name=>read221(FT221_HISTORY,[]).filter(x=>norm221(x.exercise)===norm221(name))
const recordSet221=entry=>{const list=read221(FT221_HISTORY,[]);write221(FT221_HISTORY,[...list,{...entry,date:Date.now()}].slice(-600))}
const recommendation221=(rir,weight,reps)=>{const w=Number(weight)||0,r=Number(reps)||0;if(rir<=0)return`Sehr hart – nächstes Mal ${w?w+' kg halten und ':''}${Math.max(1,r-2)}–${Math.max(1,r-1)} Wdh. anpeilen.`;if(rir===1)return`Hart – ${w?w+' kg halten':'Gewicht halten'} und etwa ${Math.max(1,r-1)}–${r} Wdh. anpeilen.`;if(rir===2)return`Perfekt – ${w?w+' kg beibehalten':'Gewicht beibehalten'} und ${r} Wdh. bestätigen.`;if(rir===3)return`Noch Reserve – ${w?w+' kg halten und ':''}${r+1} Wdh. anpeilen.`;return w?`Zu leicht – nächstes Mal Gewicht leicht über ${w} kg steigern oder ${r+2} Wdh. anpeilen.`:`Zu leicht – nächstes Mal Widerstand oder Wiederholungen erhöhen.`}
const setReactValue221=(input,value)=>{if(!input||value===undefined||value===null||value==='')return;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;setter?.call(input,String(value));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}
let pending221=null
let activeName221=''
let originalRest221=null
const currentTraining221=()=>document.querySelector('.active-training.compact-training')
const currentName221=()=>currentTraining221()?.querySelector('.exercise-stage h1')?.textContent?.trim()||''
const currentInputs221=()=>{const card=currentTraining221()?.querySelector('.set-card.compact-set-card');const inputs=card?[...card.querySelectorAll('input')]:[];return{card,weight:inputs[0],reps:inputs[1]}}
const renderHistory221=name=>{const host=currentTraining221()?.querySelector('.ft221-history');if(!host)return;const history=getHistory221(name).slice(-3).reverse();const last=history[0];host.innerHTML=`<div class="ft221-history-head"><strong>Übungsverlauf</strong>${last?`<small>Letzter Satz · ${new Date(last.date).toLocaleDateString('de-DE')}</small>`:'<small>Noch keine gespeicherten Sätze</small>'}</div>${last?`<div class="ft221-last"><b>${last.weight||0} kg × ${last.reps||0}</b><span>RIR ${last.rir}</span></div><p>${last.recommendation||recommendation221(last.rir,last.weight,last.reps)}</p>`:'<p>Gewicht, Wiederholungen und RIR werden ab dem ersten Satz pro Übung gespeichert.</p>'}`}
const enhanceActive221=()=>{const training=currentTraining221();if(!training){if(originalRest221!==null){write221('ft-timer-default',originalRest221);originalRest221=null}activeName221='';return}const name=currentName221();if(!name)return;const{card,weight,reps}=currentInputs221();if(!card)return;if(originalRest221===null)originalRest221=read221('ft-timer-default',90);const saved=getSettings221(name);if(activeName221!==name){activeName221=name;const hist=getHistory221(name),last=hist.at(-1);setTimeout(()=>{const now=currentInputs221();setReactValue221(now.weight,saved.weight??last?.weight);setReactValue221(now.reps,saved.reps??last?.reps)},0);write221('ft-timer-default',saved.restSeconds??originalRest221)}if(!card.querySelector('.ft221-pause-row')){const row=document.createElement('div');row.className='ft221-pause-row';row.innerHTML=`<label><span>Pause für diese Übung</span><div><input inputmode="numeric" value="${saved.restSeconds??originalRest221}"><small>Sek.</small></div></label>`;card.appendChild(row);const pauseInput=row.querySelector('input');pauseInput.addEventListener('input',()=>{const n=Math.max(10,Math.min(600,Number(pauseInput.value)||0));saveSettings221(name,{restSeconds:n});write221('ft-timer-default',n)})}if(!training.querySelector('.ft221-history')){const box=document.createElement('div');box.className='ft221-history';card.insertAdjacentElement('afterend',box);renderHistory221(name)}if(!card.dataset.ft221Inputs){card.dataset.ft221Inputs='1';weight?.addEventListener('input',()=>saveSettings221(currentName221(),{weight:Number(weight.value)||0}));reps?.addEventListener('input',()=>saveSettings221(currentName221(),{reps:Number(reps.value)||0}))}renderHistory221(name)}
const enhanceSingle221=()=>{const overlay=document.querySelector('.single-training-v220');if(!overlay)return;const name=overlay.querySelector('h1')?.textContent?.trim()||overlay.querySelector('.single-head-v220 strong')?.textContent?.trim()||'';const inputs=[...overlay.querySelectorAll('.single-inputs-v220 input')];if(!name||inputs.length<2)return;const saved=getSettings221(name),hist=getHistory221(name),last=hist.at(-1);if(!overlay.dataset.ft221){overlay.dataset.ft221='1';setReactValue221(inputs[0],saved.weight??last?.weight);setReactValue221(inputs[1],saved.reps??last?.reps);inputs[0].addEventListener('input',()=>saveSettings221(name,{weight:Number(inputs[0].value)||0}));inputs[1].addEventListener('input',()=>saveSettings221(name,{reps:Number(inputs[1].value)||0}));const box=document.createElement('div');box.className='ft221-single-history';box.innerHTML=last?`<strong>Letzter Satz</strong><span>${last.weight||0} kg × ${last.reps||0} · RIR ${last.rir}</span><small>${last.recommendation||''}</small>`:'<strong>Erster Durchgang</strong><small>Werte werden für diese Übung gespeichert.</small>';overlay.querySelector('.single-inputs-v220')?.insertAdjacentElement('afterend',box)}}
document.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.matches('.primary-action.compact-action')&&!currentTraining221()?.querySelector('.exercise-stage small')?.textContent?.includes('DEHN')){const name=currentName221(),{weight,reps}=currentInputs221();pending221={exercise:name,weight:Number(weight?.value)||0,reps:Number(reps?.value)||0};saveSettings221(name,{weight:pending221.weight,reps:pending221.reps})}const rirBtn=btn.closest('.rir-options button');if(rirBtn&&pending221){const raw=rirBtn.querySelector('strong')?.textContent?.trim()||'0',rir=raw.includes('+')?4:Number(raw)||0;const recommendation=recommendation221(rir,pending221.weight,pending221.reps);recordSet221({...pending221,rir,recommendation});pending221=null;setTimeout(()=>renderHistory221(currentName221()),30)}if(btn.matches('.single-done-v220')){const overlay=document.querySelector('.single-training-v220'),name=overlay?.querySelector('h1')?.textContent?.trim()||'';const ins=[...overlay?.querySelectorAll('.single-inputs-v220 input')||[]];if(name&&ins.length>=2){const weight=Number(ins[0].value)||0,reps=Number(ins[1].value)||0;saveSettings221(name,{weight,reps});recordSet221({exercise:name,weight,reps,rir:2,recommendation:'Einzelübung gespeichert – beim nächsten Start werden diese Werte wieder geladen.'})}}},true)
const updateVersion221=()=>document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0&&el.textContent?.includes('V2.0.20'))el.textContent=el.textContent.replaceAll('V2.0.20','V2.0.21')})
const enhance221=()=>{enhanceActive221();enhanceSingle221();updateVersion221()}
if(typeof document!=='undefined'){const obs221=new MutationObserver(enhance221);const start221=()=>{enhance221();obs221.observe(document.body,{childList:true,subtree:true})};document.body?start221():document.addEventListener('DOMContentLoaded',start221,{once:true})}
