// FitTogether V2.0.25: stronger German exercise naming across library, detail, swap and training views.
const FT225_VERSION='V2.0.25'
const exact225=new Map(Object.entries({
  'push up':'Liegestütz','push-up':'Liegestütz','push ups':'Liegestütze','sit up':'Sit-up','sit-up':'Sit-up','sit ups':'Sit-ups','crunch':'Crunch','plank':'Unterarmstütz','side plank':'Seitstütz','superman':'Superman','burpee':'Burpee','jumping jack':'Hampelmann','mountain climber':'Bergsteiger','high knees':'Kniehebelauf','butt kicks':'Anfersen',
  'bench press':'Bankdrücken','barbell bench press':'Langhantel-Bankdrücken','dumbbell bench press':'Kurzhantel-Bankdrücken','incline bench press':'Schrägbankdrücken','decline bench press':'Negativ-Bankdrücken','chest press':'Brustpresse','shoulder press':'Schulterdrücken','military press':'Military Press','overhead press':'Überkopfdrücken','arnold press':'Arnold Press','chest fly':'Brust-Fliegende','pec deck':'Butterfly-Maschine',
  'biceps curl':'Bizeps-Curl','hammer curl':'Hammer-Curl','preacher curl':'Scott-Curl','concentration curl':'Konzentrations-Curl','triceps extension':'Trizepsstrecken','triceps pushdown':'Trizepsdrücken','triceps dip':'Trizeps-Dip','kickback':'Kickback',
  'lat pulldown':'Latziehen','pull up':'Klimmzug','pull-up':'Klimmzug','chin up':'Untergriff-Klimmzug','chin-up':'Untergriff-Klimmzug','seated row':'Sitzendes Rudern','bent over row':'Vorgebeugtes Rudern','t bar row':'T-Bar-Rudern','t-bar row':'T-Bar-Rudern','upright row':'Aufrechtes Rudern','face pull':'Face Pull','shrug':'Schulterheben',
  'squat':'Kniebeuge','back squat':'Kniebeuge hinten','front squat':'Frontkniebeuge','goblet squat':'Goblet-Kniebeuge','split squat':'Split-Kniebeuge','lunge':'Ausfallschritt','reverse lunge':'Rückwärts-Ausfallschritt','walking lunge':'Gehende Ausfallschritte','deadlift':'Kreuzheben','romanian deadlift':'Rumänisches Kreuzheben','sumo deadlift':'Sumo-Kreuzheben','hip thrust':'Hip Thrust','glute bridge':'Glute Bridge','leg press':'Beinpresse','leg extension':'Beinstrecken','leg curl':'Beinbeugen','calf raise':'Wadenheben','good morning':'Good Morning',
  'lateral raise':'Seitheben','front raise':'Frontheben','rear delt fly':'Reverse Fly','reverse fly':'Reverse Fly','wrist curl':'Handgelenk-Curl','wrist extension':'Handgelenkstrecken',
  'rowing machine':'Rudergerät','stationary bike':'Fahrradergometer','elliptical trainer':'Crosstrainer','treadmill running':'Laufbandlauf','running':'Laufen','walking':'Gehen','cycling':'Radfahren','jump rope':'Seilspringen',
  "child's pose":'Kindhaltung','childs pose':'Kindhaltung','downward dog':'Herabschauender Hund','upward dog':'Heraufschauender Hund','warrior one':'Krieger I','warrior i':'Krieger I','warrior two':'Krieger II','warrior ii':'Krieger II','cobra pose':'Kobra','tree pose':'Baum','pigeon pose':'Taube','cat cow':'Katze-Kuh','cat-cow':'Katze-Kuh','happy baby':'Glückliches Baby','low lunge':'Tiefer Ausfallschritt','sphinx':'Sphinx'
}))
const phrases225=[
 ['smith machine','Multipresse'],['leverage machine','Kraftmaschine'],['assisted machine','Unterstützte Maschine'],['resistance band','Widerstandsband'],['stability ball','Gymnastikball'],['exercise ball','Gymnastikball'],['body weight','Körpergewicht'],['bodyweight','Körpergewicht'],['ez barbell','SZ-Stange'],['ez bar','SZ-Stange'],['straight bar','Gerade Stange'],['close grip','enger Griff'],['wide grip','breiter Griff'],['neutral grip','neutraler Griff'],['reverse grip','umgekehrter Griff'],['underhand grip','Untergriff'],['overhand grip','Obergriff'],['single arm','einarmig'],['one arm','einarmig'],['single leg','einbeinig'],['one leg','einbeinig'],['alternate','abwechselnd'],['alternating','abwechselnd'],['bent over','vorgebeugt'],['incline','schräg'],['decline','negativ'],['seated','sitzend'],['standing','stehend'],['lying','liegend'],['kneeling','kniend'],['reverse','umgekehrt'],['weighted','mit Zusatzgewicht'],['assisted','unterstützt'],
 ['bench press','Bankdrücken'],['chest press','Brustpresse'],['shoulder press','Schulterdrücken'],['overhead press','Überkopfdrücken'],['leg press','Beinpresse'],['lat pulldown','Latziehen'],['pull down','Latziehen'],['pull-up','Klimmzug'],['pull up','Klimmzug'],['chin-up','Untergriff-Klimmzug'],['chin up','Untergriff-Klimmzug'],['push-up','Liegestütz'],['push up','Liegestütz'],['biceps curl','Bizeps-Curl'],['triceps extension','Trizepsstrecken'],['triceps pushdown','Trizepsdrücken'],['lateral raise','Seitheben'],['front raise','Frontheben'],['calf raise','Wadenheben'],['leg extension','Beinstrecken'],['leg curl','Beinbeugen'],['hip thrust','Hip Thrust'],['glute bridge','Glute Bridge'],['romanian deadlift','Rumänisches Kreuzheben'],['deadlift','Kreuzheben'],['chest fly','Brust-Fliegende'],['reverse fly','Reverse Fly'],['rear delt fly','Reverse Fly'],['seated row','Sitzendes Rudern'],['upright row','Aufrechtes Rudern'],['bent over row','Vorgebeugtes Rudern'],['wrist curl','Handgelenk-Curl'],['face pull','Face Pull'],['sit up','Sit-up'],['sit-up','Sit-up'],['side plank','Seitstütz'],['mountain climber','Bergsteiger'],['jumping jack','Hampelmann'],['high knees','Kniehebelauf'],['jump rope','Seilspringen'],['rowing machine','Rudergerät'],['stationary bike','Fahrradergometer'],['elliptical trainer','Crosstrainer'],['treadmill','Laufband'],
 ["child's pose",'Kindhaltung'],['childs pose','Kindhaltung'],['downward dog','Herabschauender Hund'],['upward dog','Heraufschauender Hund'],['warrior pose','Kriegerhaltung'],['tree pose','Baumhaltung'],['pigeon pose','Taubenhaltung'],['cobra pose','Kobra'],['cat cow','Katze-Kuh'],['cat-cow','Katze-Kuh'],['happy baby','Glückliches Baby'],['sun salutation','Sonnengruß'],['low lunge','Tiefer Ausfallschritt']
]
const words225={
 barbell:'Langhantel',dumbbell:'Kurzhantel',kettlebell:'Kettlebell',cable:'Kabelzug',band:'Band',rope:'Seil',machine:'Maschine',smith:'Multipresse',bench:'Bank',lever:'Hebel',weighted:'Zusatzgewicht',bodyweight:'Körpergewicht',
 chest:'Brust',back:'Rücken',shoulder:'Schulter',shoulders:'Schultern',biceps:'Bizeps',triceps:'Trizeps',forearm:'Unterarm',forearms:'Unterarme',wrist:'Handgelenk',lat:'Lat',lats:'Latissimus',leg:'Bein',legs:'Beine',calf:'Wade',calves:'Waden',hamstring:'Beinbeuger',hamstrings:'Beinbeuger',quad:'Quadrizeps',quads:'Quadrizeps',glute:'Gesäß',glutes:'Gesäß',hip:'Hüfte',hips:'Hüften',abs:'Bauch',abdominal:'Bauch',waist:'Bauch',neck:'Nacken',trap:'Trapez',traps:'Trapez',deltoid:'Schulter',delts:'Schultern',ankle:'Sprunggelenk',knee:'Knie',knees:'Knie',arm:'Arm',arms:'Arme',elbow:'Ellenbogen',
 press:'Drücken',curl:'Curl',row:'Rudern',raise:'Heben',extension:'Strecken',flexion:'Beugen',adduction:'Adduktion',abduction:'Abduktion',rotation:'Rotation',fly:'Fliegende',squat:'Kniebeuge',lunge:'Ausfallschritt',deadlift:'Kreuzheben',dip:'Dip',dips:'Dips',shrug:'Schulterheben',crunch:'Crunch',plank:'Unterarmstütz',bridge:'Brücke',kickback:'Kickback',stretch:'Dehnung',jump:'Sprung',running:'Laufen',run:'Laufen',walking:'Gehen',walk:'Gehen',cycling:'Radfahren',cycle:'Radfahren',pedal:'Pedalieren',
 seated:'sitzend',standing:'stehend',lying:'liegend',kneeling:'kniend',incline:'schräg',decline:'negativ',reverse:'umgekehrt',assisted:'unterstützt',alternating:'abwechselnd',alternate:'abwechselnd',single:'einseitig',one:'ein',two:'zwei',arm:'Arm',leg:'Bein',wide:'breit',close:'eng',neutral:'neutral',grip:'Griff',overhead:'über Kopf',behind:'hinter',front:'vorne',rear:'hinten',side:'seitlich',lateral:'seitlich',horizontal:'horizontal',vertical:'vertikal',inner:'innen',outer:'außen',upper:'oberer',lower:'unterer',middle:'mittlerer',straight:'gerade',cross:'überkreuz',around:'um',with:'mit',without:'ohne',on:'auf',to:'zu',from:'von',and:'und',using:'mit',supported:'gestützt',dynamic:'dynamisch',static:'statisch'
}
const german225=value=>{
 const source=String(value||'').trim();if(!source)return source
 const low=source.toLowerCase().replace(/\s+/g,' ')
 if(exact225.has(low))return exact225.get(low)
 let out=source
 for(const [en,de] of phrases225){out=out.replace(new RegExp(`\\b${en.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'gi'),de)}
 out=out.split(/(\s+|[-–—/(),])/).map(part=>{const key=part.toLowerCase().replace(/[.:;]/g,'');return words225[key]||part}).join('')
 out=out.replace(/\s+/g,' ').replace(/\s+([,;)])/g,'$1').replace(/([(])\s+/g,'$1').trim()
 return out.charAt(0).toUpperCase()+out.slice(1)
}
const selectors225=['.exercise-card-v2 strong','.exercise-detail-copy h2','.swap-list strong','.swap-head h2','.active-training .exercise-stage h1','.training-overlay h1','.single-training-v220 h1','.single-head-v220 strong']
const translateVisible225=()=>{for(const sel of selectors225)document.querySelectorAll(sel).forEach(el=>{if(el.dataset.ft225)return;const before=el.textContent?.trim();if(!before)return;const after=german225(before);if(after&&after!==before)el.textContent=after;el.dataset.ft225='1'})}
const ensureGermanDetails225=()=>{
 const detail=document.querySelector('.exercise-detail-copy');if(!detail)return
 const items=[...detail.querySelectorAll('ol li')];if(!items.length)return
 // Current App.jsx already generates its exercise instructions in German. Mark verified German content
 // and replace only obvious leftover English boilerplate if another source injects it later.
 const replacements=[['Take a stable starting position','Nimm eine stabile Ausgangsposition ein'],['Perform the movement slowly and controlled','Führe die Bewegung langsam und kontrolliert aus'],['Avoid unnecessary momentum','Vermeide unnötigen Schwung'],['Breathe calmly and evenly','Atme ruhig und gleichmäßig weiter']]
 items.forEach(li=>{let t=li.textContent||'';for(const [en,de] of replacements)t=t.replace(en,de);li.textContent=t;li.dataset.ft225German='1'})
}
const updateVersion225=()=>document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0&&el.textContent?.includes('V2.0.24'))el.textContent=el.textContent.replaceAll('V2.0.24',FT225_VERSION)})
const enhance225=()=>{translateVisible225();ensureGermanDetails225();updateVersion225()}
if(typeof document!=='undefined'){const obs225=new MutationObserver(enhance225);const start225=()=>{enhance225();obs225.observe(document.body,{childList:true,subtree:true})};document.body?start225():document.addEventListener('DOMContentLoaded',start225,{once:true})}
