// FitTogether V2.0.73: exercise availability uses one central equipment profile.
export const FITTOGETHER_VERSION='V2.0.73'
const read238=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const write238=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const defaults238=()=>({bodyweight:true,dumbbell:read238('ft-dumbbell-weights',[]).length>0,barbell:read238('ft-barbell-weights',[]).length>0,band:false,machine:false,treadmill:false,bike:false,rower:false})
const initialEquipment238=()=>{const central=read238('ft-equipment-profile',null)?.equipment;if(central)return{...defaults238(),...central};const old=read238('ft-available-equipment-v238',null);return old?{...defaults238(),...old}:defaults238()}
const saveEquipment238=e=>{const p=read238('ft-equipment-profile',{});write238('ft-equipment-profile',{...p,equipment:e});write238('ft-available-equipment-v238',e);window.FitTogetherCloud?.upload?.()}
const matchEquipment238=(text,e)=>{const t=String(text||'').toLowerCase();if(/laufband|treadmill/.test(t))return e.treadmill;if(/fahrrad|ergometer|bike|bicycle|cycling|cycle/.test(t))return e.bike;if(/rudergerät|rowing machine|rower/.test(t))return e.rower;if(/kurzhantel|dumbbell/.test(t))return e.dumbbell;if(/langhantel|sz-stange|barbell/.test(t))return e.barbell;if(/körpergewicht|body.?weight/.test(t))return e.bodyweight;if(/widerstandsband|band/.test(t))return e.band;if(/kabelzug|maschine|multipresse|machine|cable/.test(t))return e.machine;if(/cardio|yoga|dehnen/.test(t))return true;return false}
let onlyMine238=read238('ft-exercise-only-mine-v238',false),equipment238=initialEquipment238()
const applyExerciseFilter238=()=>{equipment238=initialEquipment238();const grid=document.querySelector('.exercise-grid');if(!grid)return;const cards=[...grid.querySelectorAll('.exercise-card-v2')];let visible=0;cards.forEach(card=>{const show=!onlyMine238||matchEquipment238(card.textContent,equipment238);card.hidden=!show;if(show)visible++});const count=document.querySelector('.exercise-count-v238');if(count)count.textContent=`${visible} sichtbar${cards.length===80?' · aktuell 80 geladen':''}`}
const renderEquipmentChips238=box=>{const chips=box.querySelector('.equipment-chips-v238');if(!chips)return;equipment238=initialEquipment238();const defs=[['bodyweight','Körpergewicht'],['dumbbell','Kurzhantel'],['barbell','Langhantel'],['band','Widerstandsband'],['machine','Kabel/Maschine'],['treadmill','Laufband'],['bike','Fahrrad/Ergometer'],['rower','Rudergerät']];chips.innerHTML=defs.map(([k,l])=>`<button type="button" data-equipment="${k}" class="${equipment238[k]?'active':''}">${l}</button>`).join('');chips.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{const k=btn.dataset.equipment;equipment238={...equipment238,[k]:!equipment238[k]};saveEquipment238(equipment238);renderEquipmentChips238(box);applyExerciseFilter238()})}
const enhanceExercises238=()=>{const grid=document.querySelector('.exercise-grid'),filterRow=document.querySelector('.filter-row');if(!grid||!filterRow)return;let box=document.querySelector('.exercise-advanced-v238');if(!box){box=document.createElement('section');box.className='exercise-advanced-v238';box.innerHTML=`<div class="exercise-availability-head-v238"><div><strong>Meine Ausstattung</strong><small class="exercise-count-v238"></small></div><label class="only-mine-v238"><input type="checkbox"><span>Nur verfügbare Übungen</span></label></div><div class="equipment-chips-v238"></div><p>Diese Auswahl ist mit Einstellungen → Meine Ausstattung synchronisiert.</p>`;filterRow.insertAdjacentElement('afterend',box);const cb=box.querySelector('.only-mine-v238 input');cb.checked=onlyMine238;cb.onchange=()=>{onlyMine238=cb.checked;write238('ft-exercise-only-mine-v238',onlyMine238);applyExerciseFilter238()}}renderEquipmentChips238(box);applyExerciseFilter238()}
let queued238=false
const enhance238=()=>{queued238=false;enhanceExercises238()}
const schedule238=()=>{if(document.querySelector('.rest-overlay')||queued238)return;queued238=true;requestAnimationFrame(enhance238)}
if(typeof document!=='undefined'){const observer=new MutationObserver(m=>{if(document.querySelector('.rest-overlay'))return;if(m.some(x=>[...x.addedNodes].some(n=>n.nodeType===1&&!n.classList?.contains('exercise-advanced-v238'))))schedule238()});const start=()=>{enhance238();observer.observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
