// FitTogether V2.0.75: per-set planning + individual bodyweight extra load with RIR progression.
const R275=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const W275=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const N275=v=>Math.max(0,Number(String(v??'').replace(',','.'))||0)
const E275=item=>{const s=`${item?.equipment||''} ${item?.kind||''} ${item?.name||''}`.toLowerCase();if(/kurzhantel|dumbbell/.test(s))return'dumbbell';if(/langhantel|barbell|sz-stange/.test(s))return'barbell';if(/körpergewicht|body.?weight|klimmzug|pull.?up|liegestütz|push.?up|dip/.test(s))return'bodyweight';if(/band/.test(s))return'band';if(/kabel|maschine|cable|machine/.test(s))return'machine';return'bodyweight'}
const choices275=item=>{const e=E275(item),k=e==='dumbbell'?'ft-dumbbell-weights':e==='barbell'?'ft-barbell-weights':null;if(!k)return[];return[...new Set(R275(k,[]).map(N275).filter(Boolean))].sort((a,b)=>a-b)}
const esc275=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const next275=(a,v,d)=>{if(!a.length)return v;const i=a.indexOf(v);if(i>=0)return a[Math.max(0,Math.min(a.length-1,i+d))];return d>0?(a.find(x=>x>v)??a.at(-1)):([...a].reverse().find(x=>x<v)??a[0])}
const start275=items=>{if(!items?.length)return;document.querySelector('.free-workout-v247,.free-workout-v275')?.remove();let ix=0,si=0;const logs=[],loads=R275('ft-exercise-loads-v275',{});const ov=document.createElement('div');ov.className='free-workout-v247 free-workout-v275';let hint='';
 const state=item=>{const count=Math.max(1,Number(item.sets)||3),old=loads[item.name]||{},arr=Array.isArray(old.sets)?old.sets:[];return Array.from({length:count},(_,i)=>({...{reps:Number(old.reps)||10,weight:N275(old.weight),extraWeight:N275(old.extraWeight),useExtra:!!old.useExtra,rirTarget:Number(old.rirTarget??2)},...(arr[i]||{})}))};let sets=state(items[0]);
 const save=()=>{const item=items[ix];loads[item.name]={sets,reps:sets[0]?.reps||10,weight:sets[0]?.weight||0,extraWeight:sets[0]?.extraWeight||0,useExtra:!!sets[0]?.useExtra};W275('ft-exercise-loads-v275',loads)};
 const finish=()=>{const old=R275('ft-completed-workouts',[]);old.push({date:Date.now(),exercises:items.length,name:'Freies Training',source:'Freies Training',kind:'strength',sets:logs,version:'V2.0.75'});W275('ft-completed-workouts',old.slice(-100));window.FitTogetherCloud?.upload?.();ov.innerHTML='<div class="free-finished-v247"><span>✓</span><h1>Training gespeichert</h1><p>Alle Sätze abgeschlossen.</p><button>Fertig</button></div>';ov.querySelector('button').onclick=()=>ov.remove()};
 const advance=()=>{save();if(si<sets.length-1){si++;render();return}if(ix<items.length-1){ix++;si=0;sets=state(items[ix]);hint='';render();return}finish()};
 const rir=(r,item)=>{const s=sets[si],e=E275(item),cw=choices275(item),before={...s};if(r<=1){if(e==='bodyweight'&&s.useExtra)s.extraWeight=Math.max(0,s.extraWeight-1);else if(cw.length)s.weight=next275(cw,N275(s.weight),-1);else s.reps=Math.max(1,s.reps-1)}else if(r===3)s.reps+=1;else if(r>=4){if(e==='bodyweight'&&s.useExtra)s.extraWeight=N275(s.extraWeight)+1;else if(cw.length)s.weight=next275(cw,N275(s.weight),1);else s.reps+=2}hint=r===2?'Passt gut – Werte bleiben gleich.':'RIR wurde für die nächste Empfehlung berücksichtigt.';logs.push({exercise:item.name,exerciseIndex:ix,set:si+1,reps:before.reps,weight:e==='bodyweight'?0:N275(before.weight),extraWeight:e==='bodyweight'&&before.useExtra?N275(before.extraWeight):0,loadType:e==='bodyweight'?(before.useExtra?'bodyweight+extra':'bodyweight'):e,rir:r>=4?'4+':r,rirTarget:before.rirTarget});if(si+1<sets.length)sets[si+1]={...sets[si+1],reps:s.reps,weight:s.weight,extraWeight:s.extraWeight,useExtra:s.useExtra};advance()};
 const ask=item=>{const c=ov.querySelector('.free-card-v247');c.innerHTML=`<small>SATZ ${si+1} VON ${sets.length}</small><h1>${esc275(item.name)}</h1><div class="rir-v247"><span>RIR · ZIEL ${sets[si].rirTarget}</span><h2>Wie viele Wiederholungen wären noch gegangen?</h2><div>${[0,1,2,3,4].map(x=>`<button data-r="${x}">${x===4?'4+':x}</button>`).join('')}</div></div>`;c.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>rir(Number(b.dataset.r),item))};
 const render=()=>{const item=items[ix],s=sets[si],e=E275(item),cw=choices275(item);let load='';if(e==='bodyweight')load=`<div class="bw-mode-v275"><button data-bw class="${!s.useExtra?'active':''}">Nur Körpergewicht</button><button data-extra class="${s.useExtra?'active':''}">Zusatzgewicht</button></div>${s.useExtra?`<label><input data-extra-weight inputmode="decimal" value="${s.extraWeight||''}" placeholder="0"><span>kg Zusatzgewicht · individuell</span></label>`:''}`;else if(cw.length)load=`<label><select data-weight>${cw.map(v=>`<option value="${v}" ${v===N275(s.weight)?'selected':''}>${String(v).replace('.',',')} kg</option>`).join('')}</select><span>${e==='dumbbell'?'pro Arm':'gesamt'}</span></label>`;else load='<div class="bodyweight-v247"><strong>Keine Gewichtsangabe</strong><span>Wiederholungen werden gespeichert</span></div>';ov.innerHTML=`<div class="free-head-v247"><button data-close>×</button><span>ÜBUNG ${ix+1} / ${items.length}</span></div><div class="free-card-v247"><small>SATZ ${si+1} VON ${sets.length}</small><h1>${esc275(item.name)}</h1>${hint?`<p class="adjust-v247">${esc275(hint)}</p>`:''}<div class="set-plan-v275"><span>Satz ${si+1}</span><label>RIR-Ziel <input data-target inputmode="numeric" value="${s.rirTarget}"></label></div><div class="inputs-v247 inputs-v275">${load}<label><input data-reps inputmode="numeric" value="${s.reps}"><span>Wdh.</span></label></div><button type="button" data-next>Satz ${si+1} abschließen</button></div>`;ov.querySelector('[data-close]').onclick=()=>ov.remove();ov.querySelector('[data-bw]')?.addEventListener('click',()=>{s.useExtra=false;render()});ov.querySelector('[data-extra]')?.addEventListener('click',()=>{s.useExtra=true;render()});ov.querySelector('[data-next]').onclick=()=>{const w=ov.querySelector('[data-weight]');if(w)s.weight=N275(w.value);const ew=ov.querySelector('[data-extra-weight]');if(ew)s.extraWeight=N275(ew.value);s.reps=Math.max(1,Number(ov.querySelector('[data-reps]')?.value)||s.reps);s.rirTarget=Math.max(0,Math.min(4,Number(ov.querySelector('[data-target]')?.value)||2));save();ask(item)}};
 document.body.appendChild(ov);render()};
window.FitTogetherStartFreeWorkout247=start275;window.FitTogetherStartFreeWorkout275=start275;
