// FitTogether V2.0.76: Smart Trainer learns from completed set/RIR history and available loads.
const r276=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const w276=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const n276=v=>Math.max(0,Number(String(v??'').replace(',','.'))||0)
const norm276=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const eq276=x=>{const s=`${x?.equipment||''} ${x?.name||''} ${x?.query||''}`.toLowerCase();if(/kurzhantel|dumbbell/.test(s))return'dumbbell';if(/langhantel|barbell|ez bar/.test(s))return'barbell';if(/körpergewicht|body.?weight|klimm|pull.?up|liegestütz|push.?up|dip/.test(s))return'bodyweight';return'other'}
const weights276=e=>{const k=e==='dumbbell'?'ft-dumbbell-weights':e==='barbell'?'ft-barbell-weights':null;if(!k)return[];return[...new Set(r276(k,[]).map(n276).filter(Boolean))].sort((a,b)=>a-b)}
const nearest276=(a,v)=>!a.length?v:a.reduce((p,c)=>Math.abs(c-v)<Math.abs(p-v)?c:p,a[0])
const history276=name=>{const key=norm276(name),all=r276('ft-completed-workouts',[]);const out=[];for(let wi=all.length-1;wi>=0&&out.length<12;wi--){const sets=Array.isArray(all[wi]?.sets)?all[wi].sets:[];for(let si=sets.length-1;si>=0&&out.length<12;si--){const s=sets[si];if(norm276(s?.exercise)===key&&s?.rir!==undefined)out.unshift(s)}}return out}
const recommendation276=x=>{const hist=history276(x.name);if(!hist.length)return null;const last=hist.at(-1),e=eq276(x),rir=last.rir==='4+'?4:Number(last.rir),reps=Math.max(1,Number(last.reps)||10);let weight=n276(last.weight),extra=n276(last.extraWeight),useExtra=last.loadType==='bodyweight+extra'||extra>0;let nextReps=reps,reason='RIR 2: Belastung passt';if(rir<=1){reason='RIR 0–1: etwas leichter';if(e==='bodyweight'&&useExtra)extra=Math.max(0,extra-1);else{const a=weights276(e);if(a.length)weight=a[Math.max(0,a.indexOf(nearest276(a,weight))-1)];else nextReps=Math.max(1,reps-1)}}else if(rir===3){nextReps=reps+1;reason='RIR 3: +1 Wiederholung'}else if(rir>=4){reason='RIR 4+: Belastung steigern';if(e==='bodyweight'&&useExtra)extra+=1;else{const a=weights276(e);if(a.length)weight=a[Math.min(a.length-1,a.indexOf(nearest276(a,weight))+1)];else nextReps=reps+2}}return{reps:nextReps,weight,extraWeight:extra,useExtra,rirTarget:2,reason,lastRir:last.rir}}
const apply276=()=>{const plans=r276('ft-plans',[]);if(!plans.length)return;let changed=false;for(const p of plans){if(!String(p?.name||'').startsWith('Smart Plan'))continue;for(const s of p.sessions||[]){if(typeof s==='string')continue;s.exercises=(s.exercises||[]).map(x=>{if(x?.warmup)return x;const rec=recommendation276(x);if(!rec)return x;changed=true;const count=Math.max(1,Number(x.sets)||3);return{...x,smartRecommendation:rec,plannedSets:Array.from({length:count},()=>({...rec}))}})}}if(changed){w276('ft-plans',plans);window.FitTogetherCloud?.upload?.()}return changed}
const seedLoads276=()=>{const plans=r276('ft-plans',[]),loads=r276('ft-exercise-loads-v275',{});let changed=false;for(const p of plans){if(!String(p?.name||'').startsWith('Smart Plan'))continue;for(const s of p.sessions||[]){if(typeof s==='string')continue;for(const x of s.exercises||[]){const rec=x.smartRecommendation||recommendation276(x);if(!rec)continue;const count=Math.max(1,Number(x.sets)||3);loads[x.name]={sets:Array.from({length:count},()=>({...rec})),reps:rec.reps,weight:rec.weight,extraWeight:rec.extraWeight,useExtra:rec.useExtra};changed=true}}}if(changed)w276('ft-exercise-loads-v275',loads)}
const enhance276=()=>{const page=[...document.querySelectorAll('.page')].find(p=>p.querySelector('.page-head h1')?.textContent?.trim()==='Smarter Trainer');if(!page)return;const box=page.querySelector('.coach-suggestion');if(!box||box.querySelector('.smart-learning-v276'))return;const d=document.createElement('div');d.className='smart-learning-v276';const completed=r276('ft-completed-workouts',[]).filter(w=>Array.isArray(w.sets)&&w.sets.some(s=>s.rir!==undefined)).length;d.innerHTML=`<strong>SMART PROGRESSION</strong><span>${completed?`Lernt aus ${completed} Training${completed===1?'':'s'} mit RIR-Daten.`:'Noch keine RIR-Historie – startet mit deinen Planwerten.'}</span><small>RIR, Wiederholungen, Gewichte und Zusatzgewicht werden für die nächste Einheit berücksichtigt.</small>`;box.prepend(d)}
const click276=e=>{const b=e.target.closest('button');if(!b)return;if(b.textContent?.includes('Plan speichern'))setTimeout(()=>{apply276();seedLoads276()},180);if(b.textContent?.match(/Training starten|Starten|Los geht/))setTimeout(seedLoads276,0)}
let q276=false;const sched276=()=>{if(document.querySelector('.active-training,.rest-overlay')||q276)return;q276=true;requestAnimationFrame(()=>{q276=false;enhance276()})}
if(typeof document!=='undefined'){document.addEventListener('click',click276,true);const o=new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length))sched276()});const start=()=>{apply276();enhance276();o.observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
