// FitTogether V2.0.114: exercise progression history + next recommendation with targeted observer.
const r280=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const esc280=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))
const norm280=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const fmt280=n=>String(Number(n)||0).replace('.',',')
const rows280=()=>{const out=new Map();for(const w of r280('ft-completed-workouts',[])){if(!Array.isArray(w?.sets))continue;for(const s of w.sets){if(!s?.exercise||s?.rir===undefined)continue;const key=norm280(s.exercise);if(!out.has(key))out.set(key,{name:s.exercise,sessions:new Map()});const d=Number(w.date)||Date.now(),id=String(d),e=out.get(key);if(!e.sessions.has(id))e.sessions.set(id,{date:d,day:new Date(d).toLocaleDateString('de-DE'),sets:[]});e.sessions.get(id).sets.push(s)}}return[...out.values()].map(e=>({...e,sessions:[...e.sessions.values()].sort((a,b)=>a.date-b.date)})).sort((a,b)=>(b.sessions.at(-1)?.date||0)-(a.sessions.at(-1)?.date||0))}
const loadText280=s=>{const extra=Number(s.actualExtraWeight??s.extraWeight)||0,weight=Number(s.actualWeight??s.weight)||0;if(extra>0)return`+${fmt280(extra)} kg`;if(weight>0)return`${fmt280(weight)} kg`;return'Körpergewicht'}
const recommendation280=e=>{const last=e.sessions.at(-1)?.sets||[];if(!last.length)return'';const saved=r280('ft-exercise-loads-v275',{})[e.name]||{},planned=Array.isArray(saved.sets)?saved.sets:[],count=Math.max(last.length,planned.length,1);return Array.from({length:count},(_,i)=>{const p=planned[i]||{},l=last[Math.min(i,last.length-1)]||{},reps=Number(p.reps)||Number(l.reps)||10,extra=Number(p.extraWeight)||0,weight=Number(p.weight)||0,load=extra>0?` · +${fmt280(extra)} kg`:weight>0?` · ${fmt280(weight)} kg`:'';return`S${i+1}: ${reps} Wdh.${load} · RIR ${Number(p.rirTarget??2)}`}).join(' · ')}
const sessionText280=x=>x.sets.map((s,i)=>`S${i+1} ${Number(s.actualReps??s.reps)||0}× ${loadText280(s)} · RIR ${s.rir??'–'}`).join('  |  ')
const render280=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const page=[...document.querySelectorAll('.page')].find(p=>/Statistik/.test(p.querySelector('.page-head h1')?.textContent||''));if(!page)return;let box=page.querySelector('.exercise-progress-v280');if(!box){box=document.createElement('section');box.className='exercise-progress-v280';const history=page.querySelector('.training-history-v234');history?.insertAdjacentElement('afterend',box)||page.appendChild(box)}const data=rows280(),sig=JSON.stringify(data)+JSON.stringify(r280('ft-exercise-loads-v275',{}));if(box.dataset.sig===sig)return;box.dataset.sig=sig;box.innerHTML=`<div class="section-title"><span>Übungsfortschritt</span></div>${!data.length?'<p class="progress-empty-v280">Nach den ersten Trainings mit RIR erscheinen hier deine Übungsverläufe.</p>':`<div class="progress-list-v280">${data.map((e,i)=>`<article class="progress-card-v280"><button type="button" data-p280="${i}"><span><strong>${esc280(e.name)}</strong><small>${e.sessions.length} ${e.sessions.length===1?'Einheit':'Einheiten'} mit RIR</small></span><b>Verlauf</b></button><div class="progress-detail-v280" data-d280="${i}" hidden><div class="next-rec-v280"><small>NÄCHSTE EMPFEHLUNG</small><strong>${esc280(recommendation280(e))}</strong></div>${e.sessions.slice(-4).reverse().map(s=>`<div class="progress-session-v280"><span>${esc280(s.day)}</span><small>${esc280(sessionText280(s))}</small></div>`).join('')}</div></article>`).join('')}</div>`}`;box.querySelectorAll('[data-p280]').forEach(b=>b.onclick=()=>{const d=box.querySelector(`[data-d280="${b.dataset.p280}"]`);if(d)d.hidden=!d.hidden})}
let q280=false;const schedule280=()=>{if(q280||document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;q280=true;requestAnimationFrame(()=>{q280=false;render280()})}
const relevant280=n=>n?.nodeType===1&&(n.matches?.('.page,.training-history-v234')||n.querySelector?.('.page,.training-history-v234'))
if(typeof document!=='undefined'){const o=new MutationObserver(m=>{if(m.some(x=>[...x.addedNodes].some(relevant280)))schedule280()});const start=()=>{render280();o.observe(document.body,{childList:true,subtree:true});window.addEventListener('ft-stats-refresh',schedule280)};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
