// FitTogether V2.0.80: exercise progression history from completed set data.
const r280=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const esc280=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const n280=v=>Number(String(v??'').replace(',','.'))||0
const rirNum280=v=>v==='4+'?4:Number(v)||0
const allSets280=()=>{const out=[];for(const w of r280('ft-completed-workouts',[])){if(!Array.isArray(w?.sets))continue;for(const s of w.sets){if(!s?.exercise)continue;out.push({...s,date:w.date||Date.now(),workoutName:w.name||w.source||'Training'})}}return out}
const grouped280=()=>{const map=new Map();for(const s of allSets280()){const key=String(s.exercise).trim();if(!map.has(key))map.set(key,[]);map.get(key).push(s)}return [...map.entries()].map(([name,sets])=>({name,sets:sets.sort((a,b)=>a.date-b.date)})).sort((a,b)=>(b.sets.at(-1)?.date||0)-(a.sets.at(-1)?.date||0))}
const sessions280=sets=>{const m=new Map();for(const s of sets){const day=new Date(s.date).toISOString().slice(0,10);if(!m.has(day))m.set(day,[]);m.get(day).push(s)}return [...m.entries()].map(([day,x])=>({day,sets:x,date:Math.max(...x.map(v=>v.date||0))})).sort((a,b)=>b.date-a.date)}
const loadLabel280=s=>{const extra=n280(s.actualExtraWeight??s.extraWeight),weight=n280(s.actualWeight??s.weight);if(extra>0)return `+${String(extra).replace('.',',')} kg`;if(weight>0)return `${String(weight).replace('.',',')} kg`;return 'Körpergewicht'}
const summary280=session=>{const sets=session?.sets||[];if(!sets.length)return null;const reps=sets.map(s=>n280(s.actualReps??s.reps)).filter(Boolean),rirs=sets.map(s=>rirNum280(s.rir)).filter(v=>v>=0),loads=sets.map(s=>n280(s.actualExtraWeight??s.extraWeight)||n280(s.actualWeight??s.weight));return{avgReps:reps.length?reps.reduce((a,b)=>a+b,0)/reps.length:0,avgRir:rirs.length?rirs.reduce((a,b)=>a+b,0)/rirs.length:0,maxLoad:loads.length?Math.max(...loads):0,loadType:sets.at(-1)?.loadType||'',sets:sets.length}}
const trend280=list=>{if(list.length<2)return{symbol:'→',text:'Erste Vergleichsdaten'};const a=summary280(list[0]),b=summary280(list[1]);if(!a||!b)return{symbol:'→',text:'Noch kein Trend'};const loadDiff=a.maxLoad-b.maxLoad,repDiff=a.avgReps-b.avgReps;if(loadDiff>0.01)return{symbol:'↑',text:`+${String(Number(loadDiff.toFixed(2))).replace('.',',')} kg`};if(repDiff>0.4)return{symbol:'↑',text:`+${Number(repDiff.toFixed(1)).toLocaleString('de-DE')} Wdh. Ø`};if(loadDiff<-0.01||repDiff<-0.4)return{symbol:'↓',text:'Letzte Einheit niedriger'};return{symbol:'→',text:'Belastung stabil'}}
const open280=item=>{document.querySelector('.exercise-history-modal-v280')?.remove();const list=sessions280(item.sets).slice(0,10),latest=summary280(list[0]),ov=document.createElement('div');ov.className='exercise-history-modal-v280';ov.innerHTML=`<div class="exercise-history-sheet-v280"><div class="exercise-history-head-v280"><div><small>ÜBUNGSVERLAUF</small><h2>${esc280(item.name)}</h2></div><button type="button" data-close>×</button></div>${latest?`<div class="exercise-history-latest-v280"><div><span>Letzte Einheit</span><strong>${latest.avgReps.toFixed(1).replace('.',',')} Wdh. Ø</strong></div><div><span>RIR Ø</span><strong>${latest.avgRir.toFixed(1).replace('.',',')}</strong></div><div><span>Sätze</span><strong>${latest.sets}</strong></div></div>`:''}<div class="exercise-history-list-v280">${list.map(sess=>{const s=summary280(sess);const last=sess.sets.at(-1);return `<div><span><strong>${new Date(sess.date).toLocaleDateString('de-DE')}</strong><small>${s.sets} Sätze · RIR ${s.avgRir.toFixed(1).replace('.',',')} Ø</small></span><b>${s.avgReps.toFixed(1).replace('.',',')} Wdh. Ø</b><em>${loadLabel280(last)}</em></div>`}).join('')}</div></div>`;document.body.appendChild(ov);ov.querySelector('[data-close]').onclick=()=>ov.remove();ov.addEventListener('click',e=>{if(e.target===ov)ov.remove()})}
const render280=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const page=[...document.querySelectorAll('.page')].find(p=>p.querySelector('.page-head h1')?.textContent?.trim()==='Deine Statistik');if(!page)return;page.querySelector('.exercise-progress-v280')?.remove();const data=grouped280();if(!data.length)return;const section=document.createElement('section');section.className='exercise-progress-v280';section.innerHTML=`<div class="section-title"><span>Übungsfortschritt</span></div><p class="exercise-progress-intro-v280">Gewicht, Wiederholungen und RIR aus deinen absolvierten Sätzen.</p><div class="exercise-progress-grid-v280">${data.slice(0,10).map((item,i)=>{const ss=sessions280(item.sets),last=ss[0],sum=summary280(last),tr=trend280(ss),lastSet=last?.sets?.at(-1);return `<button type="button" data-ex="${i}"><span><strong>${esc280(item.name)}</strong><small>${last?new Date(last.date).toLocaleDateString('de-DE'):'–'} · ${sum?.sets||0} Sätze</small></span><div><b>${sum?sum.avgReps.toFixed(1).replace('.',','):'–'} <small>Wdh. Ø</small></b><em>${lastSet?loadLabel280(lastSet):'–'}</em><i class="${tr.symbol==='↑'?'up':tr.symbol==='↓'?'down':'flat'}">${tr.symbol} ${esc280(tr.text)}</i></div></button>`}).join('')}</div>`;const anchor=page.querySelector('.weight-history')||page.querySelector('.primary-action');anchor?.insertAdjacentElement('beforebegin',section);section.querySelectorAll('[data-ex]').forEach(b=>b.onclick=()=>open280(data[Number(b.dataset.ex)]))}
let q280=false;const schedule280=()=>{if(q280||document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;q280=true;requestAnimationFrame(()=>{q280=false;render280()})}
if(typeof document!=='undefined'){const o=new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))schedule280()});const start=()=>{render280();o.observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
