// FitTogether V2.0.81: weekly muscle feedback + confirmed Smart Plan adaptation.
const r281=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const w281=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const esc281=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm281=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const groups281=['Brust','Rücken','Beine','Schultern','Bizeps','Trizeps','Bauch','Gesäß','Waden']
const muscle281=(name,raw='')=>{const s=`${name||''} ${raw||''}`.toLowerCase();if(/chest|pector|brust|bench|fly|push.?up|liegestütz/.test(s))return'Brust';if(/lat|back|rücken|row|rudern|pull.?up|klimm|deadlift|kreuzheben/.test(s))return'Rücken';if(/quad|hamstring|thigh|leg|beine|squat|kniebeuge|lunge|ausfallschritt/.test(s))return'Beine';if(/delt|shoulder|schulter|overhead|seitheben/.test(s))return'Schultern';if(/biceps|bizeps|curl/.test(s))return'Bizeps';if(/triceps|trizeps|extension|pushdown|dip/.test(s))return'Trizeps';if(/abs|abdom|core|bauch|crunch|plank/.test(s))return'Bauch';if(/glute|gesäß|hip thrust/.test(s))return'Gesäß';if(/calf|wade/.test(s))return'Waden';return''}
const planMuscles281=()=>{const map=new Map();for(const p of r281('ft-plans',[])){for(const s of p?.sessions||[]){if(typeof s==='string')continue;for(const x of s?.exercises||[]){const key=norm281(x?.name);if(key)map.set(key,muscle281(x?.name,`${x?.muscle||''} ${x?.query||''}`))}}}return map}
const week281=()=>{const now=Date.now(),start=now-7*86400000,map=planMuscles281(),score=Object.fromEntries(groups281.map(g=>[g,{sets:0,load:0}]));for(const w of r281('ft-completed-workouts',[])){if((Number(w?.date)||0)<start||!Array.isArray(w?.sets))continue;for(const s of w.sets){const g=map.get(norm281(s?.exercise))||muscle281(s?.exercise);if(!g||!score[g])continue;const rir=s?.rir==='4+'?4:Number(s?.rir),factor=rir<=1?1.15:rir>=4?.85:1;score[g].sets++;score[g].load+=factor}}return score}
const auto281=x=>x.sets===0?'zu wenig':x.load<5?'zu wenig':x.load>13?'zu viel':'passt'
const proposal281=(score,answers)=>groups281.map(g=>({group:g,assessment:answers[g]||auto281(score[g]),sets:score[g].sets})).filter(x=>x.assessment!=='passt')
const apply281=(proposal)=>{const plans=r281('ft-plans',[]);let changed=0;for(const p of plans){if(!String(p?.name||'').startsWith('Smart Plan'))continue;for(const s of p.sessions||[]){if(typeof s==='string')continue;for(const x of s.exercises||[]){const g=muscle281(x?.name,`${x?.muscle||''} ${x?.query||''}`),hit=proposal.find(p=>p.group===g);if(!hit)continue;const old=Math.max(1,Number(x.sets)||3),next=hit.assessment==='zu wenig'?Math.min(5,old+1):Math.max(1,old-1);if(next!==old){x.sets=next;if(Array.isArray(x.plannedSets)){const seed=x.plannedSets.at(-1)||x.smartRecommendation||{};while(x.plannedSets.length<next)x.plannedSets.push({...seed});x.plannedSets=x.plannedSets.slice(0,next)}changed++}}}}if(changed){w281('ft-plans',plans);w281('ft-weekly-muscle-last-applied',{date:Date.now(),proposal});window.FitTogetherCloud?.upload?.()}return changed}
const open281=()=>{document.querySelector('.weekly-muscle-modal-v281')?.remove();const score=week281(),saved=r281('ft-weekly-muscle-feedback',{}),answers={...saved};const ov=document.createElement('div');ov.className='weekly-muscle-modal-v281';ov.innerHTML=`<div class="weekly-muscle-sheet-v281"><div class="weekly-muscle-head-v281"><div><small>WOCHENFEEDBACK</small><h2>Wie war die Muskelbelastung?</h2><p>FitTogether kombiniert deine Antwort mit Sätzen und RIR der letzten 7 Tage.</p></div><button data-close>×</button></div><div class="weekly-muscle-list-v281">${groups281.map(g=>{const a=answers[g]||auto281(score[g]);return`<div data-group="${g}"><span><strong>${g}</strong><small>${score[g].sets} Sätze · Vorschlag: ${auto281(score[g])}</small></span><div>${[['zu wenig','Zu wenig'],['passt','Passt'],['zu viel','Zu viel']].map(([v,t])=>`<button type="button" data-v="${v}" class="${a===v?'active':''}">${t}</button>`).join('')}</div></div>`}).join('')}</div><div class="weekly-muscle-actions-v281"><button data-preview>Änderungen prüfen</button></div><div class="weekly-proposal-v281" hidden></div></div>`;document.body.appendChild(ov);ov.querySelector('[data-close]').onclick=()=>ov.remove();ov.querySelectorAll('[data-group]').forEach(row=>row.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{answers[row.dataset.group]=b.dataset.v;row.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('active',x===b));w281('ft-weekly-muscle-feedback',answers)}));ov.querySelector('[data-preview]').onclick=()=>{const p=proposal281(score,answers),box=ov.querySelector('.weekly-proposal-v281');box.hidden=false;box.innerHTML=`<small>VORSCHLAG FÜR DIE NÄCHSTE WOCHE</small>${p.length?p.map(x=>`<div><strong>${x.group}</strong><span>${x.assessment==='zu wenig'?'+1 Satz je betroffener Smart-Plan-Übung':'−1 Satz je betroffener Smart-Plan-Übung'}</span></div>`).join(''):'<p>Aktuell keine Anpassung nötig.</p>'}<button type="button" data-apply ${p.length?'':'disabled'}>Vorschlag übernehmen</button>`;box.querySelector('[data-apply]')?.addEventListener('click',()=>{const n=apply281(p);box.innerHTML=`<div class="weekly-applied-v281">✓ ${n?n+' Plananpassungen gespeichert.':'Keine passenden Smart-Plan-Übungen gefunden.'}</div>`})}}
const render281=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const page=[...document.querySelectorAll('.page')].find(p=>/Statistik/.test(p.querySelector('.page-head h1')?.textContent||''));if(!page)return;let card=page.querySelector('.weekly-muscle-v281');if(!card){card=document.createElement('button');card.type='button';card.className='weekly-muscle-v281';card.onclick=open281;const anchor=page.querySelector('.exercise-progress-v280')||page.querySelector('.training-history-v234');anchor?.insertAdjacentElement('afterend',card)||page.appendChild(card)}const score=week281(),flags=groups281.filter(g=>auto281(score[g])!=='passt');card.innerHTML=`<span><small>WOCHENFEEDBACK</small><strong>Muskelbelastung auswerten</strong><em>${flags.length?flags.length+' Bereiche mit Anpassungsvorschlag':'Belastung aktuell ausgeglichen'}</em></span><b>Öffnen</b>`}
let q281=false;const schedule281=()=>{if(q281||document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;q281=true;requestAnimationFrame(()=>{q281=false;render281()})}
if(typeof document!=='undefined'){const o=new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))schedule281()});const start=()=>{render281();o.observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
