// FitTogether V2.0.114: smarter weekly plan adaptation (one best exercise per muscle, RIR/progress aware).
const r282=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const w282=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const esc282=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm282=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const groups282=['Brust','Rücken','Beine','Schultern','Bizeps','Trizeps','Bauch','Gesäß','Waden']
const muscle282=(name,raw='')=>{const s=`${name||''} ${raw||''}`.toLowerCase();if(/chest|pector|brust|bench|fly|push.?up|liegestütz/.test(s))return'Brust';if(/lat|back|rücken|row|rudern|pull.?up|klimm|deadlift|kreuzheben/.test(s))return'Rücken';if(/quad|hamstring|thigh|leg|beine|squat|kniebeuge|lunge|ausfallschritt/.test(s))return'Beine';if(/delt|shoulder|schulter|overhead|seitheben/.test(s))return'Schultern';if(/biceps|bizeps|curl/.test(s))return'Bizeps';if(/triceps|trizeps|extension|pushdown|dip/.test(s))return'Trizeps';if(/abs|abdom|core|bauch|crunch|plank/.test(s))return'Bauch';if(/glute|gesäß|hip thrust/.test(s))return'Gesäß';if(/calf|wade/.test(s))return'Waden';return''}
const recent282=name=>{const cut=Date.now()-21*86400000,sets=[];for(const w of r282('ft-completed-workouts',[])){if((Number(w?.date)||0)<cut)continue;for(const s of w?.sets||[])if(norm282(s?.exercise)===norm282(name))sets.push({...s,date:Number(w.date)||0})}return sets}
const stats282=name=>{const a=recent282(name),rirs=a.map(x=>x.rir==='4+'?4:Number(x.rir)).filter(Number.isFinite),reps=a.map(x=>Number(x.actualReps??x.reps)).filter(Number.isFinite),avgRir=rirs.length?rirs.reduce((x,y)=>x+y,0)/rirs.length:2,half=Math.max(1,Math.floor(reps.length/2)),old=reps.slice(0,half),fresh=reps.slice(half),avg=x=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,trend=avg(fresh)-avg(old);return{count:a.length,avgRir,trend}}
const smartExercises282=()=>{const out=[];r282('ft-plans',[]).forEach((p,pi)=>{if(!String(p?.name||'').startsWith('Smart Plan'))return;(p.sessions||[]).forEach((s,si)=>{if(typeof s==='string')return;(s.exercises||[]).forEach((x,xi)=>{const group=muscle282(x?.name,`${x?.muscle||''} ${x?.query||''}`);if(group)out.push({pi,si,xi,group,x,stats:stats282(x.name)})})})});return out}
const choose282=(group,assessment)=>{const xs=smartExercises282().filter(x=>x.group===group);if(!xs.length)return null;return xs.sort((a,b)=>{if(assessment==='zu wenig'){const sa=(a.stats.avgRir>=2?2:0)+(a.stats.trend>=0?1:0)+Math.min(a.stats.count,6)/10-(Number(a.x.sets)||3)/20,sb=(b.stats.avgRir>=2?2:0)+(b.stats.trend>=0?1:0)+Math.min(b.stats.count,6)/10-(Number(b.x.sets)||3)/20;return sb-sa}const sa=(a.stats.avgRir<=1.5?3:0)+(a.stats.trend<0?2:0)+(Number(a.x.sets)||3)/10,sb=(b.stats.avgRir<=1.5?3:0)+(b.stats.trend<0?2:0)+(Number(b.x.sets)||3)/10;return sb-sa})[0]}
const preview282=proposal=>proposal.map(p=>{const hit=choose282(p.group,p.assessment);if(!hit)return{...p,skip:true};const before=Math.max(1,Number(hit.x.sets)||3),after=p.assessment==='zu wenig'?Math.min(5,before+1):Math.max(1,before-1),reason=p.assessment==='zu wenig'?(hit.stats.avgRir>=3?'RIR zeigt noch deutliche Reserve':hit.stats.trend>0?'Fortschritt ist stabil – Volumen kann leicht steigen':'beste passende Übung für zusätzliches Volumen'):(hit.stats.avgRir<=1.5?'RIR ist bereits sehr niedrig – zuerst Volumen reduzieren':hit.stats.trend<0?'Leistung zuletzt rückläufig – Erholung priorisieren':'Volumen dieser Muskelgruppe reduzieren');return{...p,hit,before,after,reason,skip:before===after}})
const apply282=items=>{const plans=r282('ft-plans',[]);let changed=0;for(const it of items){if(it.skip||!it.hit)continue;const x=plans[it.hit.pi]?.sessions?.[it.hit.si]?.exercises?.[it.hit.xi];if(!x)continue;x.sets=it.after;if(Array.isArray(x.plannedSets)){const seed=x.plannedSets.at(-1)||x.smartRecommendation||{};while(x.plannedSets.length<it.after)x.plannedSets.push({...seed});x.plannedSets=x.plannedSets.slice(0,it.after)}changed++}if(changed){w282('ft-plans',plans);w282('ft-weekly-muscle-last-applied',{date:Date.now(),version:'V2.0.114',changes:items.map(x=>({group:x.group,exercise:x.hit?.x?.name,before:x.before,after:x.after,reason:x.reason}))});window.FitTogetherCloud?.upload?.();window.dispatchEvent(new CustomEvent('ft-stats-refresh'))}return changed}
const upgrade282=()=>{const ov=document.querySelector('.weekly-muscle-modal-v281');if(!ov||ov.dataset.v282)return;ov.dataset.v282='1';const btn=ov.querySelector('[data-preview]');if(!btn)return;btn.addEventListener('click',()=>setTimeout(()=>{const box=ov.querySelector('.weekly-proposal-v281');if(!box||box.hidden)return;const proposal=[];ov.querySelectorAll('[data-group]').forEach(row=>{const active=row.querySelector('[data-v].active')?.dataset.v;if(active&&active!=='passt')proposal.push({group:row.dataset.group,assessment:active})});const items=preview282(proposal);box.innerHTML=`<small>SMARTER VORSCHLAG · VORHER → NACHHER</small>${items.length?items.map(it=>it.skip?`<div><strong>${esc282(it.group)}</strong><span>Keine passende Smart-Plan-Übung gefunden.</span></div>`:`<div class="weekly-smart-change-v282"><strong>${esc282(it.group)} · ${esc282(it.hit.x.name)}</strong><span>${it.before} Sätze → <b>${it.after} Sätze</b></span><em>${esc282(it.reason)} · Ø RIR ${it.hit.stats.avgRir.toFixed(1).replace('.',',')}</em></div>`).join(''):'<p>Aktuell keine Anpassung nötig.</p>'}<button type="button" data-apply282 ${items.some(x=>!x.skip)?'':'disabled'}>Diese Änderungen übernehmen</button>`;box.querySelector('[data-apply282]')?.addEventListener('click',()=>{const n=apply282(items);box.innerHTML=`<div class="weekly-applied-v281">✓ ${n?n+' gezielte Plananpassungen gespeichert.':'Keine Änderung nötig.'}</div>`})},0),true)}
const relevant282=n=>n?.nodeType===1&&(n.matches?.('.weekly-muscle-modal-v281')||n.querySelector?.('.weekly-muscle-modal-v281'))
if(typeof document!=='undefined'){const o=new MutationObserver(m=>{if(m.some(x=>[...x.addedNodes].some(relevant282)))upgrade282()});const start=()=>{upgrade282();o.observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
