// FitTogether V2.0.83: automatic Monday-to-Sunday training cycle + weekly archive.
const r283=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const w283=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const startWeek283=d=>{const x=new Date(d),day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x.getTime()}
const endWeek283=s=>s+7*86400000-1
const label283=s=>`${new Date(s).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}–${new Date(endWeek283(s)).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})}`
const archive283=(weekStart)=>{const history=r283('ft-weekly-history',[]);if(history.some(x=>x.weekStart===weekStart))return;const workouts=r283('ft-completed-workouts',[]).filter(w=>{const d=Number(w?.date)||0;return d>=weekStart&&d<=endWeek283(weekStart)}),sets=workouts.flatMap(w=>Array.isArray(w.sets)?w.sets:[]),rirs=sets.map(s=>s.rir==='4+'?4:Number(s.rir)).filter(Number.isFinite),avgRir=rirs.length?rirs.reduce((a,b)=>a+b,0)/rirs.length:null,last=r283('ft-weekly-muscle-last-applied',null),feedback=r283('ft-weekly-muscle-feedback',{}),plans=r283('ft-plans',[]).filter(p=>String(p?.name||'').startsWith('Smart Plan')).map(p=>JSON.parse(JSON.stringify(p)));history.push({weekStart,weekEnd:endWeek283(weekStart),label:label283(weekStart),workouts:workouts.length,sets:sets.length,avgRir,feedback,planChanges:last?.date>=weekStart&&last?.date<=endWeek283(weekStart)?last:null,smartPlans:plans,archivedAt:Date.now()});w283('ft-weekly-history',history.slice(-26));window.FitTogetherCloud?.upload?.()}
const cycle283=()=>{const now=Date.now(),current=startWeek283(now),state=r283('ft-week-cycle-v283',null);if(!state){w283('ft-week-cycle-v283',{weekStart:current});return}if(state.weekStart<current){for(let s=state.weekStart;s<current;s+=7*86400000)archive283(s);w283('ft-week-cycle-v283',{weekStart:current,rolledAt:now});w283('ft-weekly-review-ready',{weekStart:current-7*86400000,createdAt:now});window.dispatchEvent(new CustomEvent('ft-week-rollover-v283'))}}
const render283=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const page=[...document.querySelectorAll('.page')].find(p=>/Statistik/.test(p.querySelector('.page-head h1')?.textContent||''));if(!page)return;let box=page.querySelector('.weekly-cycle-v283');if(!box){box=document.createElement('section');box.className='weekly-cycle-v283';const a=page.querySelector('.weekly-muscle-v281')||page.querySelector('.exercise-progress-v280');a?.insertAdjacentElement('afterend',box)||page.appendChild(box)}const current=startWeek283(Date.now()),hist=r283('ft-weekly-history',[]).slice(-4).reverse(),workouts=r283('ft-completed-workouts',[]).filter(w=>(Number(w?.date)||0)>=current).length;box.innerHTML=`<div class="section-title"><span>Trainingswoche</span></div><div class="week-current-v283"><small>AKTUELLE WOCHE · ${label283(current)}</small><strong>${workouts} ${workouts===1?'Training':'Trainings'} abgeschlossen</strong><span>Am Montag startet automatisch eine neue Woche. Die vorherige Woche bleibt als Verlauf gespeichert.</span></div>${hist.length?`<div class="week-history-v283">${hist.map(h=>`<div><span><strong>${h.label}</strong><small>${h.workouts} Trainings · ${h.sets} Sätze${h.avgRir==null?'':` · Ø RIR ${h.avgRir.toFixed(1).replace('.',',')}`}</small></span><b>${h.planChanges?'angepasst':'archiviert'}</b></div>`).join('')}</div>`:''}`}
let q283=false;const schedule283=()=>{if(q283)return;q283=true;requestAnimationFrame(()=>{q283=false;cycle283();render283()})};if(typeof document!=='undefined'){const start=()=>{cycle283();render283();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length))schedule283()}).observe(document.body,{childList:true,subtree:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule283()});window.addEventListener('pageshow',schedule283)};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
