// FitTogether V2.0.120: keep one exercise search/category UI; this layer only adds muscle/equipment filtering.
const read291=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
let mediaMap291=null,load291=null
const MUSCLES291=['abductors','abs','adductors','biceps','calves','cardio','delts','forearms','glutes','hamstrings','lats','levator-scapulae','pectorals','quads','serratus-anterior','spine','traps','triceps','upper-back']
const API291='https://raw.githubusercontent.com/JahelCuadrado/ExerciseGymGifsDB/main/api/en/muscles/'
const loadMap291=()=>load291||(load291=Promise.all(MUSCLES291.map(m=>fetch(`${API291}${m}.json`).then(r=>r.json()).catch(()=>({exercises:[]})))).then(groups=>{const map=new Map();groups.forEach(g=>(g.exercises||[]).forEach(x=>{[x.thumbUrl,x.gifUrl].filter(Boolean).forEach(u=>map.set(String(u),{muscle:String(x.muscle||''),category:String(x.category||''),bodyPart:String(x.bodyPart||''),equipment:String(x.equipment||''),name:String(x.name||'')}))}));mediaMap291=map;return map}))
const source291=card=>{const img=card.querySelector('img'),src=img?.currentSrc||img?.src||'';if(mediaMap291&&src){if(mediaMap291.has(src))return mediaMap291.get(src);for(const[url,data]of mediaMap291){if(src.endsWith(url)||url.endsWith(src))return data}}return null}
const matchEq291=(text,e)=>{const t=String(text||'').toLowerCase();if(/laufband|treadmill/.test(t))return e.treadmill!==false;if(/fahrrad|ergometer|bike|bicycle|cycling|cycle/.test(t))return e.bike!==false;if(/rudergerät|rowing machine|rower/.test(t))return e.rower!==false;if(/kurzhantel|dumbbell/.test(t))return e.dumbbell!==false;if(/langhantel|sz-stange|barbell|ez bar/.test(t))return e.barbell!==false;if(/körpergewicht|body.?weight|bodyweight/.test(t))return e.bodyweight!==false;if(/widerstandsband|band/.test(t))return e.band!==false;if(/kabelzug|maschine|multipresse|machine|cable|smith|leverage/.test(t))return e.machine!==false;return true}
const apply291=()=>{const grid=document.querySelector('.exercise-grid');if(!grid)return;const cards=[...grid.querySelectorAll('.exercise-card-v2')],muscle=read291('ft-exercise-muscle-v239','Alle'),onlyMine=read291('ft-exercise-only-mine-v238',false),equipment=read291('ft-available-equipment-v238',read291('ft-equipment-profile',{})?.equipment||{});let visible=0;cards.forEach(card=>{const data=source291(card),text=[card.textContent,data?.name,data?.muscle,data?.equipment,data?.bodyPart].filter(Boolean).join(' '),muscleOk=muscle==='Alle'||data?.muscle===muscle,eqOk=!onlyMine||matchEq291(text,equipment),show=muscleOk&&eqOk;card.hidden=!show;if(show)visible++});let count=document.querySelector('.exercise-count-v291');if(!count){count=document.createElement('small');count.className='exercise-count-v291';grid.insertAdjacentElement('beforebegin',count)}count.textContent=`${visible} Übungen`;let empty=document.querySelector('.exercise-empty-v291');if(!empty){empty=document.createElement('div');empty.className='exercise-empty-v291';empty.innerHTML='<strong>Keine Übungen gefunden</strong><span>Suche oder Filter anpassen.</span>';grid.insertAdjacentElement('afterend',empty)}empty.hidden=visible!==0}
const ensure291=()=>{document.querySelector('.exercise-filter-v291')?.remove();const row=document.querySelector('.filter-row'),grid=document.querySelector('.exercise-grid');if(!row||!grid)return;const muscle=row.querySelector('.muscle-filter-v239')||document.querySelector('.muscle-filter-v239');if(muscle&&!muscle.dataset.v291){muscle.dataset.v291='1';muscle.addEventListener('change',()=>setTimeout(apply291,0))}const mine=document.querySelector('.only-mine-v238 input');if(mine&&!mine.dataset.v291){mine.dataset.v291='1';mine.addEventListener('change',()=>setTimeout(apply291,0))}}
let q291=false;const enhance291=()=>{q291=false;ensure291();loadMap291().then(apply291)};const schedule291=()=>{if(q291||document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;q291=true;requestAnimationFrame(enhance291)}
if(typeof document!=='undefined'){const start=()=>{enhance291();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))schedule291()}).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
