// FitTogether V2.0.91: unified exercise search + category, muscle and equipment filtering.
const KEY_CAT291='ft-exercise-category-v291'
const read291=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const write291=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
let query291='',category291=read291(KEY_CAT291,'Alle'),mediaMap291=null,load291=null
const MUSCLES291=['abductors','abs','adductors','biceps','calves','cardio','delts','forearms','glutes','hamstrings','lats','levator-scapulae','pectorals','quads','serratus-anterior','spine','traps','triceps','upper-back']
const API291='https://raw.githubusercontent.com/JahelCuadrado/ExerciseGymGifsDB/main/api/en/muscles/'
const loadMap291=()=>load291||(load291=Promise.all(MUSCLES291.map(m=>fetch(`${API291}${m}.json`).then(r=>r.json()).catch(()=>({exercises:[]})))).then(groups=>{const map=new Map();groups.forEach(g=>(g.exercises||[]).forEach(x=>{[x.thumbUrl,x.gifUrl].filter(Boolean).forEach(u=>map.set(String(u),{muscle:String(x.muscle||''),category:String(x.category||''),bodyPart:String(x.bodyPart||''),equipment:String(x.equipment||''),name:String(x.name||'')}))}));mediaMap291=map;return map}))
const source291=card=>{const img=card.querySelector('img'),src=img?.currentSrc||img?.src||'';if(mediaMap291&&src){if(mediaMap291.has(src))return mediaMap291.get(src);for(const[url,data]of mediaMap291){if(src.endsWith(url)||url.endsWith(src))return data}}return null}
const cat291=(card,data)=>{const t=((card.textContent||'')+' '+(data?.category||'')+' '+(data?.bodyPart||'')+' '+(data?.name||'')).toLowerCase();if(/cardio|cardiovascular|treadmill|laufband|bike|cycling|ergometer|rower|rowing/.test(t))return'Cardio';if(/stretch|dehnen|dehnung|mobility/.test(t))return'Dehnen';if(/yoga|sphinx|cobra/.test(t))return'Yoga';return'Kraft'}
const matchEq291=(text,e)=>{const t=String(text||'').toLowerCase();if(/laufband|treadmill/.test(t))return e.treadmill!==false;if(/fahrrad|ergometer|bike|bicycle|cycling|cycle/.test(t))return e.bike!==false;if(/rudergerät|rowing machine|rower/.test(t))return e.rower!==false;if(/kurzhantel|dumbbell/.test(t))return e.dumbbell!==false;if(/langhantel|sz-stange|barbell|ez bar/.test(t))return e.barbell!==false;if(/körpergewicht|body.?weight|bodyweight/.test(t))return e.bodyweight!==false;if(/widerstandsband|band/.test(t))return e.band!==false;if(/kabelzug|maschine|multipresse|machine|cable|smith|leverage/.test(t))return e.machine!==false;if(/cardio|yoga|dehnen|stretch/.test(t))return true;return true}
const normalize291=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9äöüß]+/g,' ').trim()
const apply291=()=>{const grid=document.querySelector('.exercise-grid');if(!grid)return;const cards=[...grid.querySelectorAll('.exercise-card-v2')],muscle=read291('ft-exercise-muscle-v239','Alle'),onlyMine=read291('ft-exercise-only-mine-v238',false),equipment=read291('ft-available-equipment-v238',read291('ft-equipment-profile',{})?.equipment||{}),q=normalize291(query291);let visible=0;cards.forEach(card=>{const data=source291(card),text=[card.textContent,data?.name,data?.muscle,data?.equipment,data?.bodyPart].filter(Boolean).join(' '),searchOk=!q||normalize291(text).includes(q),catOk=category291==='Alle'||cat291(card,data)===category291,muscleOk=muscle==='Alle'||data?.muscle===muscle,eqOk=!onlyMine||matchEq291(text,equipment),show=searchOk&&catOk&&muscleOk&&eqOk;card.hidden=!show;if(show)visible++});const count=document.querySelector('.exercise-count-v291');if(count)count.textContent=`${visible} Übungen`;const empty=document.querySelector('.exercise-empty-v291');if(empty)empty.hidden=visible!==0}
const ensure291=()=>{const grid=document.querySelector('.exercise-grid'),row=document.querySelector('.filter-row');if(!grid||!row)return;let box=document.querySelector('.exercise-filter-v291');if(!box){box=document.createElement('section');box.className='exercise-filter-v291';box.innerHTML=`<div class="exercise-search-v291"><span>⌕</span><input type="search" inputmode="search" autocomplete="off" placeholder="Übung suchen …" aria-label="Übung suchen"><button type="button" aria-label="Suche löschen">×</button></div><div class="exercise-categories-v291">${['Alle','Kraft','Cardio','Yoga','Dehnen'].map(x=>`<button type="button" data-cat="${x}">${x}</button>`).join('')}</div><div class="exercise-result-v291"><small class="exercise-count-v291"></small></div>`;row.insertAdjacentElement('afterend',box);const input=box.querySelector('input');input.value=query291;input.addEventListener('input',()=>{query291=input.value;apply291()});box.querySelector('.exercise-search-v291 button').onclick=()=>{query291='';input.value='';input.focus();apply291()};box.querySelectorAll('[data-cat]').forEach(btn=>btn.onclick=()=>{category291=btn.dataset.cat;write291(KEY_CAT291,category291);paint291();apply291()})}paint291();let empty=document.querySelector('.exercise-empty-v291');if(!empty){empty=document.createElement('div');empty.className='exercise-empty-v291';empty.hidden=true;empty.innerHTML='<strong>Keine Übungen gefunden</strong><span>Suche oder Filter anpassen.</span>';grid.insertAdjacentElement('afterend',empty)};const oldSelect=row.querySelector('.muscle-filter-v239');if(oldSelect&&!oldSelect.dataset.v291){oldSelect.dataset.v291='1';oldSelect.addEventListener('change',()=>setTimeout(apply291,0))}const mine=document.querySelector('.only-mine-v238 input');if(mine&&!mine.dataset.v291){mine.dataset.v291='1';mine.addEventListener('change',()=>setTimeout(apply291,0))}}
const paint291=()=>document.querySelectorAll('.exercise-categories-v291 [data-cat]').forEach(btn=>btn.classList.toggle('active',btn.dataset.cat===category291))
let q291=false;const enhance291=()=>{q291=false;ensure291();loadMap291().then(apply291)};const schedule291=()=>{if(q291||document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;q291=true;requestAnimationFrame(enhance291)}
if(typeof document!=='undefined'){const start=()=>{enhance291();new MutationObserver(m=>{if(m.some(x=>[...x.addedNodes].some(n=>n.nodeType===1&&!n.classList?.contains('exercise-filter-v291')&&!n.classList?.contains('exercise-empty-v291'))))schedule291()}).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
