// FitTogether V2.0.92: favorites + recently trained shortcuts in exercise library.
const FAV292='ft-exercise-favorites-v292',REC292='ft-exercise-recents-v292'
const read292=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
const write292=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const norm292=s=>String(s||'').trim().toLowerCase()
const cardName292=c=>c.querySelector('strong')?.textContent?.trim()||''
const favorites292=()=>read292(FAV292,[])
const toggleFav292=name=>{let a=favorites292();const n=norm292(name);a=a.some(x=>norm292(x)===n)?a.filter(x=>norm292(x)!==n):[name,...a].slice(0,100);write292(FAV292,a);window.FitTogetherCloud?.upload?.();enhance292()}
const markRecent292=name=>{if(!name)return;let a=read292(REC292,[]).filter(x=>norm292(x.name)!==norm292(name));a.unshift({name,date:Date.now()});write292(REC292,a.slice(0,20))}
const scanCompleted292=()=>{const out=[];for(const w of read292('ft-completed-workouts',[]).slice().reverse()){const names=[];if(w?.name)names.push(w.name);for(const s of w?.sets||[])if(s?.exercise)names.push(s.exercise);for(const n of names){if(n&&!out.some(x=>norm292(x.name)===norm292(n)))out.push({name:n,date:Number(w.date)||Date.now()});if(out.length>=8)return out}}return out}
const applyMode292=mode=>{document.querySelectorAll('.exercise-shortcuts-v292 button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));const cards=[...document.querySelectorAll('.exercise-grid .exercise-card-v2')];if(mode==='all'){cards.forEach(c=>c.removeAttribute('data-shortcut-hide'));return}const names=mode==='fav'?favorites292():[...read292(REC292,[]),...scanCompleted292()].map(x=>x.name);cards.forEach(c=>{const show=names.some(n=>norm292(n)===norm292(cardName292(c)));c.toggleAttribute('data-shortcut-hide',!show)})}
const renderShortcuts292=()=>{const grid=document.querySelector('.exercise-grid'),row=document.querySelector('.exercise-search-v291')||document.querySelector('.filter-row');if(!grid||!row)return;let box=document.querySelector('.exercise-shortcuts-v292');if(!box){box=document.createElement('div');box.className='exercise-shortcuts-v292';box.innerHTML='<button type="button" data-mode="all" class="active">Alle</button><button type="button" data-mode="fav">★ Favoriten</button><button type="button" data-mode="recent">Zuletzt trainiert</button>';row.insertAdjacentElement('afterend',box);box.querySelectorAll('button').forEach(b=>b.onclick=()=>applyMode292(b.dataset.mode))}const fav=favorites292();grid.querySelectorAll('.exercise-card-v2').forEach(card=>{let b=card.querySelector('.favorite-v292');if(!b){b=document.createElement('button');b.type='button';b.className='favorite-v292';b.setAttribute('aria-label','Favorit');b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFav292(cardName292(card))};card.appendChild(b)}b.textContent=fav.some(x=>norm292(x)===norm292(cardName292(card)))?'★':'☆';b.classList.toggle('active',b.textContent==='★')})}
const enhanceDetail292=()=>{const d=document.querySelector('.exercise-detail-copy');if(!d)return;const name=d.querySelector('h2')?.textContent?.trim();if(!name)return;let b=d.querySelector('.detail-favorite-v292');if(!b){b=document.createElement('button');b.type='button';b.className='detail-favorite-v292';d.querySelector('h2')?.insertAdjacentElement('afterend',b);b.onclick=()=>toggleFav292(name)}const on=favorites292().some(x=>norm292(x)===norm292(name));b.textContent=on?'★ Favorit':'☆ Als Favorit speichern';b.classList.toggle('active',on)}
if(typeof document!=='undefined'){document.addEventListener('click',e=>{const b=e.target.closest('.quick-start-v220,.detail-start-v220');if(!b)return;const card=b.closest('.exercise-card-v2'),d=document.querySelector('.exercise-detail-copy');markRecent292(cardName292(card)||d?.querySelector('h2')?.textContent)},true);let q=false;const schedule=()=>{if(q||document.querySelector('.active-training,.rest-overlay'))return;q=true;requestAnimationFrame(()=>{q=false;renderShortcuts292();enhanceDetail292()})};const start=()=>{schedule();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
