// FitTogether V2.0.93: exercise history + next recommendation directly in exercise details.
const read293=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const esc293=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm293=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const fmt293=n=>String(Number(n)||0).replace('.',',')
const load293=s=>{const extra=Number(s.actualExtraWeight??s.extraWeight)||0;const weight=Number(s.actualWeight??s.weight)||0;return extra>0?`+${fmt293(extra)} kg`:weight>0?`${fmt293(weight)} kg`:'Körpergewicht'}
const sessions293=name=>{const a=[];for(const workout of read293('ft-completed-workouts',[])){const sets=(workout?.sets||[]).filter(s=>norm293(s.exercise)===norm293(name));if(sets.length)a.push({date:Number(workout.date)||0,sets})}return a.sort((a,b)=>b.date-a.date)}
const recommendation293=(name,last)=>{const book=read293('ft-exercise-loads-v275',{});const found=Object.entries(book).find(([k])=>norm293(k)===norm293(name));const saved=book[name]||(found?found[1]:{});const planned=Array.isArray(saved.sets)?saved.sets:[];if(!planned.length&&!last?.sets?.length)return'Noch keine Empfehlung';const count=Math.max(planned.length,last?.sets?.length||0,1);return Array.from({length:count},(_,i)=>{const x=planned[i]||{};const lastSets=last?.sets||[];const l=lastSets.length?lastSets[Math.min(i,lastSets.length-1)]:{};const reps=Number(x.reps)||Number(l.actualReps??l.reps)||10;const extra=Number(x.extraWeight)||0;const weight=Number(x.weight)||0;const load=extra>0?` · +${fmt293(extra)} kg`:weight>0?` · ${fmt293(weight)} kg`:'';return`S${i+1}: ${reps} Wdh.${load} · RIR ${Number(x.rirTarget??2)}`}).join('  |  ')}
const render293=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const d=document.querySelector('.exercise-detail-copy');if(!d)return;const name=d.querySelector('h2')?.textContent?.trim();if(!name)return;let box=d.querySelector('.detail-history-v293');if(!box){box=document.createElement('section');box.className='detail-history-v293';const action=d.querySelector('.detail-start-v220');action?.insertAdjacentElement('beforebegin',box)||d.appendChild(box)}const sessions=sessions293(name);const last=sessions[0];const sig=JSON.stringify(sessions.slice(0,3))+JSON.stringify(read293('ft-exercise-loads-v275',{})[name]);if(box.dataset.sig===sig)return;box.dataset.sig=sig;box.innerHTML=`<div class="detail-history-head-v293"><span>DEIN VERLAUF</span><b>${sessions.length?`${sessions.length} ${sessions.length===1?'Einheit':'Einheiten'}`:'Noch kein Training'}</b></div><div class="detail-next-v293"><small>NÄCHSTE EMPFEHLUNG</small><strong>${esc293(recommendation293(name,last))}</strong></div>${sessions.length?`<div class="detail-sessions-v293">${sessions.slice(0,3).map(s=>`<div><time>${new Date(s.date).toLocaleDateString('de-DE')}</time><span>${s.sets.map((x,i)=>`S${i+1} ${Number(x.actualReps??x.reps)||0}× ${load293(x)} · RIR ${x.rir??'–'}`).join('  |  ')}</span></div>`).join('')}</div>`:'<p class="detail-empty-v293">Nach deinem ersten Training mit dieser Übung erscheint hier dein Satz- und Gewichtsverlauf.</p>'}`}
let q293=false;const schedule293=()=>{if(q293)return;q293=true;requestAnimationFrame(()=>{q293=false;render293()})};if(typeof document!=='undefined'){const start=()=>{render293();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))schedule293()}).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
