// FitTogether V2.0.93: exercise history + next recommendation directly in exercise details.
const read293=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const esc293=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm293=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const fmt293=n=>String(Number(n)||0).replace('.',',')
const load293=s=>{const extra=Number(s.actualExtraWeight??s.extraWeight)||0,w=Number(s.actualWeight??s.weight)||0;return extra>0?`+${fmt293(extra)} kg`:w>0?`${fmt293(w)} kg`:'Körpergewicht'}
const sessions293=name=>{const a=[];for(const w of read293('ft-completed-workouts',[])){const sets=(w?.sets||[]).filter(s=>norm293(s.exercise)===norm293(name));if(sets.length)a.push({date:Number(w.date)||0,sets})}return a.sort((a,b)=>b.date-a.date)}
const recommendation293=name,last=>{const book=read293('ft-exercise-loads-v275',{}),saved=book[name]||Object.entries(book).find(([k])=>norm293(k)===norm293(name))?.[1]||{},p=Array.isArray(saved.sets)?saved.sets:[];if(!p.length&&!last?.sets?.length)return'Noch keine Empfehlung';const count=Math.max(p.length,last?.sets?.length||0,1);return Array.from({length:count},(_,i)=>{const x=p[i]||{},l=last?.sets?.[Math.min(i,(last.sets?.length||1)-1)]||{},reps=Number(x.reps)||Number(l.actualReps??l.reps)||10,extra=Number(x.extraWeight)||0,w=Number(x.weight)||0,load=extra>0?` · +${fmt293(extra)} kg`:w>0?` · ${fmt293(w)} kg`:'';return`S${i+1}: ${reps} Wdh.${load} · RIR ${Number(x.rirTarget??2)}`}).join('  |  ')}
const render293=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const d=document.querySelector('.exercise-detail-copy');if(!d)return;const name=d.querySelector('h2')?.textContent?.trim();if(!name)return;let box=d.querySelector('.detail-history-v293');if(!box){box=document.createElement('section');box.className='detail-history-v293';const action=d.querySelector('.detail-start-v220');action?.insertAdjacentElement('beforebegin',box)||d.appendChild(box)}const sessions=sessions293(name),last=sessions[0],sig=JSON.stringify(sessions.slice(0,3))+JSON.stringify(read293('ft-exercise-loads-v275',{})[name]);if(box.dataset.sig===sig)return;box.dataset.sig=sig;box.innerHTML=`<div class="detail-history-head-v293"><span>DEIN VERLAUF</span><b>${sessions.length?`${sessions.length} ${sessions.length===1?'Einheit':'Einheiten'}`:'Noch kein Training'}</b></div><div class="detail-next-v293"><small>NÄCHSTE EMPFEHLUNG</small><strong>${esc293(recommendation293(name,last))}</strong></div>${sessions.length?`<div class="detail-sessions-v293">${sessions.slice(0,3).map(s=>`<div><time>${new Date(s.date).toLocaleDateString('de-DE')}</time><span>${s.sets.map((x,i)=>`S${i+1} ${Number(x.actualReps??x.reps)||0}× ${load293(x)} · RIR ${x.rir??'–'}`).join('  |  ')}</span></div>`).join('')}</div>`:'<p class="detail-empty-v293">Nach deinem ersten Training mit dieser Übung erscheint hier dein Satz- und Gewichtsverlauf.</p>'}`}
let q293=false;const schedule293=()=>{if(q293)return;q293=true;requestAnimationFrame(()=>{q293=false;render293()})};if(typeof document!=='undefined'){const start=()=>{render293();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))schedule293()}).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
