// FitTogether V2.0.124: post-workout summary for strength and cardio.
const read294=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const esc294=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))
const num294=v=>{const n=Number(v);return Number.isFinite(n)?n:0}
const rir294=v=>String(v??'').replace('+','')
const latest294=()=>{const a=read294('ft-completed-workouts',[]);return a.length?a[a.length-1]:null}
const workoutKey294=w=>w?`${w.date||0}|${w.sets?.length||0}|${w.name||''}`:''
const cardio294=w=>w?.kind==='cardio'||Array.isArray(w?.sets)&&w.sets.length>0&&w.sets.every(s=>s?.kind==='cardio'||s?.loadType==='cardio')
const cardioSeconds294=w=>{const direct=num294(w?.actualSeconds??w?.durationSeconds);if(direct>0)return direct;return(Array.isArray(w?.sets)?w.sets:[]).reduce((a,s)=>a+num294(s?.durationSeconds||num294(s?.durationMinutes)*60),0)}
const duration294=s=>{const n=Math.max(0,Math.round(num294(s)));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
const stats294=w=>{const sets=Array.isArray(w?.sets)?w.sets:[];const exercises=[...new Set(sets.map(s=>s.exercise).filter(Boolean))];const reps=sets.reduce((a,s)=>a+num294(s.actualReps??s.reps),0);const volume=sets.reduce((a,s)=>{const r=num294(s.actualReps??s.reps),weight=num294(s.actualWeight??s.weight)+num294(s.actualExtraWeight??s.extraWeight);return a+r*weight},0);const rs=sets.map(s=>num294(rir294(s.rir))).filter(Boolean);const avg=rs.length?rs.reduce((a,b)=>a+b,0)/rs.length:0;return{sets,exercises,reps,volume,avg}}
const comparison294=(w,s)=>{const all=read294('ft-completed-workouts',[]),idx=all.findIndex(x=>x===w||workoutKey294(x)===workoutKey294(w));const prev=all.slice(0,idx<0?all.length-1:idx).reverse().find(x=>Array.isArray(x?.sets)&&x.sets.length&&!cardio294(x));if(!prev)return'Das ist dein erster detailliert erfasster Vergleich.';const p=stats294(prev),d=s.volume-p.volume;if(s.volume&&p.volume&&Math.abs(d)>1)return d>0?`Heute ${Math.round(d)} kg mehr Trainingsvolumen als beim letzten Training.`:`Heute ${Math.round(Math.abs(d))} kg weniger Volumen – Erholung und RIR im Blick behalten.`;if(s.avg&&p.avg){const r=s.avg-p.avg;if(r>.35)return'Die Sätze waren heute etwas leichter als beim letzten Training.';if(r<-.35)return'Die Sätze waren heute härter als beim letzten Training.'}return'Belastung ähnlich wie beim letzten Training – gute Basis für kontinuierliche Steigerung.'}
const close294=()=>document.querySelector('.workout-summary-v294')?.remove()
const show294=w=>{if(!w||document.querySelector('.workout-summary-v294'))return;const s=stats294(w);if(!s.sets.length)return;const el=document.createElement('div');el.className='workout-summary-v294';if(cardio294(w)){const seconds=cardioSeconds294(w),mode=s.sets.some(x=>x?.entryMode==='timer')?'In FitTogether':'Nachgetragen';el.innerHTML=`<div class="summary-card-v294"><div class="summary-kicker-v294">CARDIO ABGESCHLOSSEN</div><h2>${esc294(w.name||s.exercises[0]||'Cardio')}</h2><div class="summary-grid-v294"><div><small>DAUER</small><strong>${duration294(seconds)}</strong></div><div><small>ÜBUNGEN</small><strong>${s.exercises.length||1}</strong></div><div><small>ERFASSUNG</small><strong>${esc294(mode)}</strong></div><div><small>ART</small><strong>Cardio</strong></div></div><div class="summary-exercises-v294">${s.exercises.map(name=>{const xs=s.sets.filter(x=>x.exercise===name),sec=xs.reduce((a,x)=>a+num294(x?.durationSeconds||num294(x?.durationMinutes)*60),0);return`<div><b>${esc294(name)}</b><span>${duration294(sec)} Min.</span></div>`}).join('')}</div><button type="button" class="summary-done-v294">Fertig</button></div>`}else{el.innerHTML=`<div class="summary-card-v294"><div class="summary-kicker-v294">TRAINING ABGESCHLOSSEN</div><h2>Stark. Einheit geschafft.</h2><div class="summary-grid-v294"><div><small>ÜBUNGEN</small><strong>${s.exercises.length||w.exercises||0}</strong></div><div><small>SÄTZE</small><strong>${s.sets.length}</strong></div><div><small>WDH.</small><strong>${s.reps}</strong></div><div><small>Ø RIR</small><strong>${s.avg?s.avg.toFixed(1).replace('.',','):'–'}</strong></div></div><div class="summary-volume-v294"><small>TRAININGSVOLUMEN</small><strong>${Math.round(s.volume).toLocaleString('de-DE')} kg</strong></div><p class="summary-tip-v294">${esc294(comparison294(w,s))}</p><div class="summary-exercises-v294">${s.exercises.slice(0,5).map(name=>{const xs=s.sets.filter(x=>x.exercise===name);return`<div><b>${esc294(name)}</b><span>${xs.length} Sätze · ${xs.reduce((a,x)=>a+num294(x.actualReps??x.reps),0)} Wdh.</span></div>`}).join('')}</div><button type="button" class="summary-done-v294">Fertig</button></div>`}el.querySelector('.summary-done-v294').onclick=close294;document.body.appendChild(el);localStorage.setItem('ft-last-summary-shown-v294',workoutKey294(w))}
let before294=workoutKey294(latest294()),armed294=false
if(typeof document!=='undefined'){const check294=()=>{const active=!!document.querySelector('.active-training,.free-workout-v247');if(active)armed294=true;const w=latest294(),key=workoutKey294(w);if(armed294&&!active&&key&&key!==before294){before294=key;armed294=false;show294(w)}};const start=()=>{new MutationObserver(check294).observe(document.body,{childList:true,subtree:true});setInterval(check294,1200)};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
