// FitTogether V2.0.95: personal records / PRs per exercise, read-only from completed workout data.
const read295=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const esc295=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm295=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const fmt295=n=>Number(n||0).toLocaleString('de-DE',{maximumFractionDigits:1})
const sets295=name=>{const out=[];for(const w of read295('ft-completed-workouts',[])){for(const s of w?.sets||[]){if(norm295(s.exercise)!==norm295(name))continue;out.push({...s,date:Number(w.date)||0})}}return out}
const load295=s=>{const extra=Number(s.actualExtraWeight??s.extraWeight)||0;const weight=Number(s.actualWeight??s.weight)||0;return extra>0?extra:weight}
const reps295=s=>Number(s.actualReps??s.reps)||0
const records295=name=>{const sets=sets295(name);if(!sets.length)return null;let maxLoad=null,maxReps=null,maxVolume=null;for(const s of sets){const load=load295(s),reps=reps295(s),volume=load*reps;if(load>0&&(!maxLoad||load>maxLoad.value||(load===maxLoad.value&&reps>maxLoad.reps)))maxLoad={value:load,reps,date:s.date};if(reps>0&&(!maxReps||reps>maxReps.value||(reps===maxReps.value&&load>maxReps.load)))maxReps={value:reps,load,date:s.date};if(volume>0&&(!maxVolume||volume>maxVolume.value))maxVolume={value:volume,load,reps,date:s.date}}
const sessions=new Map();for(const s of sets){const key=String(s.date||0);if(!sessions.has(key))sessions.set(key,{date:s.date,volume:0,sets:0,reps:0});const x=sessions.get(key),r=reps295(s),l=load295(s);x.volume+=r*l;x.sets++;x.reps+=r}let bestSession=null;for(const x of sessions.values())if(!bestSession||x.volume>bestSession.volume)bestSession=x;return{maxLoad,maxReps,maxVolume,bestSession,totalSets:sets.length}}
const date295=d=>d?new Date(d).toLocaleDateString('de-DE'):'–'
const render295=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const d=document.querySelector('.exercise-detail-copy');if(!d)return;const name=d.querySelector('h2')?.textContent?.trim();if(!name)return;let box=d.querySelector('.detail-prs-v295');if(!box){box=document.createElement('section');box.className='detail-prs-v295';const history=d.querySelector('.detail-history-v293');history?.insertAdjacentElement('beforebegin',box)||d.querySelector('.detail-start-v220')?.insertAdjacentElement('beforebegin',box)||d.appendChild(box)}const r=records295(name),sig=JSON.stringify(r);if(box.dataset.sig===sig)return;box.dataset.sig=sig;if(!r){box.innerHTML='<div class="detail-pr-head-v295"><span>PERSÖNLICHE REKORDE</span></div><p class="detail-pr-empty-v295">Nach deinen ersten gespeicherten Sätzen erscheinen hier deine Bestleistungen.</p>';return}const load=r.maxLoad?`${fmt295(r.maxLoad.value)} kg`:'–',loadSub=r.maxLoad?`${r.maxLoad.reps} Wdh. · ${date295(r.maxLoad.date)}`:'Noch kein Gewicht';const reps=r.maxReps?`${r.maxReps.value} Wdh.`:'–',repsSub=r.maxReps?`${r.maxReps.load>0?fmt295(r.maxReps.load)+' kg':'Körpergewicht'} · ${date295(r.maxReps.date)}`:'–';const setVol=r.maxVolume?`${fmt295(r.maxVolume.value)} kg`:'–',setVolSub=r.maxVolume?`${r.maxVolume.reps} × ${fmt295(r.maxVolume.load)} kg · ${date295(r.maxVolume.date)}`:'–';const session=r.bestSession?.volume>0?`${fmt295(r.bestSession.volume)} kg`:'–',sessionSub=r.bestSession?`${r.bestSession.sets} Sätze · ${r.bestSession.reps} Wdh. · ${date295(r.bestSession.date)}`:'–';box.innerHTML=`<div class="detail-pr-head-v295"><span>PERSÖNLICHE REKORDE</span><b>${r.totalSets} erfasste Sätze</b></div><div class="detail-pr-grid-v295"><article><small>HÖCHSTES GEWICHT</small><strong>${esc295(load)}</strong><span>${esc295(loadSub)}</span></article><article><small>MEISTE WDHL.</small><strong>${esc295(reps)}</strong><span>${esc295(repsSub)}</span></article><article><small>BESTER SATZ</small><strong>${esc295(setVol)}</strong><span>${esc295(setVolSub)}</span></article><article><small>BESTE EINHEIT</small><strong>${esc295(session)}</strong><span>${esc295(sessionSub)}</span></article></div>`}
let q295=false;const schedule295=()=>{if(q295)return;q295=true;requestAnimationFrame(()=>{q295=false;render295()})};if(typeof document!=='undefined'){const start=()=>{render295();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))schedule295()}).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
