// FitTogether V2.0.96: Home V2 + weekly/monthly training overview. No training-engine changes.
const read296=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const esc296=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const day296=86400000
const completed296=()=>read296('ft-completed-workouts',[]).filter(Boolean)
const sets296=w=>Array.isArray(w?.sets)?w.sets:[]
const volume296=w=>sets296(w).reduce((a,s)=>a+(Number(s.actualReps??s.reps)||0)*((Number(s.actualWeight??s.weight)||0)+(Number(s.actualExtraWeight??s.extraWeight)||0)),0)
const fmt296=n=>Math.round(n).toLocaleString('de-DE')
const latestPlan296=()=>{const p=read296('ft-plans',[]);return p.length?p[p.length-1]:null}
const sessionTitle296=p=>{if(!p)return'Dein nächstes Workout';const sessions=p.sessions||p.workouts||p.days||[];if(Array.isArray(sessions)&&sessions.length){const done=completed296().filter(w=>w.planId===p.id||w.plan===p.name).length;const s=sessions[done%sessions.length];return s?.title||s?.name||p.name||'Dein nächstes Workout'}return p.name||p.title||'Dein nächstes Workout'}
const home296=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const welcome=document.querySelector('.welcome');if(!welcome)return;let box=document.querySelector('.home-v296');if(!box){box=document.createElement('section');box.className='home-v296';welcome.insertAdjacentElement('afterend',box)}const now=Date.now(),all=completed296(),week=all.filter(w=>now-(Number(w.date)||0)<7*day296),month=all.filter(w=>now-(Number(w.date)||0)<30*day296),last=all.slice().sort((a,b)=>(b.date||0)-(a.date||0))[0],plan=latestPlan296(),title=sessionTitle296(plan),sig=`${all.length}|${last?.date||0}|${title}`;if(box.dataset.sig===sig)return;box.dataset.sig=sig;box.innerHTML=`<div class="home-next-v296"><div><small>HEUTE TRAINIEREN</small><h2>${esc296(title)}</h2><p>${plan?'Dein aktueller Plan ist bereit.':'Wähle Kraft, Cardio, Yoga oder freies Training.'}</p></div><button type="button" class="home-start-v296">Training starten</button></div><div class="home-mini-v296"><div><strong>${week.length}</strong><span>letzte 7 Tage</span></div><div><strong>${month.length}</strong><span>letzte 30 Tage</span></div><div><strong>${last?new Date(last.date).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'}):'–'}</strong><span>letztes Training</span></div></div>`;box.querySelector('.home-start-v296').onclick=()=>document.querySelector('.today')?.click()||document.querySelector('.start-strip')?.click();document.querySelector('.today')?.classList.add('legacy-home-v296');document.querySelector('.start-strip')?.classList.add('legacy-home-v296')}
const stats296=()=>{if(document.querySelector('.active-training,.rest-overlay'))return;const pages=[...document.querySelectorAll('.page')],page=pages.find(p=>/statistik/i.test(p.querySelector('.page-head h1')?.textContent||''));if(!page)return;let box=page.querySelector('.overview-v296');if(!box){box=document.createElement('section');box.className='overview-v296';const head=page.querySelector('.page-head');head?.insertAdjacentElement('afterend',box)||page.prepend(box)}const now=Date.now(),all=completed296(),week=all.filter(w=>now-(Number(w.date)||0)<7*day296),month=all.filter(w=>now-(Number(w.date)||0)<30*day296),wv=week.reduce((a,w)=>a+volume296(w),0),mv=month.reduce((a,w)=>a+volume296(w),0),days=new Set(month.map(w=>new Date(w.date).toISOString().slice(0,10))).size,sig=`${all.length}|${week.length}|${month.length}|${wv}|${mv}`;if(box.dataset.sig===sig)return;box.dataset.sig=sig;const bars=Array.from({length:7},(_,i)=>{const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-(6-i));const end=+start+day296;const count=all.filter(w=>(w.date||0)>=+start&&(w.date||0)<end).length;return`<div><i style="height:${count?Math.min(100,32+count*28):8}%"></i><span>${['So','Mo','Di','Mi','Do','Fr','Sa'][start.getDay()]}</span></div>`}).join('');box.innerHTML=`<div class="overview-title-v296"><small>TRAININGSÜBERSICHT</small><h2>Woche & Monat</h2></div><div class="overview-grid-v296"><div><small>7 TAGE</small><strong>${week.length}</strong><span>Trainings</span></div><div><small>30 TAGE</small><strong>${month.length}</strong><span>Trainings</span></div><div><small>AKTIVE TAGE</small><strong>${days}</strong><span>im Monat</span></div></div><div class="overview-chart-v296">${bars}</div><div class="overview-volume-v296"><div><span>Wochenvolumen</span><b>${fmt296(wv)} kg</b></div><div><span>Monatsvolumen</span><b>${fmt296(mv)} kg</b></div></div>`}
let q296=false;const run296=()=>{if(q296)return;q296=true;requestAnimationFrame(()=>{q296=false;home296();stats296()})};if(typeof document!=='undefined'){const start=()=>{run296();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))run296()}).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
