// FitTogether V2.0.113: intelligent Today recommendation without depending on the old Home V2 wrapper.
const r297=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const esc297=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm297=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const done297=()=>r297('ft-completed-workouts',[]).filter(Boolean)
const plans297=()=>r297('ft-plans',[]).filter(Boolean)
const sessions297=p=>Array.isArray(p?.sessions)?p.sessions:Array.isArray(p?.workouts)?p.workouts:Array.isArray(p?.days)?p.days:[]
const name297=x=>typeof x==='string'?x:(x?.title||x?.name||'Training')
const ex297=x=>typeof x==='string'?[]:(Array.isArray(x?.exercises)?x.exercises:[])
const isSmart297=p=>p?.smart===true||/^smart plan/i.test(String(p?.name||''))
const matchSession297=(w,s,p)=>{const wn=norm297(w?.session||w?.sessionName||w?.workout||w?.name),sn=norm297(name297(s));return !!sn&&(wn===sn||wn.includes(sn)||sn.includes(wn))||(w?.planId&&p?.id&&w.planId===p.id)}
const feedback297=()=>{const f=r297('ft-weekly-feedback-v281',{});return f?.feedback||f?.ratings||f?.muscles||f||{}}
const feedbackHint297=()=>{const f=feedback297(),vals=Object.values(f).map(v=>typeof v==='object'?(v.value||v.status||v.rating):v);const low=vals.filter(v=>/wenig|low|under/i.test(String(v))).length,high=vals.filter(v=>/viel|high|over/i.test(String(v))).length;if(high)return`${high} Muskelgruppe${high>1?'n':''} zuletzt stark belastet`;if(low)return`${low} Muskelgruppe${low>1?'n':''} braucht mehr Reiz`;return'Wochenfeedback berücksichtigt'}
const estimate297=s=>{const xs=ex297(s),sets=xs.reduce((a,x)=>a+(Number(x?.sets)||3),0);return Math.max(15,Math.round((sets*2.4+xs.length*1.5)/5)*5)}
const pick297=()=>{const ps=plans297();if(!ps.length)return null;const p=[...ps].reverse().find(isSmart297)||ps.at(-1),ss=sessions297(p);if(!ss.length)return{plan:p,session:null,index:0};const all=done297(),relevant=all.filter(w=>(p.id&&w.planId===p.id)||(p.name&&(w.plan===p.name||w.planName===p.name))||ss.some(s=>matchSession297(w,s,p))).sort((a,b)=>(Number(b.date)||0)-(Number(a.date)||0));let idx=0;if(relevant.length){const last=relevant[0],found=ss.findIndex(s=>matchSession297(last,s,p));if(found>=0)idx=(found+1)%ss.length;else idx=relevant.length%ss.length}return{plan:p,session:ss[idx],index:idx}}
const render297=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const welcome=document.querySelector('.welcome');if(!welcome)return;const pick=pick297();if(!pick)return;const {plan,session,index}=pick,xs=ex297(session),title=session?name297(session):(plan.name||'Smart Training'),mins=estimate297(session),last=done297().slice().sort((a,b)=>(b.date||0)-(a.date||0))[0],smart=isSmart297(plan),sig=`${plan.id||plan.name}|${title}|${done297().length}|${JSON.stringify(feedback297())}`;let box=document.querySelector('.smart-today-v297');if(!box){box=document.createElement('section');box.className='smart-today-v297';welcome.insertAdjacentElement('afterend',box)}if(box.dataset.sig===sig)return;box.dataset.sig=sig;box.innerHTML=`<div class="smart-today-top-v297"><div><small>${smart?'SMART TRAINER · HEUTE':'HEUTE TRAINIEREN'}</small><h2>${esc297(title)}</h2><p>${esc297(plan.name||'Aktueller Plan')}${sessions297(plan).length?` · Einheit ${index+1}/${sessions297(plan).length}`:''}</p></div><span class="smart-ready-v297">BEREIT</span></div><div class="smart-facts-v297"><div><b>${xs.length||'–'}</b><span>Übungen</span></div><div><b>~${mins}</b><span>Minuten</span></div><div><b>${xs.reduce((a,x)=>a+(Number(x?.sets)||3),0)||'–'}</b><span>Sätze</span></div></div><div class="smart-reason-v297"><strong>WARUM DIESE EINHEIT?</strong><span>${last?`Folgt auf dein letztes Training vom ${new Date(last.date).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}. `:''}${esc297(feedbackHint297())}.</span></div>${xs.length?`<div class="smart-preview-v297">${xs.slice(0,4).map(x=>`<span>${esc297(x.name||x.title||'Übung')}</span>`).join('')}${xs.length>4?`<span>+${xs.length-4} weitere</span>`:''}</div>`:''}<button type="button" class="smart-start-v297">${smart?'Smart Training starten':'Training starten'}</button>`;box.querySelector('.smart-start-v297').onclick=()=>{const start=window.FitTogetherStartNormalTraining;if(xs.length&&typeof start==='function'){start(xs);return}document.querySelector('.today')?.click()||document.querySelector('.start-strip')?.click()}}
let q297=false
const run297=()=>{if(q297||document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;q297=true;requestAnimationFrame(()=>{q297=false;render297()})}
const relevant297=node=>node?.nodeType===1&&(node.matches?.('.welcome,.smart-today-v297,.page')||node.querySelector?.('.welcome,.smart-today-v297'))
if(typeof document!=='undefined'){
  const start=()=>{run297();new MutationObserver(m=>{if(m.some(x=>[...x.addedNodes,...x.removedNodes].some(relevant297)))run297()}).observe(document.body,{childList:true,subtree:true});window.addEventListener('pageshow',run297);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')run297()})}
  document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})
}
