// FitTogether V2.0.98: recovery + muscle load status. No training-engine changes.
const r298=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const norm298=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const groups298=['Brust','Rücken','Beine','Schultern','Bizeps','Trizeps','Bauch','Gesäß','Waden']
const muscle298=(name,raw='')=>{const s=`${name||''} ${raw||''}`.toLowerCase();if(/chest|pector|brust|bench|fly|push.?up|liegestütz/.test(s))return'Brust';if(/lat|back|rücken|row|rudern|pull.?up|klimm|deadlift|kreuzheben/.test(s))return'Rücken';if(/quad|hamstring|thigh|leg|beine|squat|kniebeuge|lunge|ausfallschritt/.test(s))return'Beine';if(/delt|shoulder|schulter|overhead|seitheben/.test(s))return'Schultern';if(/biceps|bizeps|curl/.test(s))return'Bizeps';if(/triceps|trizeps|extension|pushdown|dip/.test(s))return'Trizeps';if(/abs|abdom|core|bauch|crunch|plank/.test(s))return'Bauch';if(/glute|gesäß|hip thrust/.test(s))return'Gesäß';if(/calf|wade/.test(s))return'Waden';return''}
const map298=()=>{const m=new Map();for(const p of r298('ft-plans',[]))for(const ss of p?.sessions||[]){if(typeof ss==='string')continue;for(const x of ss?.exercises||[]){const k=norm298(x?.name);if(k)m.set(k,muscle298(x?.name,`${x?.muscle||''} ${x?.query||''}`))}}return m}
const calc298=()=>{const now=Date.now(),m=map298(),out=Object.fromEntries(groups298.map(g=>[g,{score:0,sets:0,last:0}]));for(const w of r298('ft-completed-workouts',[])){const date=Number(w?.date)||0,age=(now-date)/3600000;if(age>120||!Array.isArray(w?.sets))continue;for(const s of w.sets){const g=m.get(norm298(s?.exercise))||muscle298(s?.exercise);if(!g)continue;const rir=s?.rir==='4+'?4:Number(s?.rir),intensity=rir<=1?1.25:rir>=4?.75:1,decay=Math.max(0,1-age/96);out[g].score+=intensity*decay;out[g].sets++;out[g].last=Math.max(out[g].last,date)}}return out}
const state298=x=>x.score>=4.5?['Stark belastet','high']:x.score>=1.8?['Mittel belastet','mid']:['Erholt','ready']
const render298=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const anchor=document.querySelector('.smart-today-v297')||document.querySelector('.home-v296');if(!anchor)return;let box=document.querySelector('.recovery-v298');if(!box){box=document.createElement('section');box.className='recovery-v298';anchor.insertAdjacentElement('afterend',box)}const data=calc298(),sig=groups298.map(g=>`${g}:${data[g].score.toFixed(2)}:${data[g].last}`).join('|');if(box.dataset.sig===sig)return;box.dataset.sig=sig;const strong=groups298.filter(g=>state298(data[g])[1]==='high').length;box.innerHTML=`<div class="recovery-head-v298"><div><small>REGENERATION</small><h3>Muskelbelastung</h3></div><span>${strong?strong+' stark belastet':'Bereit fürs Training'}</span></div><div class="recovery-grid-v298">${groups298.map(g=>{const [label,cls]=state298(data[g]),hours=data[g].last?Math.floor((Date.now()-data[g].last)/3600000):null;return`<div class="${cls}"><b>${g}</b><span>${label}</span><i>${hours==null?'keine Belastung':hours<24?'heute':hours<48?'gestern':Math.floor(hours/24)+' Tage her'}</i></div>`}).join('')}</div><p>Berechnet aus deinen letzten Sätzen, RIR und der Zeit seit dem Training.</p>`}
let q298=false;const run298=()=>{if(q298)return;q298=true;requestAnimationFrame(()=>{q298=false;render298()})};if(typeof document!=='undefined'){const start=()=>{run298();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))run298()}).observe(document.body,{childList:true,subtree:true});setInterval(run298,60000)};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
