// FitTogether V2.0.99: recovery-aware Smart Trainer decisions. No training-engine changes.
const r299=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const n299=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const esc299=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const muscle299=(name,raw='')=>{const s=`${name||''} ${raw||''}`.toLowerCase();if(/chest|pector|brust|bench|fly|push.?up|liegestütz/.test(s))return'Brust';if(/lat|back|rücken|row|rudern|pull.?up|klimm|deadlift|kreuzheben/.test(s))return'Rücken';if(/quad|hamstring|thigh|leg|beine|squat|kniebeuge|lunge|ausfallschritt/.test(s))return'Beine';if(/delt|shoulder|schulter|overhead|seitheben/.test(s))return'Schultern';if(/biceps|bizeps|curl/.test(s))return'Bizeps';if(/triceps|trizeps|extension|pushdown|dip/.test(s))return'Trizeps';if(/abs|abdom|core|bauch|crunch|plank/.test(s))return'Bauch';if(/glute|gesäß|hip thrust/.test(s))return'Gesäß';if(/calf|wade/.test(s))return'Waden';return''}
const groups299=['Brust','Rücken','Beine','Schultern','Bizeps','Trizeps','Bauch','Gesäß','Waden']
const planMap299=()=>{const m=new Map();for(const p of r299('ft-plans',[]))for(const ss of p?.sessions||[]){if(typeof ss==='string')continue;for(const x of ss?.exercises||[]){const k=n299(x?.name);if(k)m.set(k,muscle299(x?.name,`${x?.muscle||''} ${x?.query||''}`))}}return m}
const recovery299=()=>{const now=Date.now(),m=planMap299(),out=Object.fromEntries(groups299.map(g=>[g,{score:0,last:0}]));for(const w of r299('ft-completed-workouts',[])){const date=Number(w?.date)||0,age=(now-date)/3600000;if(age>120||!Array.isArray(w?.sets))continue;for(const s of w.sets){const g=m.get(n299(s?.exercise))||muscle299(s?.exercise);if(!g)continue;const rir=s?.rir==='4+'?4:Number(s?.rir),intensity=rir<=1?1.25:rir>=4?.75:1,decay=Math.max(0,1-age/96);out[g].score+=intensity*decay;out[g].last=Math.max(out[g].last,date)}}return out}
const sessions299=p=>Array.isArray(p?.sessions)?p.sessions:Array.isArray(p?.workouts)?p.workouts:Array.isArray(p?.days)?p.days:[]
const ex299=s=>typeof s==='string'?[]:(Array.isArray(s?.exercises)?s.exercises:[])
const name299=s=>typeof s==='string'?s:(s?.title||s?.name||'Training')
const musclesOf299=s=>[...new Set(ex299(s).map(x=>muscle299(x?.name,`${x?.muscle||''} ${x?.query||''}`)).filter(Boolean))]
const burden299=(s,r)=>{const ms=musclesOf299(s);if(!ms.length)return 0;return ms.reduce((a,g)=>a+(r[g]?.score||0),0)/ms.length}
const normalIndex299=(p,ss)=>{const all=r299('ft-completed-workouts',[]).filter(Boolean).sort((a,b)=>(Number(b.date)||0)-(Number(a.date)||0));if(!all.length)return 0;const last=all.find(w=>ss.some(s=>{const wn=n299(w?.session||w?.sessionName||w?.workout||w?.name),sn=n299(name299(s));return wn&&sn&&(wn===sn||wn.includes(sn)||sn.includes(wn))||(w?.planId&&p?.id&&w.planId===p.id)}));if(!last)return all.length%ss.length;const i=ss.findIndex(s=>{const wn=n299(last?.session||last?.sessionName||last?.workout||last?.name),sn=n299(name299(s));return wn&&sn&&(wn===sn||wn.includes(sn)||sn.includes(wn))});return i>=0?(i+1)%ss.length:all.length%ss.length}
const decision299=()=>{const ps=r299('ft-plans',[]).filter(Boolean);if(!ps.length)return null;const p=[...ps].reverse().find(x=>x?.smart===true||/^smart plan/i.test(String(x?.name||'')))||ps.at(-1),ss=sessions299(p);if(ss.length<2)return null;const r=recovery299(),normal=normalIndex299(p,ss),scores=ss.map((s,i)=>({i,s,b:burden299(s,r),muscles:musclesOf299(s)})),planned=scores[normal],alts=scores.filter(x=>x.i!==normal).sort((a,b)=>a.b-b.b),best=alts[0];if(!best)return null;const plannedHigh=planned.muscles.filter(g=>(r[g]?.score||0)>=4.5);const shouldSwitch=plannedHigh.length>0&&best.b+1.25<planned.b;return{plan:p,planned,best,chosen:shouldSwitch?best:planned,switched:shouldSwitch,high:plannedHigh,recovery:r}}
const render299=()=>{if(document.querySelector('.active-training,.rest-overlay,.free-workout-v247'))return;const card=document.querySelector('.smart-today-v297');if(!card)return;const d=decision299();if(!d)return;const sig=`${d.chosen.i}|${d.switched}|${d.chosen.b.toFixed(2)}|${r299('ft-completed-workouts',[]).length}`;if(card.dataset.recoverySig===sig)return;card.dataset.recoverySig=sig;const s=d.chosen.s,xs=ex299(s),title=name299(s),oldTitle=card.querySelector('h2'),oldMeta=card.querySelector('.smart-today-top-v297 p'),ready=card.querySelector('.smart-ready-v297'),reason=card.querySelector('.smart-reason-v297 span'),preview=card.querySelector('.smart-preview-v297'),facts=card.querySelectorAll('.smart-facts-v297 b');if(oldTitle)oldTitle.textContent=title;if(oldMeta)oldMeta.textContent=`${d.plan.name||'Smart Plan'} · Einheit ${d.chosen.i+1}/${sessions299(d.plan).length}`;if(ready){ready.textContent=d.switched?'ANGEPASST':'BEREIT';ready.classList.toggle('recovery-adjusted-v299',d.switched)}if(reason)reason.innerHTML=d.switched?`<b>Regeneration berücksichtigt:</b> ${esc299(d.high.join(', '))} ${d.high.length===1?'ist':'sind'} noch stark belastet. Deshalb heute <b>${esc299(title)}</b> statt ${esc299(name299(d.planned.s))}.`:`Deine geplante Einheit passt zur aktuellen Regeneration. Keine Verschiebung nötig.`;if(preview)preview.innerHTML=xs.slice(0,4).map(x=>`<span>${esc299(x.name||x.title||'Übung')}</span>`).join('')+(xs.length>4?`<span>+${xs.length-4} weitere</span>`:'');if(facts.length>=3){facts[0].textContent=xs.length||'–';const sets=xs.reduce((a,x)=>a+(Number(x?.sets)||3),0);facts[1].textContent=`~${Math.max(15,Math.round((sets*2.4+xs.length*1.5)/5)*5)}`;facts[2].textContent=sets||'–'}const btn=card.querySelector('.smart-start-v297');if(btn){btn.textContent=d.switched?'Empfohlenes Training starten':'Smart Training starten';btn.onclick=()=>{const start=window.FitTogetherStartNormalTraining;if(xs.length&&typeof start==='function')start(xs)}}}
let q299=false;const run299=()=>{if(q299)return;q299=true;requestAnimationFrame(()=>{q299=false;render299()})};if(typeof document!=='undefined'){const start=()=>{run299();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length||x.removedNodes.length))run299()}).observe(document.body,{childList:true,subtree:true});setInterval(run299,60000)};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
