// FitTogether V2.0.115: Smart Plan warm-ups follow the central equipment profile.
const r300=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const w300=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const equipment300=()=>{const saved=r300('ft-equipment-profile',null)?.equipment||r300('ft-available-equipment-v238',null)||{};return{bodyweight:saved.bodyweight!==false,dumbbell:saved.dumbbell??r300('ft-dumbbell-weights',[]).length>0,barbell:saved.barbell??r300('ft-barbell-weights',[]).length>0,band:!!saved.band,machine:!!saved.machine,treadmill:!!saved.treadmill,bike:!!saved.bike,rower:!!saved.rower}}
const lower300=s=>/beine|unterkörper|leg|lower/i.test(String(s||''))
const ownedFor300=(x,e)=>{const t=`${x?.equipment||''} ${x?.query||''} ${x?.name||''}`.toLowerCase();if(/dumbbell|kurzhantel/.test(t))return e.dumbbell;if(/barbell|langhantel|sz/.test(t))return e.barbell;if(/band|widerstandsband/.test(t))return e.band;if(/cable|machine|smith|maschine|kabel|multipresse/.test(t))return e.machine;if(/treadmill|laufband/.test(t))return e.treadmill;if(/bike|cycle|cycling|ergometer|fahrrad/.test(t))return e.bike;if(/rower|rowing|ruder/.test(t))return e.rower;if(/body|körpergewicht|push.?up|plank|squat|lunge/.test(t))return e.bodyweight;return false}
const cardioWarmup300=(split,e)=>{if(lower300(split)&&e.bike)return{name:'Fahrrad / Ergometer locker',query:'stationary bike',sets:1,reps:'4–5 Min.',warmup:true,equipment:'bike',noWeight:true};if(e.rower)return{name:'Rudergerät locker',query:'rowing machine',sets:1,reps:'4–5 Min.',warmup:true,equipment:'rower',noWeight:true};if(e.bike)return{name:'Fahrrad / Ergometer locker',query:'stationary bike',sets:1,reps:'4–5 Min.',warmup:true,equipment:'bike',noWeight:true};if(e.treadmill)return{name:'Laufband locker',query:'treadmill',sets:1,reps:'4–5 Min.',warmup:true,equipment:'treadmill',noWeight:true};return lower300(split)?{name:'World-Greatest-Stretch',query:'world greatest stretch',sets:1,reps:'6–8 je Seite',warmup:true,noWeight:true}:{name:'Brust- & Schulterdehnung',query:'chest and front of shoulder stretch',sets:1,reps:'20–30 Sek.',warmup:true,noWeight:true}}
const specificWarmup300=(first,e)=>{if(!first||!ownedFor300(first,e))return null;const t=`${first?.equipment||''} ${first?.query||''} ${first?.name||''}`.toLowerCase();if(/body|körpergewicht/.test(t))return null;return{...first,name:`Aufwärmsatz · ${String(first.name||'erste Übung').replace(/^Aufwärmsatz · /,'')}`,sets:1,reps:'10–12 leicht',warmup:true}}
const warmups300=(session,e)=>{const xs=Array.isArray(session?.exercises)?session.exercises:[],main=xs.filter(x=>!x?.warmup),general=cardioWarmup300(session?.title||session?.name,e),specific=specificWarmup300(main[0],e),out=[general];if(specific)out.push(specific);else if(!lower300(session?.title||session?.name)&&e.band)out.push({name:'Band Pull-Apart',query:'band pull apart',sets:1,reps:'12–15',warmup:true,equipment:'band',noWeight:true});return[...out,...main]}
const adaptPlans300=()=>{const plans=r300('ft-plans',[]);if(!Array.isArray(plans)||!plans.length)return;const e=equipment300();let changed=false;const next=plans.map(p=>{if(!(p?.smart===true||/^smart plan/i.test(String(p?.name||'')))||!Array.isArray(p?.sessions))return p;const sessions=p.sessions.map(s=>{if(typeof s==='string'||!Array.isArray(s?.exercises))return s;const exercises=warmups300(s,e);if(JSON.stringify(exercises)===JSON.stringify(s.exercises))return s;changed=true;return{...s,exercises}});return changed?{...p,sessions}:p});if(!changed)return;w300('ft-plans',next);try{window.FitTogetherCloud?.upload?.()}catch{}}
let queued300=false
const schedule300=()=>{if(queued300)return;queued300=true;setTimeout(()=>{queued300=false;adaptPlans300()},0)}
if(typeof document!=='undefined'){
  const start=()=>{adaptPlans300();document.addEventListener('click',e=>{const el=e.target?.closest?.('button');if(!el)return;const text=String(el.textContent||'');if(/Plan speichern/i.test(text)||el.matches?.('[data-equipment]'))schedule300()},false);window.addEventListener('pageshow',schedule300)}
  document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})
}
