// FitTogether V2.0.118: session-specific Smart Plan warm-ups using the central equipment profile.
const r300=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const w300=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const equipment300=()=>{const saved=r300('ft-equipment-profile',null)?.equipment||r300('ft-available-equipment-v238',null)||{};return{bodyweight:saved.bodyweight!==false,dumbbell:saved.dumbbell??r300('ft-dumbbell-weights',[]).length>0,barbell:saved.barbell??r300('ft-barbell-weights',[]).length>0,band:!!saved.band,machine:!!saved.machine,treadmill:!!saved.treadmill,bike:!!saved.bike,rower:!!saved.rower}}
const text300=x=>`${x?.title||''} ${x?.name||''} ${x?.query||''} ${x?.muscle||''} ${x?.equipment||''}`.toLowerCase()
const focus300=session=>{const t=text300(session),first=(session?.exercises||[]).find(x=>!x?.warmup),f=text300(first);if(/beine|unterkörper|leg|quad|hamstring|glute|calf|squat|kniebeuge|lunge/.test(t+' '+f))return'legs';if(/pull|rücken|back|lat|row|rudern|biceps|bizeps/.test(t+' '+f))return'pull';if(/push|brust|chest|pector|shoulder|schulter|triceps|trizeps|bench|press/.test(t+' '+f))return'push';return'full'}
const ownedFor300=(x,e)=>{const t=text300(x);if(/dumbbell|kurzhantel/.test(t))return e.dumbbell;if(/barbell|langhantel|sz/.test(t))return e.barbell;if(/band|widerstandsband/.test(t))return e.band;if(/cable|machine|smith|maschine|kabel|multipresse/.test(t))return e.machine;if(/treadmill|laufband/.test(t))return e.treadmill;if(/bike|cycle|cycling|ergometer|fahrrad/.test(t))return e.bike;if(/rower|rowing|ruder/.test(t))return e.rower;if(/body|körpergewicht|push.?up|plank|squat|lunge/.test(t))return e.bodyweight;return false}
const cardio300=(type,e)=>{const mk=(name,query,equipment)=>({name,query,sets:1,reps:'4–5 Min. locker',warmup:true,equipment,noWeight:true});if(type==='legs'){if(e.bike)return mk('Fahrrad / Ergometer locker','stationary bike','bike');if(e.treadmill)return mk('Laufband locker','treadmill','treadmill');if(e.rower)return mk('Rudergerät locker','rowing machine','rower')}if(type==='pull'){if(e.rower)return mk('Rudergerät locker','rowing machine','rower');if(e.bike)return mk('Fahrrad / Ergometer locker','stationary bike','bike');if(e.treadmill)return mk('Laufband locker','treadmill','treadmill')}if(type==='push'){if(e.bike)return mk('Fahrrad / Ergometer locker','stationary bike','bike');if(e.treadmill)return mk('Laufband locker','treadmill','treadmill');if(e.rower)return mk('Rudergerät sehr locker','rowing machine','rower')}if(e.rower)return mk('Rudergerät locker','rowing machine','rower');if(e.bike)return mk('Fahrrad / Ergometer locker','stationary bike','bike');if(e.treadmill)return mk('Laufband locker','treadmill','treadmill');return null}
const mobility300=type=>type==='legs'?{name:'World-Greatest-Stretch',query:'world greatest stretch',sets:1,reps:'6–8 je Seite',warmup:true,noWeight:true}:type==='pull'?{name:'Hintere Schulterdehnung',query:'rear deltoid stretch',sets:1,reps:'20–30 Sek.',warmup:true,noWeight:true}:{name:'Brust- & Schulterdehnung',query:'chest and front of shoulder stretch',sets:1,reps:'20–30 Sek.',warmup:true,noWeight:true}
const activation300=(type,e)=>{if(type==='pull'&&e.band)return{name:'Band Pull-Apart',query:'band pull apart',sets:1,reps:'12–15 kontrolliert',warmup:true,equipment:'band',noWeight:true};if(type==='push'&&e.band)return{name:'Band-Schulteraktivierung',query:'band shoulder external rotation',sets:1,reps:'10–12 je Seite',warmup:true,equipment:'band',noWeight:true};if(type==='legs'&&e.bodyweight)return{name:'Kniebeugen ohne Gewicht',query:'bodyweight squat',sets:1,reps:'10–12 locker',warmup:true,equipment:'bodyweight',noWeight:true};return null}
const specificWarmup300=(first,e)=>{if(!first||!ownedFor300(first,e))return null;const t=text300(first);if(/body|körpergewicht/.test(t))return null;return{...first,name:`Aufwärmsatz · ${String(first.name||'erste Übung').replace(/^Aufwärmsatz · /,'')}`,sets:1,reps:'8–10 sehr leicht',warmup:true}}
const warmups300=(session,e)=>{const xs=Array.isArray(session?.exercises)?session.exercises:[],main=xs.filter(x=>!x?.warmup),type=focus300({...session,exercises:main}),out=[],cardio=cardio300(type,e),mobility=mobility300(type),activation=activation300(type,e),specific=specificWarmup300(main[0],e);if(cardio)out.push(cardio);out.push(mobility);if(activation)out.push(activation);if(specific)out.push(specific);return[...out,...main]}
const adaptPlans300=()=>{const plans=r300('ft-plans',[]);if(!Array.isArray(plans)||!plans.length)return;const e=equipment300();let changed=false;const next=plans.map(p=>{if(!(p?.smart===true||/^smart plan/i.test(String(p?.name||'')))||!Array.isArray(p?.sessions))return p;let planChanged=false;const sessions=p.sessions.map(s=>{if(typeof s==='string'||!Array.isArray(s?.exercises))return s;const exercises=warmups300(s,e);if(JSON.stringify(exercises)===JSON.stringify(s.exercises))return s;changed=true;planChanged=true;return{...s,exercises}});return planChanged?{...p,sessions}:p});if(!changed)return;w300('ft-plans',next);try{window.FitTogetherCloud?.upload?.()}catch{}}
let queued300=false
const schedule300=()=>{if(queued300)return;queued300=true;setTimeout(()=>{queued300=false;adaptPlans300()},0)}
if(typeof document!=='undefined'){
  const start=()=>{adaptPlans300();document.addEventListener('click',e=>{const el=e.target?.closest?.('button');if(!el)return;const text=String(el.textContent||'');if(/Plan speichern/i.test(text)||el.matches?.('[data-equipment]'))schedule300()},false);window.addEventListener('pageshow',schedule300)}
  document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})
}
