// FitTogether V2.0.136: connect Smart Coach to per-exercise strength progress.
const read309=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const num309=v=>{const n=Number(v);return Number.isFinite(n)?n:0}
const esc309=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm309=v=>String(v||'').toLocaleLowerCase('de-DE').replace(/[^a-z0-9äöüß]+/g,' ').trim()
const cardio309=s=>s?.kind==='cardio'||s?.loadType==='cardio'
const strengthRows309=()=>{const rows=[];read309('ft-completed-workouts',[]).forEach((w,wi)=>{const date=num309(w?.date);(Array.isArray(w?.sets)?w.sets:[]).forEach(s=>{const name=String(s?.exercise||'').trim();if(!name||cardio309(s))return;rows.push({wi,date,name,key:norm309(name),reps:num309(s?.actualReps??s?.reps??s?.plannedReps),weight:num309(s?.actualWeight??s?.weight??s?.plannedWeight),extra:num309(s?.actualExtraWeight??s?.extraWeight??s?.plannedExtraWeight)})})});return rows}
const sessions309=(rows,key)=>{const map=new Map();rows.filter(r=>r.key===key).forEach(r=>{const id=`${r.wi}|${r.date}`;if(!map.has(id))map.set(id,{date:r.date,sets:[]});map.get(id).sets.push(r)});return[...map.values()].sort((a,b)=>a.date-b.date).map(x=>{const weighted=x.sets.filter(s=>s.weight>0||s.extra>0),maxLoad=weighted.length?Math.max(...weighted.map(s=>s.weight+s.extra)):0,maxReps=Math.max(0,...x.sets.map(s=>s.reps)),atMax=weighted.filter(s=>s.weight+s.extra===maxLoad),repsAtLoad=Math.max(0,...atMax.map(s=>s.reps));return{...x,maxLoad,maxReps,repsAtLoad}})}
const compare309=s=>{const last=s.at(-1),prev=s.at(-2);if(!last||!prev)return{state:'new',text:'Noch wenig Vergleichsdaten'};if(last.maxLoad>prev.maxLoad)return{state:'up',text:`+${(last.maxLoad-prev.maxLoad).toLocaleString('de-DE',{maximumFractionDigits:1})} kg`};if(last.maxLoad<prev.maxLoad)return{state:'down',text:'Letztes Mal leichter'};const a=last.maxLoad>0?last.repsAtLoad:last.maxReps,b=prev.maxLoad>0?prev.repsAtLoad:prev.maxReps;if(a>b)return{state:'up',text:`+${a-b} Wdh.`};if(a<b)return{state:'down',text:`${a-b} Wdh.`};if(s.length>=3){const p2=s.at(-3),a2=p2?.maxLoad===last.maxLoad?(last.maxLoad>0?p2.repsAtLoad:p2.maxReps):null;if(a2!=null&&a2===a)return{state:'stalled',text:'3 Einheiten stabil'}}return{state:'stable',text:'Leistung stabil'}}
const currentExercises309=box=>{const chips=[...box.querySelectorAll('.smart-preview-v297 span')].map(x=>x.textContent?.trim()).filter(Boolean).filter(x=>!/^\+\d+ weitere$/i.test(x));return chips}
const render309=()=>{const box=document.querySelector('.smart-today-v297');if(!box||document.querySelector('.active-training,.rest-overlay,.training-overlay'))return;const names=currentExercises309(box);if(!names.length){box.querySelector('.smart-progress-v309')?.remove();return}const rows=strengthRows309(),items=names.map(name=>{const s=sessions309(rows,norm309(name)),cmp=compare309(s);return{name,cmp,count:s.length}}).filter(x=>x.count>0);if(!items.length){box.querySelector('.smart-progress-v309')?.remove();return}const up=items.filter(x=>x.cmp.state==='up').length,stalled=items.filter(x=>x.cmp.state==='stalled').length,down=items.filter(x=>x.cmp.state==='down').length,stable=items.length-up-stalled-down;const sig=items.map(x=>`${x.name}:${x.cmp.state}:${x.cmp.text}:${x.count}`).join('|');let panel=box.querySelector('.smart-progress-v309');if(!panel){panel=document.createElement('div');panel.className='smart-progress-v309';const reason=box.querySelector('.smart-reason-v297');reason?.insertAdjacentElement('afterend',panel)||box.querySelector('.smart-preview-v297')?.insertAdjacentElement('beforebegin',panel)||box.appendChild(panel)}if(panel.dataset.sig===sig)return;panel.dataset.sig=sig;let headline='Leistung im Blick';let message='Die letzten Einheiten sind überwiegend stabil.';if(up)message=`${up} Übung${up>1?'en':''} zeigt${up>1?'en':''} Fortschritt – gute Basis für weitere Steigerungen.`;else if(stalled)message=`${stalled} Übung${stalled>1?'en':''} stagniert${stalled>1?'en':''} über mehrere Einheiten – hier lohnt sich eine kleine Anpassung.`;else if(down)message='Ein Teil der Leistung lag zuletzt niedriger. Erst Erholung und RIR beobachten, bevor Gewicht erhöht wird.';panel.innerHTML=`<div class="smart-progress-head-v309"><div><small>SMART COACH · FORTSCHRITT</small><strong>${headline}</strong></div><div class="smart-progress-badges-v309">${up?`<span class="up">↑ ${up}</span>`:''}${stalled?`<span class="warn">• ${stalled}</span>`:''}${stable?`<span>${stable}</span>`:''}</div></div><p>${esc309(message)}</p><div class="smart-progress-list-v309">${items.slice(0,3).map(x=>`<div class="${x.cmp.state}"><span>${esc309(x.name)}</span><b>${esc309(x.cmp.text)}</b></div>`).join('')}</div>`}
}
let q309=false
const schedule309=()=>{if(q309)return;q309=true;requestAnimationFrame(()=>{q309=false;render309()})}
if(typeof document!=='undefined'){const start=()=>{render309();new MutationObserver(schedule309).observe(document.body,{childList:true,subtree:true});window.addEventListener('pageshow',schedule309);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule309()})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
