// FitTogether V2.0.138: compact weekly review with progress, workload and next-week focus.
const read310=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const num310=v=>{const n=Number(v);return Number.isFinite(n)?n:0}
const maybe310=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
const esc310=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm310=v=>String(v||'').toLocaleLowerCase('de-DE').replace(/[^a-z0-9äöüß]+/g,' ').trim()
const day310=86400000
const statsPage310=()=>[...document.querySelectorAll('.page')].find(p=>p.querySelector('.page-head h1')?.textContent?.includes('Deine Statistik'))
const sets310=w=>Array.isArray(w?.sets)?w.sets:[]
const cardioSet310=s=>s?.kind==='cardio'||s?.loadType==='cardio'
const strengthSet310=s=>!cardioSet310(s)
const cardioSeconds310=w=>{const cardio=sets310(w).filter(cardioSet310);if(cardio.length)return cardio.reduce((sum,s)=>sum+(num310(s?.durationSeconds)||num310(s?.durationMinutes)*60),0);return w?.kind==='cardio'?(num310(w?.actualSeconds)||num310(w?.durationSeconds)):0}
const localDay310=t=>{const d=new Date(t);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const rows310=()=>{const out=[];read310('ft-completed-workouts',[]).forEach((w,wi)=>{const date=num310(w?.date);sets310(w).forEach(s=>{if(!strengthSet310(s))return;const name=String(s?.exercise||'').trim();if(!name)return;out.push({wi,date,name,key:norm310(name),reps:num310(s?.actualReps??s?.reps??s?.plannedReps),weight:num310(s?.actualWeight??s?.weight??s?.plannedWeight),extra:num310(s?.actualExtraWeight??s?.extraWeight??s?.plannedExtraWeight),rir:maybe310(s?.rir)})})});return out}
const sessions310=(rows,key)=>{const map=new Map();rows.filter(r=>r.key===key).forEach(r=>{const id=`${r.wi}|${r.date}`;if(!map.has(id))map.set(id,{date:r.date,sets:[]});map.get(id).sets.push(r)});return[...map.values()].sort((a,b)=>a.date-b.date).map(x=>{const weighted=x.sets.filter(s=>s.weight>0||s.extra>0),maxLoad=weighted.length?Math.max(...weighted.map(s=>s.weight+s.extra)):0,atMax=weighted.filter(s=>s.weight+s.extra===maxLoad),repsAtLoad=Math.max(0,...atMax.map(s=>s.reps)),maxReps=Math.max(0,...x.sets.map(s=>s.reps));return{...x,maxLoad,repsAtLoad,maxReps}})}
const value310=s=>s?(s.maxLoad>0?s.maxLoad*1000+(s.repsAtLoad||0):s.maxReps||0):0
const compare310=s=>{const last=s.at(-1),prev=s.at(-2);if(!last||!prev)return{state:'new',text:'Noch kein Vergleich'};if(last.maxLoad>prev.maxLoad)return{state:'up',text:`+${(last.maxLoad-prev.maxLoad).toLocaleString('de-DE',{maximumFractionDigits:1})} kg`};if(last.maxLoad<prev.maxLoad)return{state:'down',text:'Gewicht niedriger'};const a=last.maxLoad>0?last.repsAtLoad:last.maxReps,b=prev.maxLoad>0?prev.repsAtLoad:prev.maxReps;if(a>b)return{state:'up',text:`+${a-b} Wdh.`};if(a<b)return{state:'down',text:`${a-b} Wdh.`};if(s.length>=3){const third=s.at(-3);if(value310(third)===value310(prev)&&value310(prev)===value310(last))return{state:'stalled',text:'3 Einheiten gleich'}}return{state:'stable',text:'Stabil'}}
const muscle310=name=>{const s=String(name||'').toLowerCase();if(/chest|pector|brust|bench|fly|push.?up|liegestütz/.test(s))return'Brust';if(/lat|back|rücken|row|rudern|pull.?up|klimm|deadlift|kreuzheben/.test(s))return'Rücken';if(/quad|hamstring|thigh|leg|beine|squat|kniebeuge|lunge|ausfallschritt/.test(s))return'Beine';if(/delt|shoulder|schulter|overhead|seitheben/.test(s))return'Schultern';if(/biceps|bizeps|curl/.test(s))return'Bizeps';if(/triceps|trizeps|extension|pushdown|dip/.test(s))return'Trizeps';if(/abs|abdom|core|bauch|crunch|plank/.test(s))return'Bauch';if(/glute|gesäß|hip thrust/.test(s))return'Gesäß';if(/calf|wade/.test(s))return'Waden';return''}
const muscleFocus310=(weekWorkouts)=>{const groups=['Brust','Rücken','Beine','Schultern','Bizeps','Trizeps','Bauch','Gesäß','Waden'],score=Object.fromEntries(groups.map(g=>[g,{sets:0,load:0}])),saved=read310('ft-weekly-muscle-feedback',{});weekWorkouts.forEach(w=>sets310(w).forEach(s=>{if(!strengthSet310(s))return;const g=muscle310(s?.exercise);if(!g)return;const rir=s?.rir==='4+'?4:num310(s?.rir),factor=rir<=1?1.15:rir>=4?.85:1;score[g].sets++;score[g].load+=factor}));return groups.map(group=>{const x=score[group],assessment=saved?.[group]||(x.sets===0?'passt':x.load<5?'zu wenig':x.load>13?'zu viel':'passt');return{group,assessment,sets:x.sets}}).filter(x=>(x.sets>0||saved?.[x.group])&&x.assessment!=='passt')}
const renderList310=(title,items,empty)=>`<div class="weekly-block-v310"><small>${title}</small>${items.length?`<div class="weekly-list-v310">${items.map(x=>`<div class="${x.state||''}"><span>${esc310(x.name||x.title)}</span><b>${esc310(x.text||'')}</b></div>`).join('')}</div>`:`<p>${esc310(empty)}</p>`}</div>`
const enhance310=()=>{
  const stats=statsPage310(),hub=stats?.querySelector('.stats-hub-v306');if(!stats||!hub)return
  const now=Date.now(),weekStart=now-7*day310,prevStart=now-14*day310,all=read310('ft-completed-workouts',[]).filter(x=>num310(x?.date)>0),week=all.filter(x=>num310(x.date)>=weekStart),prev=all.filter(x=>num310(x.date)>=prevStart&&num310(x.date)<weekStart)
  const activeDays=new Set(week.map(x=>localDay310(num310(x.date)))).size,strengthSets=week.reduce((sum,w)=>sum+sets310(w).filter(strengthSet310).length,0),cardioMin=Math.round(week.reduce((sum,w)=>sum+cardioSeconds310(w),0)/60),prevCardio=Math.round(prev.reduce((sum,w)=>sum+cardioSeconds310(w),0)/60)
  const rows=rows310(),keys=[...new Set(rows.map(r=>r.key))],progress=keys.map(key=>{const s=sessions310(rows,key),last=s.at(-1);if(!last||last.date<weekStart)return null;const cmp=compare310(s),name=rows.find(r=>r.key===key)?.name||key;return{name,state:cmp.state,text:cmp.text,date:last.date}}).filter(Boolean)
  const improved=progress.filter(x=>x.state==='up').sort((a,b)=>b.date-a.date).slice(0,3),attention=progress.filter(x=>x.state==='stalled'||x.state==='down').sort((a,b)=>b.date-a.date).slice(0,3),stable=progress.filter(x=>x.state==='stable').length,focus=muscleFocus310(week)
  const next=[]
  if(attention.some(x=>x.state==='down'))next.push({title:'Leistung stabilisieren',text:`RIR/Erholung prüfen: ${attention.filter(x=>x.state==='down').slice(0,2).map(x=>x.name).join(' · ')}`})
  if(attention.some(x=>x.state==='stalled'))next.push({title:'Stagnation lösen',text:`+1 Wdh. oder Technik/RIR prüfen: ${attention.filter(x=>x.state==='stalled').slice(0,2).map(x=>x.name).join(' · ')}`})
  focus.slice(0,2).forEach(x=>next.push({title:x.group,text:x.assessment==='zu wenig'?'Mehr Reiz prüfen · +1 Satz im Smart Plan':'Belastung hoch · −1 Satz bzw. Erholung prüfen'}))
  if(!next.length&&improved.length)next.push({title:'Fortschritt bestätigen',text:`Nächste Woche sauber weiterführen: ${improved.slice(0,2).map(x=>x.name).join(' · ')}`})
  if(!next.length)next.push({title:'Plan beibehalten',text:'Aktuell keine größere Anpassung aus den letzten 7 Tagen nötig.'})
  let panel=hub.querySelector('.weekly-review-v310')
  if(!panel){panel=document.createElement('details');panel.className='stats-accordion-v306 weekly-review-v310';panel.innerHTML='<summary><span><small>WOCHENRÜCKBLICK</small><strong>Letzte 7 Tage</strong></span><b>›</b></summary><div class="stats-accordion-body-v306"></div>';const before=hub.querySelector('.training-stats-v307')||hub.querySelector('.training-history-wrap-v306');before?hub.insertBefore(panel,before):hub.appendChild(panel)}
  const sig=[week.length,prev.length,activeDays,strengthSets,cardioMin,improved.map(x=>x.name+x.text).join(','),attention.map(x=>x.name+x.text).join(','),focus.map(x=>x.group+x.assessment).join(',')].join('|')
  const body=panel.querySelector('.stats-accordion-body-v306');if(panel.dataset.signature!==sig){panel.dataset.signature=sig;panel.querySelector('summary strong').textContent=`Letzte 7 Tage · ${week.length} Training${week.length===1?'':'s'}`;const workoutDiff=week.length-prev.length,cardioDiff=cardioMin-prevCardio;body.innerHTML=`<div class="weekly-grid-v310"><div><small>TRAININGS</small><strong>${week.length}</strong><span>${workoutDiff===0?'wie zuvor':`${workoutDiff>0?'+':''}${workoutDiff} vs. vorige 7 Tage`}</span></div><div><small>AKTIVE TAGE</small><strong>${activeDays}</strong><span>mit Training</span></div><div><small>KRAFTSÄTZE</small><strong>${strengthSets}</strong><span>aufgezeichnet</span></div><div><small>CARDIO</small><strong>${cardioMin} Min.</strong><span>${cardioDiff===0?'wie zuvor':`${cardioDiff>0?'+':''}${cardioDiff} Min. vs. zuvor`}</span></div></div>${renderList310('FORTSCHRITT',improved,'Diese Woche noch kein klarer Leistungsanstieg erkannt.')}${renderList310('IM BLICK',attention,stable?`${stable} Übung${stable===1?'':'en'} stabil – keine Auffälligkeit.`:'Noch nicht genug Wiederholungsdaten für eine Bewertung.')}${renderList310('FOKUS NÄCHSTE WOCHE',next,'Aktuell keine Anpassung nötig.')}<div class="weekly-feedback-slot-v310"></div>`}
  const feedback=stats.querySelector('.weekly-muscle-v281'),slot=body.querySelector('.weekly-feedback-slot-v310');if(feedback&&slot&&feedback.parentElement!==slot)slot.appendChild(feedback)
}
let q310=false
const schedule310=()=>{if(q310||document.querySelector('.active-training,.rest-overlay,.training-overlay'))return;q310=true;requestAnimationFrame(()=>{q310=false;enhance310()})}
if(typeof document!=='undefined'){const start=()=>{enhance310();new MutationObserver(schedule310).observe(document.body,{childList:true,subtree:true});window.addEventListener('pageshow',schedule310);window.addEventListener('ft-stats-refresh',schedule310);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule310()})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
