// FitTogether V2.0.139: show one home reminder per calendar week until the weekly review is opened.
const read311=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const write311=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const weekKey311=()=>{const d=new Date(),x=new Date(d);x.setHours(0,0,0,0);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
const home311=()=>[...document.querySelectorAll('.page')].find(p=>p.querySelector('.welcome'))
const seen311=()=>read311('ft-weekly-review-seen-v311','')===weekKey311()
const markSeen311=()=>{write311('ft-weekly-review-seen-v311',weekKey311());document.querySelector('.weekly-review-reminder-v311')?.remove()}
const openStats311=()=>{const nav=[...document.querySelectorAll('button,a')].find(x=>/statistik/i.test((x.textContent||'').trim())&&!x.closest('.weekly-review-reminder-v311'));if(nav){nav.click();setTimeout(()=>{const review=document.querySelector('.weekly-review-v310');if(review){review.open=true;review.scrollIntoView({behavior:'smooth',block:'start'};markSeen311()}},180);return}window.dispatchEvent(new CustomEvent('ft-open-statistics'));setTimeout(()=>{const review=document.querySelector('.weekly-review-v310');if(review){review.open=true;review.scrollIntoView({behavior:'smooth',block:'start'};markSeen311()}},220)}
const bindReview311=()=>{const review=document.querySelector('.weekly-review-v310');if(!review||review.dataset.seenBind311)return;review.dataset.seenBind311='1';review.addEventListener('toggle',()=>{if(review.open)markSeen311()})}
const render311=()=>{bindReview311();const home=home311();if(!home||seen311()||document.querySelector('.active-training,.rest-overlay,.training-overlay,.rir-backdrop,.swap-backdrop')){document.querySelector('.weekly-review-reminder-v311')?.remove();return}let card=home.querySelector('.weekly-review-reminder-v311');if(card)return;card=document.createElement('button');card.type='button';card.className='weekly-review-reminder-v311';card.innerHTML='<span><small>NEUE WOCHE</small><strong>Dein Wochenrückblick ist bereit</strong><em>Fortschritt, Belastung und Fokus für die nächste Woche ansehen.</em></span><b>Öffnen ›</b>';card.onclick=openStats311;const anchor=home.querySelector('.smart-today-v297')||home.firstElementChild;anchor?.insertAdjacentElement('afterend',card)||home.appendChild(card)}
let q311=false
const schedule311=()=>{if(q311)return;q311=true;requestAnimationFrame(()=>{q311=false;render311()})}
if(typeof document!=='undefined'){const start=()=>{render311();new MutationObserver(schedule311).observe(document.body,{childList:true,subtree:true});window.addEventListener('pageshow',schedule311);window.addEventListener('ft-stats-refresh',schedule311);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule311()})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
