// FitTogether V2.0.146: scheduled training-day reminder settings.
const KEY315='ft-training-reminder-v315'
const LAST315='ft-training-reminder-last-v315'
const read315=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const write315=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const esc315=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const dayNames315=['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag']
const dayAbbr315=['So','Mo','Di','Mi','Do','Fr','Sa']
const normalizeDay315=v=>String(v||'').trim().toLowerCase().replace(/[.\s_-]+/g,'')
const dayMatches315=(v,d)=>{const n=normalizeDay315(v);if(!n)return false;const full=normalizeDay315(dayNames315[d]),short=normalizeDay315(dayAbbr315[d]);return n===full||n===short||n.startsWith(full)||n===full.slice(0,2)}
const todayPlan315=()=>{const plans=read315('ft-plans',[]),d=new Date().getDay();for(let pi=plans.length-1;pi>=0;pi--){const plan=plans[pi],sessions=Array.isArray(plan?.sessions)?plan.sessions:[];for(let si=0;si<sessions.length;si++){const s=sessions[si];if(!s||typeof s==='string')continue;const labels=[s.day,s.title,s.name,Array.isArray(plan?.weekdays)?plan.weekdays[si]:null];if(labels.some(v=>dayMatches315(v,d))&&(s.exercises||[]).length)return{plan,session:s,index:si}}}return null}
const cfg315=()=>{const c=read315(KEY315,{enabled:false,time:'18:00'});return{enabled:!!c.enabled,time:/^([01]\d|2[0-3]):[0-5]\d$/.test(c.time||'')?c.time:'18:00'}}
const saveCfg315=c=>{write315(KEY315,c);try{window.FitTogetherCloud?.upload?.()}catch{}}
const dateKey315=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const permission315=()=>typeof Notification==='undefined'?'unsupported':Notification.permission
const ensureSw315=async()=>{if(!('serviceWorker'in navigator))return null;try{return await navigator.serviceWorker.register('/ft-reminder-sw.js?v=146',{scope:'/'})}catch{return null}}
const requestPermission315=async()=>{if(typeof Notification==='undefined')return'unsupported';if(Notification.permission==='granted'){await ensureSw315();return'granted'}if(Notification.permission==='denied')return'denied';try{const p=await Notification.requestPermission();if(p==='granted')await ensureSw315();return p}catch{return'unsupported'}}
const notify315=async info=>{const reg=await ensureSw315();const title='Zeit fürs Training 💪';const planName=info?.plan?.name||'Dein Training';const sessionName=info?.session?.title||info?.session?.name||info?.session?.day||'';const body=sessionName?`${sessionName} · ${planName}`:`${planName} steht heute an.`;try{if(reg?.showNotification){await reg.showNotification(title,{body,icon:'/fittogether-icon-192.png?v=230',badge:'/fittogether-icon-192.png?v=230',tag:`ft-training-${dateKey315()}`,renotify:false,data:{url:'/?reminder=training'}});return true}if(typeof Notification!=='undefined'){new Notification(title,{body,icon:'/fittogether-icon-192.png?v=230',tag:`ft-training-${dateKey315()}`});return true}}catch{}return false}
let checking315=false
const checkReminder315=async()=>{if(checking315)return;checking315=true;try{const c=cfg315();if(!c.enabled||permission315()!=='granted')return;const info=todayPlan315();if(!info)return;const now=new Date(),[h,m]=c.time.split(':').map(Number),due=new Date(now);due.setHours(h,m,0,0);if(now<due)return;const key=dateKey315();if(read315(LAST315,'')===key)return;if(await notify315(info))write315(LAST315,key)}finally{checking315=false}}
const status315=()=>{const c=cfg315(),info=todayPlan315(),p=permission315();if(!c.enabled)return'Erinnerung ist aus';if(p==='denied')return'Mitteilungen sind auf diesem Gerät blockiert';if(p==='unsupported')return'Systemmitteilungen werden hier nicht unterstützt';if(p!=='granted')return'Mitteilungen noch nicht erlaubt';if(info)return`Heute geplant · Erinnerung ${c.time} Uhr`;return`Heute kein Training geplant · ${c.time} Uhr gespeichert`}
const mount315=()=>{const h1=[...document.querySelectorAll('.page-head h1,h1')].find(x=>x.textContent?.trim()==='Einstellungen');if(!h1)return;const page=h1.closest('.page')||h1.parentElement?.parentElement;if(!page||page.querySelector('.training-reminder-v315'))return;const list=page.querySelector('.settings-list');if(!list)return;const c=cfg315();const wrap=document.createElement('section');wrap.className='training-reminder-v315';wrap.innerHTML=`<div class="training-reminder-title-v315"><div><small>TRAININGSERINNERUNG</small><strong>An Trainingstagen erinnern</strong><p>Nur wenn für den jeweiligen Tag ein Training in deinem Plan steht.</p></div><button type="button" class="training-reminder-toggle-v315 ${c.enabled?'on':''}" aria-pressed="${c.enabled}"><i></i></button></div><div class="training-reminder-options-v315 ${c.enabled?'':'hidden'}"><label><span>Uhrzeit</span><input type="time" value="${esc315(c.time)}" step="300"></label><div class="training-reminder-status-v315"></div></div>`;list.after(wrap);const toggle=wrap.querySelector('.training-reminder-toggle-v315'),options=wrap.querySelector('.training-reminder-options-v315'),input=wrap.querySelector('input'),status=wrap.querySelector('.training-reminder-status-v315');const refresh=()=>{const cc=cfg315();toggle.classList.toggle('on',cc.enabled);toggle.setAttribute('aria-pressed',String(cc.enabled));options.classList.toggle('hidden',!cc.enabled);input.value=cc.time;status.textContent=status315()};toggle.onclick=async()=>{const cc=cfg315();if(!cc.enabled){const p=await requestPermission315();if(p==='denied'||p==='unsupported'){saveCfg315({...cc,enabled:false});refresh();return}saveCfg315({...cc,enabled:true})}else saveCfg315({...cc,enabled:false});refresh();checkReminder315()};input.onchange=()=>{const cc=cfg315();saveCfg315({...cc,time:input.value||'18:00'});write315(LAST315,'');refresh();checkReminder315()};refresh()}
if(typeof document!=='undefined'){
  const obs=new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length))requestAnimationFrame(()=>mount315())})
  const start=()=>{mount315();obs.observe(document.body,{childList:true,subtree:true});setInterval(checkReminder315,30000);window.addEventListener('pageshow',checkReminder315);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){mount315();checkReminder315()}});setTimeout(checkReminder315,1200)}
  document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})
}
