import { supabase, supabaseConfigured } from './lib/supabase.js'

// FitTogether V2.0.147: scheduled training-day reminders with background Web Push.
const KEY315='ft-training-reminder-v315'
const LAST315='ft-training-reminder-last-v315'
const REMOTE315='ft-training-push-remote-v315'
const DIGEST315='ft-training-push-digest-v315'
const VAPID_PUBLIC315='BBixbM-JEbk_ey2niJhsXxSNXp9nC6Cqkm0roHXOYzIIwRNRGiKKz3CIdnszXo_5lX18vC8T9gMV5hYpknsFjOY'
const read315=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const write315=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const esc315=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const dayNames315=['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag']
const dayAbbr315=['So','Mo','Di','Mi','Do','Fr','Sa']
const normalizeDay315=v=>String(v||'').trim().toLowerCase().replace(/[.\s_-]+/g,'')
const dayMatches315=(v,d)=>{const n=normalizeDay315(v);if(!n)return false;const full=normalizeDay315(dayNames315[d]),short=normalizeDay315(dayAbbr315[d]);return n===full||n===short||n.startsWith(full)||n===full.slice(0,2)}
const schedule315=()=>{const plans=read315('ft-plans',[]),days=new Set();let planName='';for(let pi=plans.length-1;pi>=0;pi--){const plan=plans[pi],sessions=Array.isArray(plan?.sessions)?plan.sessions:[];for(let si=0;si<sessions.length;si++){const s=sessions[si];if(!s||typeof s==='string'||!(s.exercises||[]).length)continue;const labels=[s.day,s.title,s.name,Array.isArray(plan?.weekdays)?plan.weekdays[si]:null];for(let d=0;d<7;d++){if(labels.some(v=>dayMatches315(v,d))){days.add(d);if(!planName)planName=plan?.name||'Trainingsplan'}}}}return{weekdays:[...days].sort((a,b)=>a-b),planName}}
const todayPlan315=()=>{const plans=read315('ft-plans',[]),d=new Date().getDay();for(let pi=plans.length-1;pi>=0;pi--){const plan=plans[pi],sessions=Array.isArray(plan?.sessions)?plan.sessions:[];for(let si=0;si<sessions.length;si++){const s=sessions[si];if(!s||typeof s==='string')continue;const labels=[s.day,s.title,s.name,Array.isArray(plan?.weekdays)?plan.weekdays[si]:null];if(labels.some(v=>dayMatches315(v,d))&&(s.exercises||[]).length)return{plan,session:s,index:si}}}return null}
const cfg315=()=>{const c=read315(KEY315,{enabled:false,time:'18:00'});return{enabled:!!c.enabled,time:/^([01]\d|2[0-3]):[0-5]\d$/.test(c.time||'')?c.time:'18:00'}}
const saveCfg315=c=>{write315(KEY315,c);try{window.FitTogetherCloud?.upload?.()}catch{}}
const dateKey315=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const permission315=()=>typeof Notification==='undefined'?'unsupported':Notification.permission
const isIOS315=()=>/iphone|ipad|ipod/i.test(navigator.userAgent||'')
const standalone315=()=>window.matchMedia?.('(display-mode: standalone)')?.matches||navigator.standalone===true
const pushSupported315=()=>typeof window!=='undefined'&&'serviceWorker'in navigator&&'PushManager'in window&&typeof Notification!=='undefined'
const remote315=()=>read315(REMOTE315,{status:'off',updatedAt:0,error:''})
const setRemote315=(status,error='')=>write315(REMOTE315,{status,updatedAt:Date.now(),error})
const remoteActive315=()=>remote315().status==='active'
const timezone315=()=>{try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Berlin'}catch{return'Europe/Berlin'}}
const ensureSw315=async()=>{if(!('serviceWorker'in navigator))return null;try{const reg=await navigator.serviceWorker.register('/ft-reminder-sw.js?v=147',{scope:'/'});try{await reg.update()}catch{}return reg}catch{return null}}
const b64ToBytes315=s=>{const p=String(s).replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(String(s).length/4)*4,'=');const raw=atob(p);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
const bytesToB64315=bytes=>{let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
const requestPermission315=async()=>{if(typeof Notification==='undefined')return'unsupported';if(isIOS315()&&!standalone315())return'install';if(Notification.permission==='granted')return'granted';if(Notification.permission==='denied')return'denied';try{return await Notification.requestPermission()}catch{return'unsupported'}}
const ensureSubscription315=async()=>{if(!pushSupported315())return null;const reg=await ensureSw315();if(!reg?.pushManager)return null;let sub=await reg.pushManager.getSubscription();if(sub?.options?.applicationServerKey){try{const bound=bytesToB64315(new Uint8Array(sub.options.applicationServerKey));if(bound!==VAPID_PUBLIC315){await sub.unsubscribe();sub=null}}catch{}}if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToBytes315(VAPID_PUBLIC315)});return sub}
const session315=async()=>{if(!supabaseConfigured||!supabase)return null;try{const {data}=await supabase.auth.getSession();return data?.session||null}catch{return null}}
const invoke315=async body=>{const session=await session315();if(!session)return{ok:false,code:'signin'};try{const {data,error}=await supabase.functions.invoke('training-push-register',{body});if(error)return{ok:false,code:'server',error:error.message||String(error)};return data?.ok?{ok:true,data}:{ok:false,code:'server',error:data?.error||'Unbekannter Fehler'}}catch(error){return{ok:false,code:'server',error:error?.message||String(error)}}}
const remotePayload315=subscription=>{const c=cfg315(),schedule=schedule315();return{action:'sync',enabled:c.enabled,time:c.time,timezone:timezone315(),weekdays:schedule.weekdays,planName:schedule.planName,subscription:subscription?.toJSON?.()||undefined}}
const syncRemote315=async(force=false)=>{const c=cfg315();if(!c.enabled)return false;if(!supabaseConfigured||!supabase){setRemote315('local','signin');return false}let sub=null;if(permission315()==='granted'&&pushSupported315()){try{sub=await ensureSubscription315()}catch{}}const payload=remotePayload315(sub),digest=JSON.stringify({enabled:payload.enabled,time:payload.time,timezone:payload.timezone,weekdays:payload.weekdays,planName:payload.planName,endpoint:payload.subscription?.endpoint||''}),old=read315(DIGEST315,{value:'',at:0});if(!force&&old.value===digest&&Date.now()-Number(old.at||0)<21600000){if(sub)setRemote315('active');return !!sub}setRemote315('syncing');const res=await invoke315(payload);if(res.ok){write315(DIGEST315,{value:digest,at:Date.now()});setRemote315(sub?'active':'local',sub?'':'push_not_enabled');return !!sub}setRemote315('local',res.code||'server');return false}
const enableRemote315=async()=>{const p=await requestPermission315();if(p!=='granted'){setRemote315('local',p);return{ok:false,code:p}}if(!pushSupported315()){setRemote315('local','unsupported');return{ok:false,code:'unsupported'}}let sub;try{sub=await ensureSubscription315()}catch(error){setRemote315('local','subscribe');return{ok:false,code:'subscribe',error}}if(!sub){setRemote315('local','subscribe');return{ok:false,code:'subscribe'}}setRemote315('syncing');const res=await invoke315(remotePayload315(sub));if(res.ok){write315(DIGEST315,{value:JSON.stringify({...remotePayload315(sub),subscription:{endpoint:sub.endpoint}}),at:Date.now()});setRemote315('active');return{ok:true}}setRemote315('local',res.code||'server');return res}
const disableRemote315=async()=>{setRemote315('off');write315(DIGEST315,{value:'',at:0});try{await invoke315({action:'disable',enabled:false,time:cfg315().time,timezone:timezone315(),weekdays:schedule315().weekdays,planName:schedule315().planName})}catch{}}
const notify315=async info=>{const reg=await ensureSw315();const title='Zeit fürs Training 💪';const planName=info?.plan?.name||'Dein Training';const sessionName=info?.session?.title||info?.session?.name||info?.session?.day||'';const body=sessionName?`${sessionName} · ${planName}`:`${planName} steht heute an.`;try{if(reg?.showNotification){await reg.showNotification(title,{body,icon:'/fittogether-icon-192.png?v=230',badge:'/fittogether-icon-192.png?v=230',tag:`ft-training-${dateKey315()}`,renotify:false,data:{url:'/?reminder=training'}});return true}if(typeof Notification!=='undefined'){new Notification(title,{body,icon:'/fittogether-icon-192.png?v=230',tag:`ft-training-${dateKey315()}`});return true}}catch{}return false}
let checking315=false
const checkReminder315=async()=>{if(checking315)return;checking315=true;try{const c=cfg315();if(!c.enabled||permission315()!=='granted'||remoteActive315())return;const info=todayPlan315();if(!info)return;const now=new Date(),[h,m]=c.time.split(':').map(Number),due=new Date(now);due.setHours(h,m,0,0);if(now<due)return;const key=dateKey315();if(read315(LAST315,'')===key)return;if(await notify315(info))write315(LAST315,key)}finally{checking315=false}}
const status315=()=>{const c=cfg315(),info=todayPlan315(),p=permission315(),r=remote315();if(!c.enabled)return'Erinnerung ist aus';if(p==='denied')return'Mitteilungen sind auf diesem Gerät blockiert';if(r.status==='active')return`Push aktiv · ${c.time} Uhr · auch bei geschlossener App`;if(r.status==='syncing')return'Push wird eingerichtet …';if(isIOS315()&&!standalone315())return'Für Push FitTogether zum Home-Bildschirm hinzufügen';if(p==='unsupported'||!pushSupported315())return'System-Push wird hier nicht unterstützt';if(p!=='granted')return'Mitteilungen auf diesem Gerät noch nicht erlaubt';if(r.error==='signin')return`Nur lokal · für Push bitte anmelden`;if(r.error==='server'||r.error==='subscribe')return`Push gerade nicht verbunden · lokale Erinnerung ${c.time} Uhr`;if(info)return`Lokale Erinnerung · heute ${c.time} Uhr`;return`Lokale Erinnerung · ${c.time} Uhr gespeichert`}
const mount315=()=>{const h1=[...document.querySelectorAll('.page-head h1,h1')].find(x=>x.textContent?.trim()==='Einstellungen');if(!h1)return;const page=h1.closest('.page')||h1.parentElement?.parentElement;if(!page||page.querySelector('.training-reminder-v315'))return;const list=page.querySelector('.settings-list');if(!list)return;const c=cfg315();const wrap=document.createElement('section');wrap.className='training-reminder-v315';wrap.innerHTML=`<div class="training-reminder-title-v315"><div><small>TRAININGSERINNERUNG</small><strong>An Trainingstagen erinnern</strong><p>Nur wenn für den jeweiligen Tag ein Training in deinem Plan steht.</p></div><button type="button" class="training-reminder-toggle-v315 ${c.enabled?'on':''}" aria-label="Trainingserinnerung" aria-pressed="${c.enabled}"><i></i></button></div><div class="training-reminder-options-v315 ${c.enabled?'':'hidden'}"><label><span>Uhrzeit</span><input type="time" value="${esc315(c.time)}" step="300"></label><button type="button" class="training-reminder-setup-v315">Push auf diesem Gerät aktivieren</button><div class="training-reminder-status-v315"></div></div>`;list.after(wrap);const toggle=wrap.querySelector('.training-reminder-toggle-v315'),options=wrap.querySelector('.training-reminder-options-v315'),input=wrap.querySelector('input'),status=wrap.querySelector('.training-reminder-status-v315'),setup=wrap.querySelector('.training-reminder-setup-v315');const refresh=()=>{const cc=cfg315(),r=remote315();toggle.classList.toggle('on',cc.enabled);toggle.setAttribute('aria-pressed',String(cc.enabled));options.classList.toggle('hidden',!cc.enabled);input.value=cc.time;status.textContent=status315();setup.hidden=!cc.enabled||r.status==='active'||r.status==='syncing'};toggle.onclick=async()=>{const cc=cfg315();if(!cc.enabled){saveCfg315({...cc,enabled:true});write315(LAST315,'');refresh();await enableRemote315();refresh();checkReminder315()}else{saveCfg315({...cc,enabled:false});write315(LAST315,'');refresh();await disableRemote315();refresh()}};setup.onclick=async()=>{setup.disabled=true;await enableRemote315();setup.disabled=false;refresh()};input.onchange=async()=>{const cc=cfg315();saveCfg315({...cc,time:input.value||'18:00'});write315(LAST315,'');setRemote315('syncing');refresh();await syncRemote315(true);refresh();checkReminder315()};refresh()}
if(typeof document!=='undefined'){
  const obs=new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length))requestAnimationFrame(()=>mount315())})
  const start=()=>{mount315();obs.observe(document.body,{childList:true,subtree:true});setInterval(()=>{syncRemote315(false);checkReminder315()},60000);window.addEventListener('pageshow',()=>{syncRemote315(false);checkReminder315()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){mount315();syncRemote315(false);checkReminder315()}});setTimeout(()=>{syncRemote315(false);checkReminder315()},1200);window.FitTogetherReminderSync=()=>syncRemote315(true)}
  document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})
}
