// FitTogether V2.0.150: Help & Anleitung lives on the More page, not Settings.
const help317=[
 ['Startseite & heutiges Training','Wochenfortschritt und Tagesplan','Auf der Startseite siehst du deinen Wochenfortschritt und dein nächstes Workout. Der gelbe Play-Button startet – wenn vorhanden – das für heute geplante Training.','home'],
 ['Training starten','Plan, freies Training oder Schnellstart','Unter Workouts kannst du einen Wochenplan öffnen, Übungen frei zusammenstellen oder einen Schnellstart beginnen.','play'],
 ['Trainingspläne','Tage, Übungen, Sätze und Cardio','Öffne im Planeditor einen Wochentag und lege Übungen fest. Bei Krafttraining stellst du Sätze, Wiederholungen, Gewicht und RIR ein; bei Cardio die Dauer.','plan'],
 ['Übungen','Suchen, filtern und Ausführung ansehen','Die Übungsbibliothek enthält Kraft, Cardio, Yoga und Dehnen. Suche nach Namen oder filtere nach Trainingsart und verfügbarem Equipment.','exercise'],
 ['Während des Trainings','Sätze, RIR und Timer','Nach einem Kraftsatz trägst du dein Ergebnis und RIR ein. Der Pausentimer läuft weiter. Cardio verwendet stattdessen einen Zeittimer und speichert die tatsächliche Dauer.','training'],
 ['Smarter Trainer','Planung und Empfehlungen','Der Smarte Trainer erstellt Pläne passend zu deinen Vorgaben. Gespeicherte Trainingswerte, RIR und Wochenfeedback helfen bei Empfehlungen für die nächste Einheit.','coach'],
 ['Statistik & Fortschritt','Training, Gewicht und Leistung','Hier findest du Trainingsaktivität, Gewichtsentwicklung und den Fortschritt einzelner Kraftübungen. Die Bereiche lassen sich kompakt auf- und zuklappen.','stats'],
 ['Profil & Equipment','Körperdaten, Ziel und Geräte','Im Profil verwaltest du Körperdaten und Ziel. Unter Equipment legst du deine vorhandenen Geräte und Gewichte fest, damit Vorschläge dazu passen.','profile'],
 ['Trainingserinnerungen','Push nur an geplanten Trainingstagen','Unter Einstellungen kannst du eine Uhrzeit wählen. Push wird nur an Wochentagen gesendet, an denen ein Training geplant ist, und funktioniert auch bei geschlossener App.','bell'],
 ['Konto & Cloud-Sync','Daten auf deinen Geräten','Mit deinem Konto werden unterstützte FitTogether-Daten synchronisiert. Laufende Trainings bleiben lokal stabil und werden anschließend abgeglichen.','cloud']
]
const art317=type=>`<div class="ft317-art ${type}"><div class="ft317-top"><b>FitTogether</b><i></i></div><div class="ft317-screen"><span class="a"></span><span class="b"></span><span class="c"></span><div class="ft317-focus">${type==='play'?'▶ TRAINING STARTEN':type==='plan'?'MONTAG · 3 ÜBUNGEN':type==='training'?'SATZ 2 · RIR 2':type==='stats'?'FORTSCHRITT ↗':type==='bell'?'🔔 18:00 UHR':type==='cloud'?'☁ SYNCHRONISIERT':type==='coach'?'✦ SMART COACH':type==='profile'?'PROFIL & EQUIPMENT':type==='exercise'?'⌕ ÜBUNG SUCHEN':'HEUTIGES TRAINING'}</div></div></div>`
const close317=()=>{document.querySelector('.ft317-page')?.remove();document.documentElement.classList.remove('ft317-open')}
const open317=()=>{close317();const page=document.createElement('div');page.className='ft317-page';page.innerHTML=`<div class="ft317-head"><button type="button" aria-label="Zurück">‹</button><div><small>HILFE & ANLEITUNG</small><h1>So funktioniert FitTogether</h1><p>Tippe auf einen Bereich. Dort findest du eine kurze Erklärung mit Bild.</p></div></div><div class="ft317-list">${help317.map((x,i)=>`<article><button type="button" class="ft317-row" aria-expanded="false"><span class="ft317-num">${String(i+1).padStart(2,'0')}</span><span><b>${x[0]}</b><small>${x[1]}</small></span><strong>›</strong></button><div class="ft317-detail" hidden>${art317(x[3])}<p>${x[2]}</p></div></article>`).join('')}</div><div class="ft317-foot">FitTogether V2.0.150 · Hilfe & Anleitung</div>`;document.body.appendChild(page);document.documentElement.classList.add('ft317-open');page.querySelector('.ft317-head button').onclick=close317;page.querySelectorAll('.ft317-row').forEach(btn=>btn.onclick=()=>{const a=btn.closest('article'),d=a.querySelector('.ft317-detail'),open=btn.getAttribute('aria-expanded')==='true';page.querySelectorAll('article.open').forEach(o=>{if(o===a)return;o.classList.remove('open');o.querySelector('.ft317-row')?.setAttribute('aria-expanded','false');const od=o.querySelector('.ft317-detail');if(od)od.hidden=true});btn.setAttribute('aria-expanded',String(!open));a.classList.toggle('open',!open);d.hidden=open;if(!open)setTimeout(()=>a.scrollIntoView({behavior:'smooth',block:'nearest'}),50)})}
const mount317=()=>{document.querySelectorAll('.ft-help-v316').forEach(x=>x.remove());const h1=[...document.querySelectorAll('.page-head h1,h1')].find(x=>x.textContent?.trim()==='FitTogether');if(!h1)return;const page=h1.closest('.page')||h1.parentElement?.parentElement;if(!page||page.querySelector('.ft317-menu'))return;const list=page.querySelector('.menu-list');if(!list)return;const buttons=[...list.querySelectorAll(':scope > button')];const timer=buttons.find(b=>/Timer/i.test(b.textContent||''));const b=document.createElement('button');b.type='button';b.className='ft317-menu';b.innerHTML='<span class="ft317-q">?</span><span><strong>Hilfe & Anleitung</strong><small>Alle Funktionen mit Bildern erklärt</small></span><b>›</b>';b.onclick=open317;if(timer)list.insertBefore(b,timer);else list.appendChild(b)}
if(typeof document!=='undefined'){const boot=()=>{mount317();new MutationObserver(()=>requestAnimationFrame(mount317)).observe(document.body,{childList:true,subtree:true})};document.body?boot():document.addEventListener('DOMContentLoaded',boot,{once:true})}
