// FitTogether V2.0.153: one-tap Smart Coach targets for the next planned strength session.
const r318=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const w318=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const n318=v=>{const n=Number(String(v??'').replace(',','.').replace('+',''));return Number.isFinite(n)?n:0}
const e318=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const norm318=s=>String(s||'').toLocaleLowerCase('de-DE').replace(/[^a-z0-9äöüß]+/g,' ').trim()
const sessions318=p=>Array.isArray(p?.sessions)?p.sessions:Array.isArray(p?.workouts)?p.workouts:Array.isArray(p?.days)?p.days:[]
const name318=s=>typeof s==='string'?s:(s?.title||s?.name||'Training')
const exs318=s=>typeof s==='string'?[]:(Array.isArray(s?.exercises)?s.exercises:[])
const smart318=p=>p?.smart===true||/^smart plan/i.test(String(p?.name||''))
const cardio318=x=>{const t=`${x?.kind||''} ${x?.loadType||''} ${x?.category||''} ${x?.equipment||''} ${x?.name||''}`.toLowerCase();return /cardio|fahrrad|ergometer|bike|cycling|laufband|treadmill|rudergerät|rower|rowing/.test(t)}
const targetSession318=box=>{const plans=r318('ft-plans',[]).filter(Boolean);if(!plans.length)return null;let pi=-1;for(let i=plans.length-1;i>=0;i--){if(smart318(plans[i])){pi=i;break}}if(pi<0)pi=plans.length-1;const plan=plans[pi],ss=sessions318(plan);if(!ss.length)return null;const title=norm318(box?.querySelector('.smart-today-top-v297 h2')?.textContent);let si=title?ss.findIndex(s=>norm318(name318(s))===title):-1;if(si<0)si=0;return{plans,plan,pi,session:ss[si],si}}
const history318=name=>{const key=norm318(name),groups=[];r318('ft-completed-workouts',[]).forEach((work,wi)=>{const sets=(Array.isArray(work?.sets)?work.sets:[]).filter(s=>norm318(s?.exercise)===key&&!cardio318(s));if(!sets.length)return;groups.push({id:wi,date:n318(work?.date),sets:sets.map((s,i)=>({set:n318(s?.set)||i+1,reps:n318(s?.actualReps??s?.reps??s?.plannedReps),weight:n318(s?.actualWeight??s?.weight??s?.plannedWeight),extra:n318(s?.actualExtraWeight??s?.extraWeight??s?.plannedExtraWeight),rir:s?.rir==null?null:n318(s.rir),rirTarget:s?.rirTarget==null?2:n318(s.rirTarget),loadType:String(s?.loadType||'') })).sort((a,b)=>a.set-b.set)})});return groups.sort((a,b)=>a.date-b.date)}
const kind318=(ex,last)=>{const t=`${ex?.equipment||''} ${ex?.name||''} ${last?.sets?.[0]?.loadType||''}`.toLowerCase();if(/dumbbell|kurzhantel/.test(t))return'dumbbell';if(/barbell|langhantel|ez bar|sz-stange/.test(t))return'barbell';if(/bodyweight|body weight|körpergewicht|klimm|pull.?up|liegestütz|push.?up|dip/.test(t))return'bodyweight';return'other'}
const weights318=k=>{const key=k==='dumbbell'?'ft-dumbbell-weights':k==='barbell'?'ft-barbell-weights':'';if(!key)return[];return[...new Set(r318(key,[]).map(x=>typeof x==='object'?(x?.weight??x?.value??x?.kg):x).map(n318).filter(Boolean))].sort((a,b)=>a-b)}
const avg318=a=>{const x=a.filter(v=>v!=null);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null}
const summary318=g=>{const weighted=g.sets.filter(s=>s.weight>0||s.extra>0),max=weighted.length?Math.max(...weighted.map(s=>s.weight+s.extra)):0,total=g.sets.reduce((s,x)=>s+x.reps,0),rir=avg318(g.sets.map(s=>s.rir));return{max,total,rir}}
const coach318=(ex,h)=>{const last=h.at(-1),prev=h.at(-2);if(!last||!prev)return null;const a=summary318(last),b=summary318(prev),k=kind318(ex,last),next=weights318(k).find(v=>v>a.max+.001)||null,down=a.max<b.max||(a.max===b.max&&a.total<b.total),repGain=a.max===b.max&&a.total>b.total,reserve=a.rir!=null&&a.rir>=2.5,hard=a.rir!=null&&a.rir<=1;let mode='hold',label='Belastung bestätigen',reason='Die letzte Leistung wird zuerst sauber bestätigt.';if(down||hard){label='Belastung halten';reason=hard?'RIR war nah am Limit – kein Sprung nötig.':'Leistung zuletzt niedriger – erst stabilisieren.'}else if(repGain&&reserve&&next){mode='load';label=`${next.toLocaleString('de-DE',{maximumFractionDigits:1})}${k==='dumbbell'?' kg/Arm':k==='barbell'?' kg gesamt':' kg'} testen`;reason='Mehr Wiederholungen plus Reserve – nächste verfügbare Gewichtsstufe.'}else if(a.rir!=null&&a.rir>=2){mode='reps';label='+1 Wdh. pro Satz';reason='Noch Reserve vorhanden – zuerst Wiederholungen ausbauen.'}const count=Math.max(1,Math.min(8,Number(ex?.sets)||last.sets.length||3)),src=Array.from({length:count},(_,i)=>last.sets[i]||last.sets.at(-1)).map(s=>({reps:Math.max(1,s.reps),weight:k==='bodyweight'?0:s.weight,extraWeight:k==='bodyweight'?s.extra:0,useExtra:k==='bodyweight'&&s.extra>0,rirTarget:Math.max(0,Math.min(4,s.rirTarget||2))}));if(mode==='reps')src.forEach(s=>s.reps=Math.min(30,s.reps+1));if(mode==='load'&&next)src.forEach(s=>{s.weight=next;s.reps=Math.max(1,s.reps-1)});return{mode,label,reason,kind:k,sets:src,confidence:h.length>=5?'hoch':h.length>=3?'gut':'Basis'}}
const label318=c=>{const reps=c.sets.map(s=>s.reps),min=Math.min(...reps),max=Math.max(...reps),s=c.sets[0];let load=c.kind==='bodyweight'?(s.useExtra?`+${s.extraWeight} kg Zusatz`:'Körpergewicht'):`${s.weight.toLocaleString('de-DE',{maximumFractionDigits:1})}${c.kind==='dumbbell'?' kg/Arm':c.kind==='barbell'?' kg gesamt':' kg'}`;return`${c.sets.length} Sätze · ${min===max?min:`${min}–${max}`} Wdh. · ${load} · RIR ${s.rirTarget}`}
const digest318=(t,items)=>`${t?.plan?.id||t?.plan?.name||t?.pi}|${t?.si}|${items.map(x=>`${x.name}:${x.coach.mode}:${label318(x.coach)}`).join('|')}`
const apply318=(t,items,digest)=>{const plans=r318('ft-plans',[]),plan=plans[t.pi],session=sessions318(plan)?.[t.si];if(!plan||!session||typeof session==='string')return false;const xs=exs318(session),loads=r318('ft-exercise-loads-v275',{}),now=Date.now();let changed=0;items.forEach(item=>{const ex=xs.find(x=>norm318(x?.name||x?.title)===norm318(item.name));if(!ex)return;const sets=item.coach.sets.map(s=>({...s})),first=sets[0];ex.sets=sets.length;ex.plannedSets=sets;ex.smartRecommendation={...first,reason:item.coach.reason,source:'Smart Coach',updatedAt:now};loads[ex.name]={...(loads[ex.name]||{}),sets,reps:first.reps,weight:first.weight,extraWeight:first.extraWeight,useExtra:first.useExtra,rirTarget:first.rirTarget,reason:item.coach.reason,source:'Smart Coach',updatedAt:now};changed++});if(!changed)return false;w318('ft-plans',plans);w318('ft-exercise-loads-v275',loads);w318('ft-smart-coach-applied-v318',{key:`${t.pi}|${t.si}`,digest,at:now,count:changed});try{window.FitTogetherCloud?.upload?.()}catch{};return true}
const render318=()=>{const box=document.querySelector('.smart-today-v297');if(!box||document.querySelector('.active-training,.rest-overlay,.training-overlay'))return;const t=targetSession318(box);if(!t)return;const items=exs318(t.session).filter(x=>!cardio318(x)&&!x?.warmup).map(ex=>{const h=history318(ex?.name||ex?.title),coach=coach318(ex,h);return coach?{name:ex?.name||ex?.title,coach,count:h.length}:null}).filter(Boolean);let panel=box.querySelector('.smart-apply-v318');if(!items.length){panel?.remove();return}const digest=digest318(t,items),saved=r318('ft-smart-coach-applied-v318',{}),applied=saved.key===`${t.pi}|${t.si}`&&saved.digest===digest,sig=digest+'|'+applied;if(!panel){panel=document.createElement('section');panel.className='smart-apply-v318';const after=box.querySelector('.smart-progress-v309');after?.insertAdjacentElement('afterend',panel)||box.querySelector('.smart-preview-v297')?.insertAdjacentElement('beforebegin',panel)||box.appendChild(panel)}if(panel.dataset.sig===sig)return;panel.dataset.sig=sig;panel.innerHTML=`<div class="smart-apply-head-v318"><div><small>SMART COACH · AUTO-VORBEREITUNG</small><strong>Nächste Sätze vorbereiten</strong></div><span>${items.length}</span></div><div class="smart-apply-list-v318">${items.slice(0,4).map(x=>`<div><b>${e318(x.name)}</b><span>${e318(x.coach.label)}</span><em>${e318(label318(x.coach))}</em><small>${e318(x.coach.confidence)} · ${e318(x.coach.reason)}</small></div>`).join('')}</div>${items.length>4?`<p>+ ${items.length-4} weitere Übungen werden ebenfalls vorbereitet.</p>`:''}<button type="button" ${applied?'disabled':''}>${applied?'✓ Ziele übernommen':`${items.length} Coach-Ziel${items.length>1?'e':''} übernehmen`}</button><small class="smart-apply-foot-v318">${applied?'Beim Start werden diese Werte als geplante Sätze geladen.':'Übernimmt Satzanzahl, Wiederholungen, Gewicht und RIR-Ziel aus deiner Leistungshistorie.'}</small>`;panel.querySelector('button')?.addEventListener('click',()=>{if(apply318(t,items,digest)){panel.dataset.sig='';render318()}})}
let q318=false;const run318=()=>{if(q318)return;q318=true;requestAnimationFrame(()=>{q318=false;render318()})}
if(typeof document!=='undefined'){const start=()=>{render318();new MutationObserver(run318).observe(document.body,{childList:true,subtree:true});window.addEventListener('pageshow',run318);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')run318()})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
