// FitTogether V2.0.154: weekly Smart Coach preview combines muscle feedback with performance/RIR before changing Smart Plans.
const r319=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const w319=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
const n319=v=>{const n=Number(v);return Number.isFinite(n)?n:0}
const norm319=s=>String(s||'').toLowerCase().replace(/[^a-z0-9äöüß]+/g,' ').trim()
const groups319=['Brust','Rücken','Beine','Schultern','Bizeps','Trizeps','Bauch','Gesäß','Waden']
const muscle319=(name,raw='')=>{const s=`${name||''} ${raw||''}`.toLowerCase();if(/chest|pector|brust|bench|fly|push.?up|liegestütz/.test(s))return'Brust';if(/lat|back|rücken|row|rudern|pull.?up|klimm|deadlift|kreuzheben/.test(s))return'Rücken';if(/quad|hamstring|thigh|leg|beine|squat|kniebeuge|lunge|ausfallschritt/.test(s))return'Beine';if(/delt|shoulder|schulter|overhead|seitheben/.test(s))return'Schultern';if(/biceps|bizeps|curl/.test(s))return'Bizeps';if(/triceps|trizeps|extension|pushdown|dip/.test(s))return'Trizeps';if(/abs|abdom|core|bauch|crunch|plank/.test(s))return'Bauch';if(/glute|gesäß|hip thrust/.test(s))return'Gesäß';if(/calf|wade/.test(s))return'Waden';return''}
const smart319=p=>p?.smart===true||/^smart plan/i.test(String(p?.name||''))
const planMap319=()=>{const m=new Map();r319('ft-plans',[]).forEach(p=>(p?.sessions||[]).forEach(s=>{if(typeof s==='string')return;(s?.exercises||[]).forEach(x=>{const k=norm319(x?.name);if(k)m.set(k,muscle319(x?.name,`${x?.muscle||''} ${x?.query||''}`))})}));return m}
const week319=()=>{const start=Date.now()-7*86400000,map=planMap319(),score=Object.fromEntries(groups319.map(g=>[g,{sets:0,rir:[],down:0,stalled:0}])),by=new Map();r319('ft-completed-workouts',[]).forEach((w,wi)=>{if(n319(w?.date)<start)return;(w?.sets||[]).forEach(s=>{if(s?.kind==='cardio'||s?.loadType==='cardio')return;const key=norm319(s?.exercise),g=map.get(key)||muscle319(s?.exercise);if(!g||!score[g])return;score[g].sets++;const rv=s?.rir==='4+'?4:Number(s?.rir);if(Number.isFinite(rv))score[g].rir.push(rv);if(!by.has(key))by.set(key,[]);by.get(key).push({wi,date:n319(w.date),reps:n319(s?.actualReps??s?.reps),load:n319(s?.actualWeight??s?.weight)+n319(s?.actualExtraWeight??s?.extraWeight),g})})});for(const rows of by.values()){const ses=new Map();rows.forEach(x=>{const id=`${x.wi}|${x.date}`;if(!ses.has(id))ses.set(id,{date:x.date,v:0,g:x.g});const z=ses.get(id),v=x.load>0?x.load*1000+x.reps:x.reps;z.v=Math.max(z.v,v)});const a=[...ses.values()].sort((x,y)=>x.date-y.date),last=a.at(-1),prev=a.at(-2),third=a.at(-3);if(last&&prev&&last.v<prev.v)score[last.g].down++;if(last&&prev&&third&&last.v===prev.v&&prev.v===third.v)score[last.g].stalled++}return score}
const proposal319=()=>{const score=week319(),answers=r319('ft-weekly-muscle-feedback',{});return groups319.map(group=>{const x=score[group],avg=x.rir.length?x.rir.reduce((a,b)=>a+b,0)/x.rir.length:null,assessment=answers[group]||(x.sets===0?'zu wenig':x.sets<5?'zu wenig':x.sets>13?'zu viel':'passt');let delta=assessment==='zu wenig'?1:assessment==='zu viel'?-1:0,reason=assessment==='zu wenig'?'Wochenfeedback: zu wenig Reiz':assessment==='zu viel'?'Wochenfeedback: zu viel Belastung':'Belastung passt';if(delta>0&&(x.down>0||(avg!=null&&avg<=1.5))){delta=0;reason=x.down>0?'Keine Volumensteigerung: Leistung zuletzt rückläufig':`Keine Volumensteigerung: RIR Ø ${avg.toFixed(1)} bereits sehr hart`}else if(delta>0&&x.stalled>0){reason='Stagnation + zu wenig Reiz: vorsichtig +1 Satz'}if(delta<0&&x.down>0)reason='Zu viel Belastung + Leistungsrückgang: −1 Satz';return{group,delta,reason,sets:x.sets,avg}}).filter(x=>x.delta!==0||x.reason.startsWith('Keine'))}
const apply319=p=>{const plans=r319('ft-plans',[]);let changed=0;plans.forEach(plan=>{if(!smart319(plan))return;(plan.sessions||[]).forEach(s=>{if(typeof s==='string')return;(s.exercises||[]).forEach(x=>{const hit=p.find(z=>z.group===muscle319(x?.name,`${x?.muscle||''} ${x?.query||''}`));if(!hit||!hit.delta)return;const old=Math.max(1,n319(x.sets)||3),next=Math.max(1,Math.min(5,old+hit.delta));if(next===old)return;x.sets=next;if(Array.isArray(x.plannedSets)){const seed=x.plannedSets.at(-1)||x.smartRecommendation||{};while(x.plannedSets.length<next)x.plannedSets.push({...seed});x.plannedSets=x.plannedSets.slice(0,next)}changed++})})});if(changed){w319('ft-plans',plans);w319('ft-weekly-smart-coach-last',{date:Date.now(),proposal:p});window.FitTogetherCloud?.upload?.();window.dispatchEvent(new CustomEvent('ft-stats-refresh'))}return changed}
const open319=()=>{document.querySelector('.weekly-coach-modal-v319')?.remove();const p=proposal319(),ov=document.createElement('div');ov.className='weekly-coach-modal-v319';ov.innerHTML=`<div class="weekly-coach-sheet-v319"><div class="weekly-coach-head-v319"><div><small>SMART COACH · NÄCHSTE WOCHE</small><h2>Plananpassung prüfen</h2><p>Muskelgefühl, Trainingsvolumen, RIR und Leistungsentwicklung werden gemeinsam bewertet.</p></div><button data-close>×</button></div><div class="weekly-coach-list-v319">${p.length?p.map(x=>`<div><span><strong>${x.group}</strong><small>${x.reason}</small></span><b class="${x.delta>0?'up':x.delta<0?'down':'hold'}">${x.delta>0?'+1 Satz':x.delta<0?'−1 Satz':'Halten'}</b></div>`).join(''):'<p>Diese Woche ist keine Planänderung nötig.</p>'}</div><div class="weekly-coach-note-v319">Gewicht/Wiederholungen bleiben Aufgabe des Satz-Coachs. So erhöht FitTogether nicht gleichzeitig Last und Wochenvolumen.</div><button class="weekly-coach-apply-v319" data-apply ${p.some(x=>x.delta)?'':'disabled'}>Änderungen für nächste Woche übernehmen</button></div>`;document.body.appendChild(ov);ov.querySelector('[data-close]').onclick=()=>ov.remove();ov.addEventListener('click',e=>{if(e.target===ov)ov.remove()});ov.querySelector('[data-apply]')?.addEventListener('click',e=>{const count=apply319(p);e.currentTarget.disabled=true;e.currentTarget.textContent=count?`✓ ${count} Plananpassungen gespeichert`:'Keine passenden Smart-Plan-Übungen gefunden'})}
const enhance319=()=>{const page=[...document.querySelectorAll('.page')].find(p=>/Statistik/.test(p.querySelector('.page-head h1')?.textContent||''));if(!page||page.querySelector('.weekly-coach-v319'))return;const anchor=page.querySelector('.weekly-review-v310')||page.querySelector('.weekly-muscle-v281');const b=document.createElement('button');b.type='button';b.className='weekly-coach-v319';b.innerHTML='<span><small>SMART COACH</small><strong>Nächste Woche anpassen</strong><em>Feedback + RIR + Leistung gemeinsam prüfen</em></span><b>Prüfen</b>';b.onclick=open319;anchor?.insertAdjacentElement('afterend',b)||page.appendChild(b)}
let q319=false;const schedule319=()=>{if(q319||document.querySelector('.active-training,.rest-overlay,.training-overlay'))return;q319=true;requestAnimationFrame(()=>{q319=false;enhance319()})};if(typeof document!=='undefined'){const start=()=>{enhance319();new MutationObserver(schedule319).observe(document.body,{childList:true,subtree:true});window.addEventListener('ft-stats-refresh',schedule319)};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
