// FitTogether V2.0.155: show the app's existing exercise images while editing a plan.
const img320=x=>String(x?.thumbUrl||x?.image||x?.gifUrl||x?.imageUrl||x?.thumbnail||'').trim()
const norm320=s=>String(s||'').toLocaleLowerCase('de-DE').replace(/[^a-z0-9äöüß]+/g,' ').trim()
const plans320=()=>{try{return JSON.parse(localStorage.getItem('ft-plans')||'[]')||[]}catch{return[]}}
const esc320=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const exerciseImages320=()=>{const map=new Map();for(const p of plans320())for(const s of p?.sessions||[]){if(typeof s==='string')continue;for(const x of s?.exercises||[]){const u=img320(x),keys=[x?.name,x?.query,x?.title].map(norm320).filter(Boolean);if(u)keys.forEach(k=>map.set(k,u))}}return map}
const enhance320=editor=>{if(!editor)return;const map=exerciseImages320();editor.querySelectorAll('.plan-ex-v313').forEach(row=>{if(row.dataset.image320)return;row.dataset.image320='1';const title=row.querySelector('.plan-ex-title-v313'),text=title?.querySelector('strong')?.textContent||'';if(!title)return;let url='';const plans=plans320(),key=norm320(text);outer:for(const p of plans)for(const s of p?.sessions||[]){if(typeof s==='string')continue;for(const x of s?.exercises||[]){if([x?.name,x?.query,x?.title].some(v=>norm320(v)===key)){url=img320(x)||map.get(norm320(x?.query))||'';if(url)break outer}}}if(!url)url=map.get(key)||'';const wrap=document.createElement('div');wrap.className='plan-ex-main-v320';const media=document.createElement('div');media.className='plan-ex-image-v320';if(url){const im=document.createElement('img');im.src=url;im.alt='';im.loading='lazy';im.decoding='async';im.onerror=()=>{media.classList.add('missing-v320');im.remove()};media.appendChild(im)}else media.classList.add('missing-v320');title.parentNode.insertBefore(wrap,title);wrap.append(media,title)})}
let queued320=false;const scan320=()=>{if(queued320)return;queued320=true;requestAnimationFrame(()=>{queued320=false;document.querySelectorAll('.plan-editor-backdrop-v313').forEach(enhance320)})}
if(typeof document!=='undefined'){const start=()=>{scan320();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length))scan320()}).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
