// FitTogether V2.0.156: show the app's exercise images in the plan editor and enlarge them on tap.
const img320=x=>String(x?.thumbUrl||x?.image||x?.gifUrl||x?.imageUrl||x?.thumbnail||'').trim()
const norm320=s=>String(s||'').toLocaleLowerCase('de-DE').replace(/[^a-z0-9äöüß]+/g,' ').trim()
const plans320=()=>{try{return JSON.parse(localStorage.getItem('ft-plans')||'[]')||[]}catch{return[]}}
const exerciseImages320=()=>{const map=new Map();for(const p of plans320())for(const s of p?.sessions||[]){if(typeof s==='string')continue;for(const x of s?.exercises||[]){const u=img320(x),keys=[x?.name,x?.query,x?.title].map(norm320).filter(Boolean);if(u)keys.forEach(k=>map.set(k,u))}}return map}
const closeZoom320=()=>document.querySelector('.plan-image-zoom-v320')?.remove()
const openZoom320=(url,name)=>{if(!url)return;closeZoom320();const ov=document.createElement('div');ov.className='plan-image-zoom-v320';ov.setAttribute('role','dialog');ov.setAttribute('aria-modal','true');ov.innerHTML=`<button type="button" class="plan-image-zoom-close-v320" aria-label="Bild schließen">×</button><div class="plan-image-zoom-card-v320"><img src="${url}" alt="${String(name||'Übung').replace(/["<>]/g,'')}"><small>${String(name||'Übung').replace(/[<>]/g,'')}</small></div>`;document.body.appendChild(ov);ov.querySelector('.plan-image-zoom-close-v320').onclick=closeZoom320;ov.addEventListener('click',e=>{if(e.target===ov)closeZoom320()});const onKey=e=>{if(e.key==='Escape'){closeZoom320();document.removeEventListener('keydown',onKey)}};document.addEventListener('keydown',onKey)}
const enhance320=editor=>{if(!editor)return;const map=exerciseImages320();editor.querySelectorAll('.plan-ex-v313').forEach(row=>{if(row.dataset.image320)return;row.dataset.image320='1';const title=row.querySelector('.plan-ex-title-v313'),text=title?.querySelector('strong')?.textContent||'';if(!title)return;let url='';const plans=plans320(),key=norm320(text);outer:for(const p of plans)for(const s of p?.sessions||[]){if(typeof s==='string')continue;for(const x of s?.exercises||[]){if([x?.name,x?.query,x?.title].some(v=>norm320(v)===key)){url=img320(x)||map.get(norm320(x?.query))||'';if(url)break outer}}}if(!url)url=map.get(key)||'';const wrap=document.createElement('div');wrap.className='plan-ex-main-v320';const media=document.createElement('button');media.type='button';media.className='plan-ex-image-v320';media.setAttribute('aria-label',url?`${text} Bild vergrößern`:'Kein Übungsbild vorhanden');if(url){const im=document.createElement('img');im.src=url;im.alt='';im.loading='lazy';im.decoding='async';im.onerror=()=>{media.classList.add('missing-v320');media.disabled=true;im.remove()};media.onclick=e=>{e.preventDefault();e.stopPropagation();openZoom320(url,text)};media.appendChild(im)}else{media.classList.add('missing-v320');media.disabled=true}title.parentNode.insertBefore(wrap,title);wrap.append(media,title)})}
let queued320=false;const scan320=()=>{if(queued320)return;queued320=true;requestAnimationFrame(()=>{queued320=false;document.querySelectorAll('.plan-editor-backdrop-v313').forEach(enhance320)})}
if(typeof document!=='undefined'){const start=()=>{scan320();new MutationObserver(m=>{if(m.some(x=>x.addedNodes.length))scan320()}).observe(document.body,{childList:true,subtree:true})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
