// FitTogether V2.0.163: connect training history, next-session targets and weekly volume into one Smart Coach loop.
const r327=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
const n327=v=>{const n=Number(String(v??'').replace(',','.').replace('+',''));return Number.isFinite(n)?n:0}
const norm327=s=>String(s||'').toLocaleLowerCase('de-DE').replace(/[^a-z0-9äöüß]+/g,' ').trim()
const esc327=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const cardio327=x=>/cardio|fahrrad|ergometer|bike|cycling|laufband|treadmill|rudergerät|rower|rowing/.test(`${x?.kind||''} ${x?.loadType||''} ${x?.category||''} ${x?.name||''}`.toLowerCase())
const sessions327=p=>Array.isArray(p?.sessions)?p.sessions:Array.isArray(p?.workouts)?p.workouts:Array.isArray(p?.days)?p.days:[]
const exs327=s=>typeof s==='string'?[]:(Array.isArray(s?.exercises)?s.exercises:[])
const smart327=p=>p?.smart===true||/^smart plan/i.test(String(p?.name||''))
const target327=()=>{const plans=r327('ft-plans',[]);let pi=-1;for(let i=plans.length-1;i>=0;i--)if(smart327(plans[i])){pi=i;break}if(pi<0)return null;const plan=plans[pi],ss=sessions327(plan);if(!ss.length)return null;const days=['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],today=days[new Date().getDay()],si=Math.max(0,ss.findIndex(s=>{const t=String(typeof s==='string'?s:(s?.day||s?.weekday||s?.title||s?.name||''));return norm327(t).includes(norm327(today))}));return{plan,session:ss[si],pi,si}}
const history327=name=>{const key=norm327(name),out=[];r327('ft-completed-workouts',[]).forEach((w,wi)=>{const sets=(w?.sets||[]).filter(s=>norm327(s?.exercise)===key&&!cardio327(s));if(sets.length)out.push({date:n327(w?.date)||wi,sets})});return out.sort((a,b)=>a.date-b.date)}
const avg327=a=>{const x=a.filter(Number.isFinite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null}
const state327=(ex,h)=>{const last=h.at(-1),prev=h.at(-2);if(!last)return{mode:'learn',label:'Daten sammeln',reason:'Nach zwei Einheiten kann der Coach zuverlässig anpassen.'};const sum=g=>({reps:g.sets.reduce((s,x)=>s+n327(x?.actualReps??x?.reps),0),load:Math.max(0,...g.sets.map(x=>n327(x?.actualWeight??x?.weight)+n327(x?.actualExtraWeight??x?.extraWeight))),rir:avg327(g.sets.map(x=>{const v=x?.rir==='4+'?4:Number(x?.rir);return Number.isFinite(v)?v:NaN}))});const a=sum(last),b=prev?sum(prev):null;if(!b)return{mode:'learn',label:'Noch 1 Einheit',reason:'Eine weitere Vergleichseinheit verbessert die Empfehlung.'};if((a.rir!=null&&a.rir<=1)||a.load<b.load||(a.load===b.load&&a.reps<b.reps))return{mode:'hold',label:'Belastung halten',reason:a.rir!=null&&a.rir<=1?'Letzte Einheit war bereits sehr hart.':'Leistung zuletzt niedriger – erst stabilisieren.'};if(a.load===b.load&&a.reps>b.reps&&a.rir!=null&&a.rir>=2.5)return{mode:'progress',label:'Steigerung bereit',reason:'Mehr Wiederholungen und noch Reserve vorhanden.'};if(a.rir!=null&&a.rir>=2)return{mode:'reps',label:'+1 Wdh. sinnvoll',reason:'Noch Reserve vorhanden – zuerst Wiederholungen steigern.'};return{mode:'hold',label:'Bestätigen',reason:'Aktuelle Belastung noch einmal sauber bestätigen.'}}
const weekly327=()=>{const last=r327('ft-weekly-smart-coach-last',null);if(!last?.date)return null;const age=Math.max(0,Date.now()-Number(last.date)),changes=(last.proposal||[]).filter(x=>n327(x?.delta)!==0);return{fresh:age<8*86400000,changes}}
const render327=()=>{if(document.querySelector('.active-training,.rest-overlay,.training-overlay'))return;const box=document.querySelector('.smart-today-v297');if(!box)return;const t=target327();if(!t)return;const items=exs327(t.session).filter(x=>!cardio327(x)&&!x?.warmup).map(ex=>({name:ex?.name||ex?.title||'Übung',state:state327(ex,history327(ex?.name||ex?.title))}));if(!items.length)return;let panel=box.querySelector('.smart-loop-v327');if(!panel){panel=document.createElement('section');panel.className='smart-loop-v327';const old=box.querySelector('.smart-apply-v318');old?.insertAdjacentElement('beforebegin',panel)||box.appendChild(panel)}const weekly=weekly327(),ready=items.filter(x=>['progress','reps'].includes(x.state.mode)).length,hold=items.filter(x=>x.state.mode==='hold').length,learn=items.filter(x=>x.state.mode==='learn').length,sig=items.map(x=>`${x.name}:${x.state.mode}`).join('|')+`|${weekly?.changes?.length||0}`;if(panel.dataset.sig===sig)return;panel.dataset.sig=sig;panel.innerHTML=`<div class="smart-loop-head-v327"><div><small>SMART COACH V2</small><strong>Dein Trainingskreislauf</strong></div><span>${ready?`${ready} ↑`:'✓'}</span></div><div class="smart-loop-flow-v327"><div><b>1</b><span><strong>Auswerten</strong><small>${items.length-learn}/${items.length} Übungen mit Vergleichsdaten</small></span></div><i>›</i><div><b>2</b><span><strong>Vorbereiten</strong><small>${ready} steigern · ${hold} halten${learn?` · ${learn} lernen`:''}</small></span></div><i>›</i><div><b>3</b><span><strong>Woche</strong><small>${weekly?.fresh?(weekly.changes.length?`${weekly.changes.length} Volumenänderungen aktiv`:'Volumen geprüft'):'Wochencheck noch offen'}</small></span></div></div><div class="smart-loop-next-v327">${items.slice(0,3).map(x=>`<div class="${x.state.mode}"><span><b>${esc327(x.name)}</b><small>${esc327(x.state.reason)}</small></span><strong>${esc327(x.state.label)}</strong></div>`).join('')}</div><small class="smart-loop-foot-v327">Der Satz-Coach steuert Gewicht/Wiederholungen. Der Wochen-Coach steuert nur das Volumen – beides wird nicht gleichzeitig aggressiv erhöht.</small>`}
let q327=false;const run327=()=>{if(q327)return;q327=true;requestAnimationFrame(()=>{q327=false;render327()})};if(typeof document!=='undefined'){const start=()=>{render327();new MutationObserver(run327).observe(document.body,{childList:true,subtree:true});window.addEventListener('pageshow',run327);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')run327()})};document.body?start():document.addEventListener('DOMContentLoaded',start,{once:true})}
